#! gmake

DEPTH = ../..

CSRCS =		       \
	font_metrics.c \
	print.c	       \
	ps.c	       \
	stubs.c	       \
	tblprint.c     \
	text.c	       \
	xlateimg.c     \
	$(NULL)

OBJS = $(CSRCS:.c=.o)

LIBRARY = libxlate.a

include $(DEPTH)/config/rules.mk
