#!/bin/sh
#
# Copyright (c) 1993 Michael A. Cooper
# Copyright (c) 1993 Regents of the University of California.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. All advertising materials mentioning features or use of this software
#    must display the following acknowledgement:
#	This product includes software developed by the University of
#	California, Berkeley and its contributors.
# 4. Neither the name of the University nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $Id: runmake,v 1.1 1996/01/31 23:30:15 dkarlton Exp $
#

#
# This script builds up a make command and then runs it
#

test -z "$ostype" && test -f ./os-type && {
	ostype="./os-type"
}
test -z "$ostype" && test -f config/os-type && {
	ostype="config/os-type"
}
test -z "$ostype" && test -f ../config/os-type && {
	ostype="../config/os-type"
}
if [ -z "$ostype" ]; then
	echo "Cannot find the os-type command."
	exit 1
fi

if [ ! -z "${MAKE}" ]; then
	Make="${MAKE}"
else
	Make="gmake"
fi

MAK="${Make} Make=\"${Make}\""
MKARGS="${MKCOM}"

OS="`$ostype`"

if [ ! -f "../config/os-${OS}.h" ]; then
	echo "Your OS (${OS}) is currently not supported."
	exit 1
fi

if [ -f ../mf/Makefile.var ]; then
	MKARGS="${MKARGS} -f ../mf/Makefile.var"
fi
if [ -f ../config/mf.${OS} ]; then
	MKARGS="${MKARGS} -f ../config/mf.${OS}"
fi
if [ ! -z "${ISGNUMAKE}" -a -f ../mf/GNUmf.aux ]; then
	MKARGS="${MKARGS} -f ../mf/GNUmf.aux"
fi
if [ -f ../Makefile.local ]; then
	MKARGS="${MKARGS} -f ../Makefile.local"
fi
if [ -f ../Makefile.local.${OS} ]; then
	MKARGS="${MKARGS} -f ../Makefile.local.${OS}"
fi
if [ -f Makefile.real ]; then
	MKARGS="${MKARGS} -f Makefile.real"
fi

${MAK} ${MKARGS} OS=${OS} $*
exit $?
