#! gmake
#! gmake
#! gmake
#! gmake
#! gmake

DEPTH = ../../..

include $(DEPTH)/sun-java/config/config.mk

GENERATED_HEADERS_CLASSFILES =		    \
	java.awt.Button			    \
	java.awt.Canvas			    \
	java.awt.CheckboxGroup		    \
	java.awt.Checkbox		    \
	java.awt.CheckboxMenuItem	    \
	java.awt.Choice		    \
	java.awt.Color			    \
	java.awt.Component		    \
	java.awt.Dialog			    \
	java.awt.Event			    \
	java.awt.FileDialog		    \
	java.awt.Font			    \
	java.awt.FontMetrics		    \
	java.awt.Frame			    \
	java.awt.Graphics		    \
	java.awt.Image			    \
	java.awt.Insets			    \
	java.awt.Label			    \
	java.awt.List			    \
	java.awt.Menu			    \
	java.awt.MenuBar		    \
	java.awt.MenuItem		    \
	java.awt.Rectangle		    \
	java.awt.Scrollbar		    \
	java.awt.TextArea		    \
	java.awt.TextComponent		    \
	java.awt.TextField		    \
	java.awt.Toolkit		    \
	java.awt.Window			    \
	java.awt.image.ColorModel	    \
	java.awt.image.ImageConsumer	    \
	java.awt.image.ImageObserver	    \
	java.awt.image.IndexColorModel	    \
	java.awt.image.DirectColorModel	    \
	java.util.Vector	    \
	sun.awt.image.Image		    \
	sun.awt.image.ImageRepresentation   \
	sun.awt.image.OffScreenImageSource  \
	sun.awt.macos.InterfaceThread	    \
	sun.awt.macos.MacintoshEvent	    \
	sun.awt.macos.MButtonPeer	    \
	sun.awt.macos.MCanvasPeer	    \
	sun.awt.macos.MComponentPeer	    \
	sun.awt.macos.MCheckboxPeer	    \
	sun.awt.macos.MCheckboxMenuItemPeer \
	sun.awt.macos.MChoicePeer           \
	sun.awt.macos.MDialogPeer	    \
	sun.awt.macos.MFramePeer	    \
	sun.awt.macos.MLabelPeer	    \
	sun.awt.macos.MListPeer		    \
	sun.awt.macos.MMenuBarPeer	    \
	sun.awt.macos.MMenuItemPeer	    \
	sun.awt.macos.MMenuPeer		    \
	sun.awt.macos.MPanelPeer	    \
	sun.awt.macos.MScrollbarPeer	    \
	sun.awt.macos.MTextAreaPeer	    \
	sun.awt.macos.MTextFieldPeer	    \
	sun.awt.macos.MToolkit		    \
	sun.awt.macos.MWindowPeer	    \
	sun.awt.macos.MacFontMetrics	    \
	sun.awt.macos.MacGraphics	    \
	sun.awt.macos.MacImage		    \
	$(NULL)

GENERATED_STUBS_CLASSFILES =		    \
	sun.awt.macos.MButtonPeer	    \
	sun.awt.macos.MCanvasPeer	    \
	sun.awt.macos.MCheckboxPeer	    \
	sun.awt.macos.MCheckboxMenuItemPeer \
	sun.awt.macos.MComponentPeer	    \
	sun.awt.macos.MDialogPeer	    \
	sun.awt.macos.MFramePeer	    \
	sun.awt.macos.MLabelPeer	    \
	sun.awt.macos.MListPeer		    \
	sun.awt.macos.MMenuBarPeer	    \
	sun.awt.macos.MMenuItemPeer	    \
	sun.awt.macos.MMenuPeer		    \
	sun.awt.macos.MScrollbarPeer	    \
	sun.awt.macos.MTextAreaPeer	    \
	sun.awt.macos.MTextFieldPeer	    \
	sun.awt.macos.MToolkit		    \
	sun.awt.macos.MWindowPeer	    \
	sun.awt.macos.MacFontMetrics	    \
	sun.awt.macos.MacGraphics	    \
	$(NULL)

include $(DEPTH)/sun-java/config/rules.mk

targets: mac_headers mac_stubs

mac:: targets
