/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_net_SocketImpl */

#ifndef _Included_java_net_SocketImpl
#define _Included_java_net_SocketImpl
struct Hjava_io_FileDescriptor;
struct Hjava_net_InetAddress;

typedef struct Classjava_net_SocketImpl {
    struct Hjava_io_FileDescriptor *fd;
    struct Hjava_net_InetAddress *address;
    long port;
    long localport;
} Classjava_net_SocketImpl;
HandleTo(java_net_SocketImpl);

#endif
