/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_io_FileDescriptor */

#ifndef _Included_java_io_FileDescriptor
#define _Included_java_io_FileDescriptor

typedef struct Classjava_io_FileDescriptor {
    long fd;
/* Inaccessible static: in */
/* Inaccessible static: out */
/* Inaccessible static: err */
} Classjava_io_FileDescriptor;
HandleTo(java_io_FileDescriptor);

extern /*boolean*/ long java_io_FileDescriptor_valid(struct Hjava_io_FileDescriptor* self);
struct Hjava_io_FileDescriptor;
extern struct Hjava_io_FileDescriptor *java_io_FileDescriptor_initSystemFD(struct Hjava_io_FileDescriptor* self,struct Hjava_io_FileDescriptor *,long);
#endif
