/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_lang_Integer */

#ifndef _Included_java_lang_Integer
#define _Included_java_lang_Integer

typedef struct Classjava_lang_Integer {
#define java_lang_Integer_MIN_VALUE	-2147483648L
#define java_lang_Integer_MAX_VALUE	2147483647L
    long value;
} Classjava_lang_Integer;
HandleTo(java_lang_Integer);

#endif
