/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_io_FileOutputStream */

#ifndef _Included_java_io_FileOutputStream
#define _Included_java_io_FileOutputStream
struct Hjava_io_FileDescriptor;

typedef struct Classjava_io_FileOutputStream {
    struct Hjava_io_FileDescriptor *fd;
} Classjava_io_FileOutputStream;
HandleTo(java_io_FileOutputStream);

struct Hjava_lang_String;
extern void java_io_FileOutputStream_open(struct Hjava_io_FileOutputStream* self,struct Hjava_lang_String *);
extern void java_io_FileOutputStream_write(struct Hjava_io_FileOutputStream* self,long);
extern void java_io_FileOutputStream_writeBytes(struct Hjava_io_FileOutputStream* self,HArrayOfByte *,long,long);
extern void java_io_FileOutputStream_close(struct Hjava_io_FileOutputStream* self);
#endif
