/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_lang_Object */

#ifndef _Included_java_lang_Object
#define _Included_java_lang_Object
struct Hjava_lang_Class;
extern struct Hjava_lang_Class *java_lang_Object_getClass(struct Hjava_lang_Object* self);
extern long java_lang_Object_hashCode(struct Hjava_lang_Object* self);
struct Hjava_lang_Object;
extern struct Hjava_lang_Object *java_lang_Object_clone(struct Hjava_lang_Object* self);
extern void java_lang_Object_notify(struct Hjava_lang_Object* self);
extern void java_lang_Object_notifyAll(struct Hjava_lang_Object* self);
extern void java_lang_Object_wait(struct Hjava_lang_Object* self,int64_t);
#endif
