/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class netscape/net/URLInputStream */

/* SYMBOL: "netscape/net/URLInputStream/open()V", Java_netscape_net_URLInputStream_open_stub */
JRI_PUBLIC_API(stack_item*)
Java_netscape_net_URLInputStream_open_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void netscape_net_URLInputStream_open(void *);
	(void) netscape_net_URLInputStream_open(_P_[0].p);
	return _P_;
}

/* SYMBOL: "netscape/net/URLInputStream/read([BII)I", Java_netscape_net_URLInputStream_read_stub */
JRI_PUBLIC_API(stack_item*)
Java_netscape_net_URLInputStream_read_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long netscape_net_URLInputStream_read(void *, void *, long, long);
	_P_[0].i = netscape_net_URLInputStream_read(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)));
	return _P_ + 1;
}

/* SYMBOL: "netscape/net/URLInputStream/available()I", Java_netscape_net_URLInputStream_available_stub */
JRI_PUBLIC_API(stack_item*)
Java_netscape_net_URLInputStream_available_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long netscape_net_URLInputStream_available(void *);
	_P_[0].i = netscape_net_URLInputStream_available(_P_[0].p);
	return _P_ + 1;
}

