/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class netscape/net/URLStreamHandlerFactory */

/* SYMBOL: "netscape/net/URLStreamHandlerFactory/pInit()V", Java_netscape_net_URLStreamHandlerFactory_pInit_stub */
JRI_PUBLIC_API(stack_item*)
Java_netscape_net_URLStreamHandlerFactory_pInit_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void netscape_net_URLStreamHandlerFactory_pInit(void *);
	(void) netscape_net_URLStreamHandlerFactory_pInit(NULL);
	return _P_;
}

/* SYMBOL: "netscape/net/URLStreamHandlerFactory/pSupportsProtocol(Ljava/lang/String;)Z", Java_netscape_net_URLStreamHandlerFactory_pSupportsProtocol_stub */
JRI_PUBLIC_API(stack_item*)
Java_netscape_net_URLStreamHandlerFactory_pSupportsProtocol_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long netscape_net_URLStreamHandlerFactory_pSupportsProtocol(void *, void *);
	_P_[0].i = (netscape_net_URLStreamHandlerFactory_pSupportsProtocol(_P_[0].p,((_P_[1].p))) ? 1 : 0);
	return _P_ + 1;
}

