/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Header for class java/applet/Applet */

#ifndef _java_applet_Applet_H_
#define _java_applet_Applet_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct java_applet_AppletStub;
struct java_net_URL;
struct java_lang_String;
struct java_applet_AppletContext;
struct java_awt_Dimension;
struct java_awt_Image;
struct java_applet_AudioClip;
struct java_lang_Class;

/*******************************************************************************
 * Class java/applet/Applet
 ******************************************************************************/

typedef struct java_applet_Applet java_applet_Applet;

#define classname_java_applet_Applet	"java/applet/Applet"

#define class_java_applet_Applet(env) \
	((struct java_lang_Class*)JRI_FindClass(env, classname_java_applet_Applet))

/*******************************************************************************
 * Public Methods
 ******************************************************************************/

#ifdef DEBUG

/*** public final setStub (Ljava/applet/AppletStub;)V ***/
extern JRI_PUBLIC_API(void)
java_applet_Applet_setStub(JRIEnv* env, struct java_applet_Applet* self, struct java_applet_AppletStub *a);

/*** public isActive ()Z ***/
extern JRI_PUBLIC_API(jbool)
java_applet_Applet_isActive(JRIEnv* env, struct java_applet_Applet* self);

/*** public getDocumentBase ()Ljava/net/URL; ***/
extern JRI_PUBLIC_API(struct java_net_URL *)
java_applet_Applet_getDocumentBase(JRIEnv* env, struct java_applet_Applet* self);

/*** public getCodeBase ()Ljava/net/URL; ***/
extern JRI_PUBLIC_API(struct java_net_URL *)
java_applet_Applet_getCodeBase(JRIEnv* env, struct java_applet_Applet* self);

/*** public getParameter (Ljava/lang/String;)Ljava/lang/String; ***/
extern JRI_PUBLIC_API(struct java_lang_String *)
java_applet_Applet_getParameter(JRIEnv* env, struct java_applet_Applet* self, struct java_lang_String *a);

/*** public getAppletContext ()Ljava/applet/AppletContext; ***/
extern JRI_PUBLIC_API(struct java_applet_AppletContext *)
java_applet_Applet_getAppletContext(JRIEnv* env, struct java_applet_Applet* self);

/*** public resize (II)V ***/
extern JRI_PUBLIC_API(void)
java_applet_Applet_resize(JRIEnv* env, struct java_applet_Applet* self, jint a, jint b);

/*** public resize (Ljava/awt/Dimension;)V ***/
extern JRI_PUBLIC_API(void)
java_applet_Applet_resize_1(JRIEnv* env, struct java_applet_Applet* self, struct java_awt_Dimension *a);

/*** public showStatus (Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
java_applet_Applet_showStatus(JRIEnv* env, struct java_applet_Applet* self, struct java_lang_String *a);

/*** public getImage (Ljava/net/URL;)Ljava/awt/Image; ***/
extern JRI_PUBLIC_API(struct java_awt_Image *)
java_applet_Applet_getImage(JRIEnv* env, struct java_applet_Applet* self, struct java_net_URL *a);

/*** public getImage (Ljava/net/URL;Ljava/lang/String;)Ljava/awt/Image; ***/
extern JRI_PUBLIC_API(struct java_awt_Image *)
java_applet_Applet_getImage_1(JRIEnv* env, struct java_applet_Applet* self, struct java_net_URL *a, struct java_lang_String *b);

/*** public getAudioClip (Ljava/net/URL;)Ljava/applet/AudioClip; ***/
extern JRI_PUBLIC_API(struct java_applet_AudioClip *)
java_applet_Applet_getAudioClip(JRIEnv* env, struct java_applet_Applet* self, struct java_net_URL *a);

/*** public getAudioClip (Ljava/net/URL;Ljava/lang/String;)Ljava/applet/AudioClip; ***/
extern JRI_PUBLIC_API(struct java_applet_AudioClip *)
java_applet_Applet_getAudioClip_1(JRIEnv* env, struct java_applet_Applet* self, struct java_net_URL *a, struct java_lang_String *b);

/*** public getAppletInfo ()Ljava/lang/String; ***/
extern JRI_PUBLIC_API(struct java_lang_String *)
java_applet_Applet_getAppletInfo(JRIEnv* env, struct java_applet_Applet* self);

/*** public getParameterInfo ()[[Ljava/lang/String; ***/
extern JRI_PUBLIC_API(jref)
java_applet_Applet_getParameterInfo(JRIEnv* env, struct java_applet_Applet* self);

/*** public play (Ljava/net/URL;)V ***/
extern JRI_PUBLIC_API(void)
java_applet_Applet_play(JRIEnv* env, struct java_applet_Applet* self, struct java_net_URL *a);

/*** public play (Ljava/net/URL;Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
java_applet_Applet_play_1(JRIEnv* env, struct java_applet_Applet* self, struct java_net_URL *a, struct java_lang_String *b);

/*** public init ()V ***/
extern JRI_PUBLIC_API(void)
java_applet_Applet_init(JRIEnv* env, struct java_applet_Applet* self);

/*** public start ()V ***/
extern JRI_PUBLIC_API(void)
java_applet_Applet_start(JRIEnv* env, struct java_applet_Applet* self);

/*** public stop ()V ***/
extern JRI_PUBLIC_API(void)
java_applet_Applet_stop(JRIEnv* env, struct java_applet_Applet* self);

/*** public destroy ()V ***/
extern JRI_PUBLIC_API(void)
java_applet_Applet_destroy(JRIEnv* env, struct java_applet_Applet* self);

/*** public <init> ()V ***/
extern JRI_PUBLIC_API(struct java_applet_Applet*)
java_applet_Applet_new(JRIEnv* env, struct java_lang_Class* clazz);

#else /* !DEBUG */

/*** public final setStub (Ljava/applet/AppletStub;)V ***/
#define java_applet_Applet_setStub(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_setStub, a))

/*** public isActive ()Z ***/
#define java_applet_Applet_isActive(env, obj) \
	(JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_isActive))

/*** public getDocumentBase ()Ljava/net/URL; ***/
#define java_applet_Applet_getDocumentBase(env, obj) \
	((struct java_net_URL *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_getDocumentBase))

/*** public getCodeBase ()Ljava/net/URL; ***/
#define java_applet_Applet_getCodeBase(env, obj) \
	((struct java_net_URL *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_getCodeBase))

/*** public getParameter (Ljava/lang/String;)Ljava/lang/String; ***/
#define java_applet_Applet_getParameter(env, obj, a) \
	((struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_getParameter, a))

/*** public getAppletContext ()Ljava/applet/AppletContext; ***/
#define java_applet_Applet_getAppletContext(env, obj) \
	((struct java_applet_AppletContext *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_getAppletContext))

/*** public resize (II)V ***/
#define java_applet_Applet_resize(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_resize, a, b))

/*** public resize (Ljava/awt/Dimension;)V ***/
#define java_applet_Applet_resize_1(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_resize_1, a))

/*** public showStatus (Ljava/lang/String;)V ***/
#define java_applet_Applet_showStatus(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_showStatus, a))

/*** public getImage (Ljava/net/URL;)Ljava/awt/Image; ***/
#define java_applet_Applet_getImage(env, obj, a) \
	((struct java_awt_Image *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_getImage, a))

/*** public getImage (Ljava/net/URL;Ljava/lang/String;)Ljava/awt/Image; ***/
#define java_applet_Applet_getImage_1(env, obj, a, b) \
	((struct java_awt_Image *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_getImage_1, a, b))

/*** public getAudioClip (Ljava/net/URL;)Ljava/applet/AudioClip; ***/
#define java_applet_Applet_getAudioClip(env, obj, a) \
	((struct java_applet_AudioClip *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_getAudioClip, a))

/*** public getAudioClip (Ljava/net/URL;Ljava/lang/String;)Ljava/applet/AudioClip; ***/
#define java_applet_Applet_getAudioClip_1(env, obj, a, b) \
	((struct java_applet_AudioClip *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_getAudioClip_1, a, b))

/*** public getAppletInfo ()Ljava/lang/String; ***/
#define java_applet_Applet_getAppletInfo(env, obj) \
	((struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_getAppletInfo))

/*** public getParameterInfo ()[[Ljava/lang/String; ***/
#define java_applet_Applet_getParameterInfo(env, obj) \
	((jref)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_getParameterInfo))

/*** public play (Ljava/net/URL;)V ***/
#define java_applet_Applet_play(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_play, a))

/*** public play (Ljava/net/URL;Ljava/lang/String;)V ***/
#define java_applet_Applet_play_1(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_play_1, a, b))

/*** public init ()V ***/
#define java_applet_Applet_init(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_init))

/*** public start ()V ***/
#define java_applet_Applet_start(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_start))

/*** public stop ()V ***/
#define java_applet_Applet_stop(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_stop))

/*** public destroy ()V ***/
#define java_applet_Applet_destroy(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_java_applet_Applet_destroy))

/*** public <init> ()V ***/
#define java_applet_Applet_new(env, clazz)	\
	((struct java_applet_Applet*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_applet_Applet_new))

#endif /* !DEBUG*/

/*** public final setStub (Ljava/applet/AppletStub;)V ***/
extern JRIMethodID FAR methodID_java_applet_Applet_setStub;
#define name_java_applet_Applet_setStub	"setStub"
#define sig_java_applet_Applet_setStub 	"(Ljava/applet/AppletStub;)V"
#define use_java_applet_Applet_setStub(env, clazz)	\
	(methodID_java_applet_Applet_setStub =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_setStub,	\
			sig_java_applet_Applet_setStub))
#define unuse_java_applet_Applet_setStub(env, clazz)	\
	(methodID_java_applet_Applet_setStub = JRIUninitialized)

/*** public isActive ()Z ***/
extern JRIMethodID FAR methodID_java_applet_Applet_isActive;
#define name_java_applet_Applet_isActive	"isActive"
#define sig_java_applet_Applet_isActive 	"()Z"
#define use_java_applet_Applet_isActive(env, clazz)	\
	(methodID_java_applet_Applet_isActive =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_isActive,	\
			sig_java_applet_Applet_isActive))
#define unuse_java_applet_Applet_isActive(env, clazz)	\
	(methodID_java_applet_Applet_isActive = JRIUninitialized)

/*** public getDocumentBase ()Ljava/net/URL; ***/
extern JRIMethodID FAR methodID_java_applet_Applet_getDocumentBase;
#define name_java_applet_Applet_getDocumentBase	"getDocumentBase"
#define sig_java_applet_Applet_getDocumentBase 	"()Ljava/net/URL;"
#define use_java_applet_Applet_getDocumentBase(env, clazz)	\
	(methodID_java_applet_Applet_getDocumentBase =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_getDocumentBase,	\
			sig_java_applet_Applet_getDocumentBase))
#define unuse_java_applet_Applet_getDocumentBase(env, clazz)	\
	(methodID_java_applet_Applet_getDocumentBase = JRIUninitialized)

/*** public getCodeBase ()Ljava/net/URL; ***/
extern JRIMethodID FAR methodID_java_applet_Applet_getCodeBase;
#define name_java_applet_Applet_getCodeBase	"getCodeBase"
#define sig_java_applet_Applet_getCodeBase 	"()Ljava/net/URL;"
#define use_java_applet_Applet_getCodeBase(env, clazz)	\
	(methodID_java_applet_Applet_getCodeBase =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_getCodeBase,	\
			sig_java_applet_Applet_getCodeBase))
#define unuse_java_applet_Applet_getCodeBase(env, clazz)	\
	(methodID_java_applet_Applet_getCodeBase = JRIUninitialized)

/*** public getParameter (Ljava/lang/String;)Ljava/lang/String; ***/
extern JRIMethodID FAR methodID_java_applet_Applet_getParameter;
#define name_java_applet_Applet_getParameter	"getParameter"
#define sig_java_applet_Applet_getParameter 	"(Ljava/lang/String;)Ljava/lang/String;"
#define use_java_applet_Applet_getParameter(env, clazz)	\
	(methodID_java_applet_Applet_getParameter =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_getParameter,	\
			sig_java_applet_Applet_getParameter))
#define unuse_java_applet_Applet_getParameter(env, clazz)	\
	(methodID_java_applet_Applet_getParameter = JRIUninitialized)

/*** public getAppletContext ()Ljava/applet/AppletContext; ***/
extern JRIMethodID FAR methodID_java_applet_Applet_getAppletContext;
#define name_java_applet_Applet_getAppletContext	"getAppletContext"
#define sig_java_applet_Applet_getAppletContext 	"()Ljava/applet/AppletContext;"
#define use_java_applet_Applet_getAppletContext(env, clazz)	\
	(methodID_java_applet_Applet_getAppletContext =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_getAppletContext,	\
			sig_java_applet_Applet_getAppletContext))
#define unuse_java_applet_Applet_getAppletContext(env, clazz)	\
	(methodID_java_applet_Applet_getAppletContext = JRIUninitialized)

/*** public resize (II)V ***/
extern JRIMethodID FAR methodID_java_applet_Applet_resize;
#define name_java_applet_Applet_resize	"resize"
#define sig_java_applet_Applet_resize 	"(II)V"
#define use_java_applet_Applet_resize(env, clazz)	\
	(methodID_java_applet_Applet_resize =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_resize,	\
			sig_java_applet_Applet_resize))
#define unuse_java_applet_Applet_resize(env, clazz)	\
	(methodID_java_applet_Applet_resize = JRIUninitialized)

/*** public resize (Ljava/awt/Dimension;)V ***/
extern JRIMethodID FAR methodID_java_applet_Applet_resize_1;
#define name_java_applet_Applet_resize_1	"resize"
#define sig_java_applet_Applet_resize_1 	"(Ljava/awt/Dimension;)V"
#define use_java_applet_Applet_resize_1(env, clazz)	\
	(methodID_java_applet_Applet_resize_1 =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_resize_1,	\
			sig_java_applet_Applet_resize_1))
#define unuse_java_applet_Applet_resize_1(env, clazz)	\
	(methodID_java_applet_Applet_resize_1 = JRIUninitialized)

/*** public showStatus (Ljava/lang/String;)V ***/
extern JRIMethodID FAR methodID_java_applet_Applet_showStatus;
#define name_java_applet_Applet_showStatus	"showStatus"
#define sig_java_applet_Applet_showStatus 	"(Ljava/lang/String;)V"
#define use_java_applet_Applet_showStatus(env, clazz)	\
	(methodID_java_applet_Applet_showStatus =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_showStatus,	\
			sig_java_applet_Applet_showStatus))
#define unuse_java_applet_Applet_showStatus(env, clazz)	\
	(methodID_java_applet_Applet_showStatus = JRIUninitialized)

/*** public getImage (Ljava/net/URL;)Ljava/awt/Image; ***/
extern JRIMethodID FAR methodID_java_applet_Applet_getImage;
#define name_java_applet_Applet_getImage	"getImage"
#define sig_java_applet_Applet_getImage 	"(Ljava/net/URL;)Ljava/awt/Image;"
#define use_java_applet_Applet_getImage(env, clazz)	\
	(methodID_java_applet_Applet_getImage =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_getImage,	\
			sig_java_applet_Applet_getImage))
#define unuse_java_applet_Applet_getImage(env, clazz)	\
	(methodID_java_applet_Applet_getImage = JRIUninitialized)

/*** public getImage (Ljava/net/URL;Ljava/lang/String;)Ljava/awt/Image; ***/
extern JRIMethodID FAR methodID_java_applet_Applet_getImage_1;
#define name_java_applet_Applet_getImage_1	"getImage"
#define sig_java_applet_Applet_getImage_1 	"(Ljava/net/URL;Ljava/lang/String;)Ljava/awt/Image;"
#define use_java_applet_Applet_getImage_1(env, clazz)	\
	(methodID_java_applet_Applet_getImage_1 =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_getImage_1,	\
			sig_java_applet_Applet_getImage_1))
#define unuse_java_applet_Applet_getImage_1(env, clazz)	\
	(methodID_java_applet_Applet_getImage_1 = JRIUninitialized)

/*** public getAudioClip (Ljava/net/URL;)Ljava/applet/AudioClip; ***/
extern JRIMethodID FAR methodID_java_applet_Applet_getAudioClip;
#define name_java_applet_Applet_getAudioClip	"getAudioClip"
#define sig_java_applet_Applet_getAudioClip 	"(Ljava/net/URL;)Ljava/applet/AudioClip;"
#define use_java_applet_Applet_getAudioClip(env, clazz)	\
	(methodID_java_applet_Applet_getAudioClip =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_getAudioClip,	\
			sig_java_applet_Applet_getAudioClip))
#define unuse_java_applet_Applet_getAudioClip(env, clazz)	\
	(methodID_java_applet_Applet_getAudioClip = JRIUninitialized)

/*** public getAudioClip (Ljava/net/URL;Ljava/lang/String;)Ljava/applet/AudioClip; ***/
extern JRIMethodID FAR methodID_java_applet_Applet_getAudioClip_1;
#define name_java_applet_Applet_getAudioClip_1	"getAudioClip"
#define sig_java_applet_Applet_getAudioClip_1 	"(Ljava/net/URL;Ljava/lang/String;)Ljava/applet/AudioClip;"
#define use_java_applet_Applet_getAudioClip_1(env, clazz)	\
	(methodID_java_applet_Applet_getAudioClip_1 =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_getAudioClip_1,	\
			sig_java_applet_Applet_getAudioClip_1))
#define unuse_java_applet_Applet_getAudioClip_1(env, clazz)	\
	(methodID_java_applet_Applet_getAudioClip_1 = JRIUninitialized)

/*** public getAppletInfo ()Ljava/lang/String; ***/
extern JRIMethodID FAR methodID_java_applet_Applet_getAppletInfo;
#define name_java_applet_Applet_getAppletInfo	"getAppletInfo"
#define sig_java_applet_Applet_getAppletInfo 	"()Ljava/lang/String;"
#define use_java_applet_Applet_getAppletInfo(env, clazz)	\
	(methodID_java_applet_Applet_getAppletInfo =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_getAppletInfo,	\
			sig_java_applet_Applet_getAppletInfo))
#define unuse_java_applet_Applet_getAppletInfo(env, clazz)	\
	(methodID_java_applet_Applet_getAppletInfo = JRIUninitialized)

/*** public getParameterInfo ()[[Ljava/lang/String; ***/
extern JRIMethodID FAR methodID_java_applet_Applet_getParameterInfo;
#define name_java_applet_Applet_getParameterInfo	"getParameterInfo"
#define sig_java_applet_Applet_getParameterInfo 	"()[[Ljava/lang/String;"
#define use_java_applet_Applet_getParameterInfo(env, clazz)	\
	(methodID_java_applet_Applet_getParameterInfo =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_getParameterInfo,	\
			sig_java_applet_Applet_getParameterInfo))
#define unuse_java_applet_Applet_getParameterInfo(env, clazz)	\
	(methodID_java_applet_Applet_getParameterInfo = JRIUninitialized)

/*** public play (Ljava/net/URL;)V ***/
extern JRIMethodID FAR methodID_java_applet_Applet_play;
#define name_java_applet_Applet_play	"play"
#define sig_java_applet_Applet_play 	"(Ljava/net/URL;)V"
#define use_java_applet_Applet_play(env, clazz)	\
	(methodID_java_applet_Applet_play =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_play,	\
			sig_java_applet_Applet_play))
#define unuse_java_applet_Applet_play(env, clazz)	\
	(methodID_java_applet_Applet_play = JRIUninitialized)

/*** public play (Ljava/net/URL;Ljava/lang/String;)V ***/
extern JRIMethodID FAR methodID_java_applet_Applet_play_1;
#define name_java_applet_Applet_play_1	"play"
#define sig_java_applet_Applet_play_1 	"(Ljava/net/URL;Ljava/lang/String;)V"
#define use_java_applet_Applet_play_1(env, clazz)	\
	(methodID_java_applet_Applet_play_1 =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_play_1,	\
			sig_java_applet_Applet_play_1))
#define unuse_java_applet_Applet_play_1(env, clazz)	\
	(methodID_java_applet_Applet_play_1 = JRIUninitialized)

/*** public init ()V ***/
extern JRIMethodID FAR methodID_java_applet_Applet_init;
#define name_java_applet_Applet_init	"init"
#define sig_java_applet_Applet_init 	"()V"
#define use_java_applet_Applet_init(env, clazz)	\
	(methodID_java_applet_Applet_init =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_init,	\
			sig_java_applet_Applet_init))
#define unuse_java_applet_Applet_init(env, clazz)	\
	(methodID_java_applet_Applet_init = JRIUninitialized)

/*** public start ()V ***/
extern JRIMethodID FAR methodID_java_applet_Applet_start;
#define name_java_applet_Applet_start	"start"
#define sig_java_applet_Applet_start 	"()V"
#define use_java_applet_Applet_start(env, clazz)	\
	(methodID_java_applet_Applet_start =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_start,	\
			sig_java_applet_Applet_start))
#define unuse_java_applet_Applet_start(env, clazz)	\
	(methodID_java_applet_Applet_start = JRIUninitialized)

/*** public stop ()V ***/
extern JRIMethodID FAR methodID_java_applet_Applet_stop;
#define name_java_applet_Applet_stop	"stop"
#define sig_java_applet_Applet_stop 	"()V"
#define use_java_applet_Applet_stop(env, clazz)	\
	(methodID_java_applet_Applet_stop =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_stop,	\
			sig_java_applet_Applet_stop))
#define unuse_java_applet_Applet_stop(env, clazz)	\
	(methodID_java_applet_Applet_stop = JRIUninitialized)

/*** public destroy ()V ***/
extern JRIMethodID FAR methodID_java_applet_Applet_destroy;
#define name_java_applet_Applet_destroy	"destroy"
#define sig_java_applet_Applet_destroy 	"()V"
#define use_java_applet_Applet_destroy(env, clazz)	\
	(methodID_java_applet_Applet_destroy =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_destroy,	\
			sig_java_applet_Applet_destroy))
#define unuse_java_applet_Applet_destroy(env, clazz)	\
	(methodID_java_applet_Applet_destroy = JRIUninitialized)

/*** public <init> ()V ***/
extern JRIMethodID FAR methodID_java_applet_Applet_new;
#define name_java_applet_Applet_new	"<init>"
#define sig_java_applet_Applet_new 	"()V"
#define use_java_applet_Applet_new(env, clazz)	\
	(methodID_java_applet_Applet_new =	\
		JRI_GetMethodID(env, clazz,	\
			name_java_applet_Applet_new,	\
			sig_java_applet_Applet_new))
#define unuse_java_applet_Applet_new(env, clazz)	\
	(methodID_java_applet_Applet_new = JRIUninitialized)

/*******************************************************************************
 * IMPLEMENTATION SECTION: 
 * Define the IMPLEMENT_java_applet_Applet symbol 
 * if you intend to implement the native methods of this class. This 
 * symbol makes the private and protected methods available. You should 
 * also call the register_java_applet_Applet routine 
 * to make your native methods available.
 ******************************************************************************/

extern JRI_PUBLIC_API(struct java_lang_Class*)
use_java_applet_Applet(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unuse_java_applet_Applet(JRIEnv* env);

extern JRI_PUBLIC_API(struct java_lang_Class*)
register_java_applet_Applet(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unregister_java_applet_Applet(JRIEnv* env);

#ifdef IMPLEMENT_java_applet_Applet

/*******************************************************************************
 * Implementation Field Accessors: 
 * You should only use these from within the native method definitions.
 ******************************************************************************/

#ifdef DEBUG

/*** private stub Ljava/applet/AppletStub; ***/
extern JRI_PUBLIC_API(struct java_applet_AppletStub *)
get_java_applet_Applet_stub(JRIEnv* env, java_applet_Applet* obj);
extern JRI_PUBLIC_API(void)
set_java_applet_Applet_stub(JRIEnv* env, java_applet_Applet* obj, struct java_applet_AppletStub * v);

#else /* !DEBUG */

/*** private stub Ljava/applet/AppletStub; ***/
#define get_java_applet_Applet_stub(env, obj) \
	((struct java_applet_AppletStub *)JRI_GetField(env, obj, fieldID_java_applet_Applet_stub))
#define set_java_applet_Applet_stub(env, obj, v) \
	JRI_SetField(env, obj, fieldID_java_applet_Applet_stub, v)

#endif /* !DEBUG*/

extern JRIFieldID FAR fieldID_java_applet_Applet_stub;
#define name_java_applet_Applet_stub	"stub"
#define sig_java_applet_Applet_stub 	"Ljava/applet/AppletStub;"
#define use_java_applet_Applet_stub(env, clazz)	\
	(fieldID_java_applet_Applet_stub =	\
		JRI_GetFieldID(env, clazz,	\
			name_java_applet_Applet_stub,	\
			sig_java_applet_Applet_stub))
#define unuse_java_applet_Applet_stub(env, clazz)	\
		(fieldID_java_applet_Applet_stub = JRIUninitialized)

#endif /* IMPLEMENT_java_applet_Applet */

#ifdef __cplusplus
} /* extern "C" */

/*******************************************************************************
 * C++ Definitions
 ******************************************************************************/

#include "java_awt_Panel.h"

struct java_applet_Applet : virtual public java_awt_Panel {

	static struct java_lang_Class* _use(JRIEnv* env) {
		return use_java_applet_Applet(env);
	}

	static void _unuse(JRIEnv* env) {
		unuse_java_applet_Applet(env);
	}

	static struct java_lang_Class* _register(JRIEnv* env) {
		return register_java_applet_Applet(env);
	}

	static void _unregister(JRIEnv* env) {
		unregister_java_applet_Applet(env);
	}

	static struct java_lang_Class* _class(JRIEnv* env) {
		return class_java_applet_Applet(env);
	}

	/* Public Methods */
	/*** public final setStub (Ljava/applet/AppletStub;)V ***/
	void setStub(JRIEnv* env, struct java_applet_AppletStub *a) {
		java_applet_Applet_setStub(env, this, a);
	}

	/*** public isActive ()Z ***/
	jbool isActive(JRIEnv* env) {
		return java_applet_Applet_isActive(env, this);
	}

	/*** public getDocumentBase ()Ljava/net/URL; ***/
	struct java_net_URL * getDocumentBase(JRIEnv* env) {
		return java_applet_Applet_getDocumentBase(env, this);
	}

	/*** public getCodeBase ()Ljava/net/URL; ***/
	struct java_net_URL * getCodeBase(JRIEnv* env) {
		return java_applet_Applet_getCodeBase(env, this);
	}

	/*** public getParameter (Ljava/lang/String;)Ljava/lang/String; ***/
	struct java_lang_String * getParameter(JRIEnv* env, struct java_lang_String *a) {
		return java_applet_Applet_getParameter(env, this, a);
	}

	/*** public getAppletContext ()Ljava/applet/AppletContext; ***/
	struct java_applet_AppletContext * getAppletContext(JRIEnv* env) {
		return java_applet_Applet_getAppletContext(env, this);
	}

	/*** public resize (II)V ***/
	void resize(JRIEnv* env, jint a, jint b) {
		java_applet_Applet_resize(env, this, a, b);
	}

	/*** public resize (Ljava/awt/Dimension;)V ***/
	void resize(JRIEnv* env, struct java_awt_Dimension *a) {
		java_applet_Applet_resize_1(env, this, a);
	}

	/*** public showStatus (Ljava/lang/String;)V ***/
	void showStatus(JRIEnv* env, struct java_lang_String *a) {
		java_applet_Applet_showStatus(env, this, a);
	}

	/*** public getImage (Ljava/net/URL;)Ljava/awt/Image; ***/
	struct java_awt_Image * getImage(JRIEnv* env, struct java_net_URL *a) {
		return java_applet_Applet_getImage(env, this, a);
	}

	/*** public getImage (Ljava/net/URL;Ljava/lang/String;)Ljava/awt/Image; ***/
	struct java_awt_Image * getImage(JRIEnv* env, struct java_net_URL *a, struct java_lang_String *b) {
		return java_applet_Applet_getImage_1(env, this, a, b);
	}

	/*** public getAudioClip (Ljava/net/URL;)Ljava/applet/AudioClip; ***/
	struct java_applet_AudioClip * getAudioClip(JRIEnv* env, struct java_net_URL *a) {
		return java_applet_Applet_getAudioClip(env, this, a);
	}

	/*** public getAudioClip (Ljava/net/URL;Ljava/lang/String;)Ljava/applet/AudioClip; ***/
	struct java_applet_AudioClip * getAudioClip(JRIEnv* env, struct java_net_URL *a, struct java_lang_String *b) {
		return java_applet_Applet_getAudioClip_1(env, this, a, b);
	}

	/*** public getAppletInfo ()Ljava/lang/String; ***/
	struct java_lang_String * getAppletInfo(JRIEnv* env) {
		return java_applet_Applet_getAppletInfo(env, this);
	}

	/*** public getParameterInfo ()[[Ljava/lang/String; ***/
	jref getParameterInfo(JRIEnv* env) {
		return java_applet_Applet_getParameterInfo(env, this);
	}

	/*** public play (Ljava/net/URL;)V ***/
	void play(JRIEnv* env, struct java_net_URL *a) {
		java_applet_Applet_play(env, this, a);
	}

	/*** public play (Ljava/net/URL;Ljava/lang/String;)V ***/
	void play(JRIEnv* env, struct java_net_URL *a, struct java_lang_String *b) {
		java_applet_Applet_play_1(env, this, a, b);
	}

	/*** public init ()V ***/
	void init(JRIEnv* env) {
		java_applet_Applet_init(env, this);
	}

	/*** public start ()V ***/
	void start(JRIEnv* env) {
		java_applet_Applet_start(env, this);
	}

	/*** public stop ()V ***/
	void stop(JRIEnv* env) {
		java_applet_Applet_stop(env, this);
	}

	/*** public destroy ()V ***/
	void destroy(JRIEnv* env) {
		java_applet_Applet_destroy(env, this);
	}

	/*** public <init> ()V ***/
	static java_applet_Applet* _new(JRIEnv* env, struct java_lang_Class* clazz) {
		return java_applet_Applet_new(env, clazz);
	}

#ifdef IMPLEMENT_java_applet_Applet

	/* Private Field Accessors */
	/*** private stub Ljava/applet/AppletStub; ***/
	struct java_applet_AppletStub * stub(JRIEnv* env) {
		return get_java_applet_Applet_stub(env, this);
	}
	void stub(JRIEnv* env, struct java_applet_AppletStub * v) {
		set_java_applet_Applet_stub(env, this, v);
	}

#endif /* IMPLEMENT_java_applet_Applet */
};

#endif /* __cplusplus */

#endif /* Class java/applet/Applet */
