/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Header for class netscape/applet/AppletClassLoader */

#ifndef _netscape_applet_AppletClassLoader_H_
#define _netscape_applet_AppletClassLoader_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct java_util_Hashtable;
struct java_net_URL;
struct netscape_applet_MozillaAppletContext;
struct netscape_applet_AppletClassLoader;
struct java_io_InputStream;
struct java_lang_String;
struct java_lang_Class;
struct java_lang_Class;

/*******************************************************************************
 * Class netscape/applet/AppletClassLoader
 ******************************************************************************/

typedef struct netscape_applet_AppletClassLoader netscape_applet_AppletClassLoader;

#define classname_netscape_applet_AppletClassLoader	"netscape/applet/AppletClassLoader"

#define class_netscape_applet_AppletClassLoader(env) \
	((struct java_lang_Class*)JRI_FindClass(env, classname_netscape_applet_AppletClassLoader))

/*******************************************************************************
 * Public Methods
 ******************************************************************************/

#ifdef DEBUG

/*** public loadClass (Ljava/lang/String;)Ljava/lang/Class; ***/
extern JRI_PUBLIC_API(struct java_lang_Class *)
netscape_applet_AppletClassLoader_loadClass_1(JRIEnv* env, struct netscape_applet_AppletClassLoader* self, struct java_lang_String *a);

#else /* !DEBUG */

/*** public loadClass (Ljava/lang/String;)Ljava/lang/Class; ***/
#define netscape_applet_AppletClassLoader_loadClass_1(env, obj, a) \
	((struct java_lang_Class *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_loadClass_1, a))

#endif /* !DEBUG*/

/*** public loadClass (Ljava/lang/String;)Ljava/lang/Class; ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_loadClass_1;
#define name_netscape_applet_AppletClassLoader_loadClass_1	"loadClass"
#define sig_netscape_applet_AppletClassLoader_loadClass_1 	"(Ljava/lang/String;)Ljava/lang/Class;"
#define use_netscape_applet_AppletClassLoader_loadClass_1(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_loadClass_1 =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_loadClass_1,	\
			sig_netscape_applet_AppletClassLoader_loadClass_1))
#define unuse_netscape_applet_AppletClassLoader_loadClass_1(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_loadClass_1 = JRIUninitialized)

/*******************************************************************************
 * IMPLEMENTATION SECTION: 
 * Define the IMPLEMENT_netscape_applet_AppletClassLoader symbol 
 * if you intend to implement the native methods of this class. This 
 * symbol makes the private and protected methods available. You should 
 * also call the register_netscape_applet_AppletClassLoader routine 
 * to make your native methods available.
 ******************************************************************************/

extern JRI_PUBLIC_API(struct java_lang_Class*)
use_netscape_applet_AppletClassLoader(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unuse_netscape_applet_AppletClassLoader(JRIEnv* env);

extern JRI_PUBLIC_API(struct java_lang_Class*)
register_netscape_applet_AppletClassLoader(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unregister_netscape_applet_AppletClassLoader(JRIEnv* env);

#ifdef IMPLEMENT_netscape_applet_AppletClassLoader

/*******************************************************************************
 * Native Methods: 
 * These are the signatures of the native methods which you must implement.
 ******************************************************************************/

/*** native openZipFile (Ljava/io/InputStream;)I ***/
extern JRI_PUBLIC_API(jint)
native_netscape_applet_AppletClassLoader_openZipFile(JRIEnv* env, struct netscape_applet_AppletClassLoader* self, struct java_io_InputStream *a);

/*** native loadFromZipFile (ILjava/lang/String;)[B ***/
extern JRI_PUBLIC_API(jref)
native_netscape_applet_AppletClassLoader_loadFromZipFile(JRIEnv* env, struct netscape_applet_AppletClassLoader* self, jint a, struct java_lang_String *b);

/*** native closeZipFile (I)V ***/
extern JRI_PUBLIC_API(void)
native_netscape_applet_AppletClassLoader_closeZipFile(JRIEnv* env, struct netscape_applet_AppletClassLoader* self, jint a);

/*******************************************************************************
 * Implementation Field Accessors: 
 * You should only use these from within the native method definitions.
 ******************************************************************************/

#ifdef DEBUG

/*** classes Ljava/util/Hashtable; ***/
extern JRI_PUBLIC_API(struct java_util_Hashtable *)
get_netscape_applet_AppletClassLoader_classes(JRIEnv* env, netscape_applet_AppletClassLoader* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_AppletClassLoader_classes(JRIEnv* env, netscape_applet_AppletClassLoader* obj, struct java_util_Hashtable * v);

/*** codeBaseURL Ljava/net/URL; ***/
extern JRI_PUBLIC_API(struct java_net_URL *)
get_netscape_applet_AppletClassLoader_codeBaseURL(JRIEnv* env, netscape_applet_AppletClassLoader* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_AppletClassLoader_codeBaseURL(JRIEnv* env, netscape_applet_AppletClassLoader* obj, struct java_net_URL * v);

/*** archiveURL Ljava/net/URL; ***/
extern JRI_PUBLIC_API(struct java_net_URL *)
get_netscape_applet_AppletClassLoader_archiveURL(JRIEnv* env, netscape_applet_AppletClassLoader* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_AppletClassLoader_archiveURL(JRIEnv* env, netscape_applet_AppletClassLoader* obj, struct java_net_URL * v);

/*** context Lnetscape/applet/MozillaAppletContext; ***/
extern JRI_PUBLIC_API(struct netscape_applet_MozillaAppletContext *)
get_netscape_applet_AppletClassLoader_context(JRIEnv* env, netscape_applet_AppletClassLoader* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_AppletClassLoader_context(JRIEnv* env, netscape_applet_AppletClassLoader* obj, struct netscape_applet_MozillaAppletContext * v);

/*** nativeZipFile I ***/
extern JRI_PUBLIC_API(jint)
get_netscape_applet_AppletClassLoader_nativeZipFile(JRIEnv* env, netscape_applet_AppletClassLoader* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_AppletClassLoader_nativeZipFile(JRIEnv* env, netscape_applet_AppletClassLoader* obj, jint v);

/*** static wantTiming Z ***/
extern JRI_PUBLIC_API(jbool)
get_netscape_applet_AppletClassLoader_wantTiming(JRIEnv* env, struct java_lang_Class* clazz);
extern JRI_PUBLIC_API(void)
set_netscape_applet_AppletClassLoader_wantTiming(JRIEnv* env, struct java_lang_Class* clazz, jbool v);

/*** loaderTime J ***/
extern JRI_PUBLIC_API(jlong)
get_netscape_applet_AppletClassLoader_loaderTime(JRIEnv* env, netscape_applet_AppletClassLoader* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_AppletClassLoader_loaderTime(JRIEnv* env, netscape_applet_AppletClassLoader* obj, jlong v);

/*** mayScript Z ***/
extern JRI_PUBLIC_API(jbool)
get_netscape_applet_AppletClassLoader_mayScript(JRIEnv* env, netscape_applet_AppletClassLoader* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_AppletClassLoader_mayScript(JRIEnv* env, netscape_applet_AppletClassLoader* obj, jbool v);

/*** static classloaders Ljava/util/Vector; ***/
extern JRI_PUBLIC_API(struct java_util_Vector *)
get_netscape_applet_AppletClassLoader_classloaders(JRIEnv* env, struct java_lang_Class* clazz);
extern JRI_PUBLIC_API(void)
set_netscape_applet_AppletClassLoader_classloaders(JRIEnv* env, struct java_lang_Class* clazz, struct java_util_Vector * v);

/*** refCount I ***/
extern JRI_PUBLIC_API(jint)
get_netscape_applet_AppletClassLoader_refCount(JRIEnv* env, netscape_applet_AppletClassLoader* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_AppletClassLoader_refCount(JRIEnv* env, netscape_applet_AppletClassLoader* obj, jint v);

#else /* !DEBUG */

/*** classes Ljava/util/Hashtable; ***/
#define get_netscape_applet_AppletClassLoader_classes(env, obj) \
	((struct java_util_Hashtable *)JRI_GetField(env, obj, fieldID_netscape_applet_AppletClassLoader_classes))
#define set_netscape_applet_AppletClassLoader_classes(env, obj, v) \
	JRI_SetField(env, obj, fieldID_netscape_applet_AppletClassLoader_classes, v)

/*** codeBaseURL Ljava/net/URL; ***/
#define get_netscape_applet_AppletClassLoader_codeBaseURL(env, obj) \
	((struct java_net_URL *)JRI_GetField(env, obj, fieldID_netscape_applet_AppletClassLoader_codeBaseURL))
#define set_netscape_applet_AppletClassLoader_codeBaseURL(env, obj, v) \
	JRI_SetField(env, obj, fieldID_netscape_applet_AppletClassLoader_codeBaseURL, v)

/*** archiveURL Ljava/net/URL; ***/
#define get_netscape_applet_AppletClassLoader_archiveURL(env, obj) \
	((struct java_net_URL *)JRI_GetField(env, obj, fieldID_netscape_applet_AppletClassLoader_archiveURL))
#define set_netscape_applet_AppletClassLoader_archiveURL(env, obj, v) \
	JRI_SetField(env, obj, fieldID_netscape_applet_AppletClassLoader_archiveURL, v)

/*** context Lnetscape/applet/MozillaAppletContext; ***/
#define get_netscape_applet_AppletClassLoader_context(env, obj) \
	((struct netscape_applet_MozillaAppletContext *)JRI_GetField(env, obj, fieldID_netscape_applet_AppletClassLoader_context))
#define set_netscape_applet_AppletClassLoader_context(env, obj, v) \
	JRI_SetField(env, obj, fieldID_netscape_applet_AppletClassLoader_context, v)

/*** nativeZipFile I ***/
#define get_netscape_applet_AppletClassLoader_nativeZipFile(env, obj) \
	(JRI_GetFieldInt(env, obj, fieldID_netscape_applet_AppletClassLoader_nativeZipFile))
#define set_netscape_applet_AppletClassLoader_nativeZipFile(env, obj, v) \
	JRI_SetFieldInt(env, obj, fieldID_netscape_applet_AppletClassLoader_nativeZipFile, v)

/*** static wantTiming Z ***/
#define get_netscape_applet_AppletClassLoader_wantTiming(env, clazz) \
	(JRI_GetStaticFieldBoolean(env, clazz, fieldID_netscape_applet_AppletClassLoader_wantTiming))
#define set_netscape_applet_AppletClassLoader_wantTiming(env, clazz, v) \
	JRI_SetStaticFieldBoolean(env, clazz, fieldID_netscape_applet_AppletClassLoader_wantTiming, v)

/*** loaderTime J ***/
#define get_netscape_applet_AppletClassLoader_loaderTime(env, obj) \
	(JRI_GetFieldLong(env, obj, fieldID_netscape_applet_AppletClassLoader_loaderTime))
#define set_netscape_applet_AppletClassLoader_loaderTime(env, obj, v) \
	JRI_SetFieldLong(env, obj, fieldID_netscape_applet_AppletClassLoader_loaderTime, v)

/*** mayScript Z ***/
#define get_netscape_applet_AppletClassLoader_mayScript(env, obj) \
	(JRI_GetFieldBoolean(env, obj, fieldID_netscape_applet_AppletClassLoader_mayScript))
#define set_netscape_applet_AppletClassLoader_mayScript(env, obj, v) \
	JRI_SetFieldBoolean(env, obj, fieldID_netscape_applet_AppletClassLoader_mayScript, v)

/*** static classloaders Ljava/util/Vector; ***/
#define get_netscape_applet_AppletClassLoader_classloaders(env, clazz) \
	((struct java_util_Vector *)JRI_GetStaticField(env, clazz, fieldID_netscape_applet_AppletClassLoader_classloaders))
#define set_netscape_applet_AppletClassLoader_classloaders(env, clazz, v) \
	JRI_SetStaticField(env, clazz, fieldID_netscape_applet_AppletClassLoader_classloaders, v)

/*** refCount I ***/
#define get_netscape_applet_AppletClassLoader_refCount(env, obj) \
	(JRI_GetFieldInt(env, obj, fieldID_netscape_applet_AppletClassLoader_refCount))
#define set_netscape_applet_AppletClassLoader_refCount(env, obj, v) \
	JRI_SetFieldInt(env, obj, fieldID_netscape_applet_AppletClassLoader_refCount, v)

#endif /* !DEBUG*/

extern JRIFieldID FAR fieldID_netscape_applet_AppletClassLoader_classes;
#define name_netscape_applet_AppletClassLoader_classes	"classes"
#define sig_netscape_applet_AppletClassLoader_classes 	"Ljava/util/Hashtable;"
#define use_netscape_applet_AppletClassLoader_classes(env, clazz)	\
	(fieldID_netscape_applet_AppletClassLoader_classes =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_classes,	\
			sig_netscape_applet_AppletClassLoader_classes))
#define unuse_netscape_applet_AppletClassLoader_classes(env, clazz)	\
		(fieldID_netscape_applet_AppletClassLoader_classes = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_AppletClassLoader_codeBaseURL;
#define name_netscape_applet_AppletClassLoader_codeBaseURL	"codeBaseURL"
#define sig_netscape_applet_AppletClassLoader_codeBaseURL 	"Ljava/net/URL;"
#define use_netscape_applet_AppletClassLoader_codeBaseURL(env, clazz)	\
	(fieldID_netscape_applet_AppletClassLoader_codeBaseURL =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_codeBaseURL,	\
			sig_netscape_applet_AppletClassLoader_codeBaseURL))
#define unuse_netscape_applet_AppletClassLoader_codeBaseURL(env, clazz)	\
		(fieldID_netscape_applet_AppletClassLoader_codeBaseURL = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_AppletClassLoader_archiveURL;
#define name_netscape_applet_AppletClassLoader_archiveURL	"archiveURL"
#define sig_netscape_applet_AppletClassLoader_archiveURL 	"Ljava/net/URL;"
#define use_netscape_applet_AppletClassLoader_archiveURL(env, clazz)	\
	(fieldID_netscape_applet_AppletClassLoader_archiveURL =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_archiveURL,	\
			sig_netscape_applet_AppletClassLoader_archiveURL))
#define unuse_netscape_applet_AppletClassLoader_archiveURL(env, clazz)	\
		(fieldID_netscape_applet_AppletClassLoader_archiveURL = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_AppletClassLoader_context;
#define name_netscape_applet_AppletClassLoader_context	"context"
#define sig_netscape_applet_AppletClassLoader_context 	"Lnetscape/applet/MozillaAppletContext;"
#define use_netscape_applet_AppletClassLoader_context(env, clazz)	\
	(fieldID_netscape_applet_AppletClassLoader_context =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_context,	\
			sig_netscape_applet_AppletClassLoader_context))
#define unuse_netscape_applet_AppletClassLoader_context(env, clazz)	\
		(fieldID_netscape_applet_AppletClassLoader_context = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_AppletClassLoader_nativeZipFile;
#define name_netscape_applet_AppletClassLoader_nativeZipFile	"nativeZipFile"
#define sig_netscape_applet_AppletClassLoader_nativeZipFile 	"I"
#define use_netscape_applet_AppletClassLoader_nativeZipFile(env, clazz)	\
	(fieldID_netscape_applet_AppletClassLoader_nativeZipFile =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_nativeZipFile,	\
			sig_netscape_applet_AppletClassLoader_nativeZipFile))
#define unuse_netscape_applet_AppletClassLoader_nativeZipFile(env, clazz)	\
		(fieldID_netscape_applet_AppletClassLoader_nativeZipFile = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_AppletClassLoader_wantTiming;
#define name_netscape_applet_AppletClassLoader_wantTiming	"wantTiming"
#define sig_netscape_applet_AppletClassLoader_wantTiming 	"Z"
#define use_netscape_applet_AppletClassLoader_wantTiming(env, clazz)	\
	(fieldID_netscape_applet_AppletClassLoader_wantTiming =	\
		JRI_GetStaticFieldID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_wantTiming,	\
			sig_netscape_applet_AppletClassLoader_wantTiming))
#define unuse_netscape_applet_AppletClassLoader_wantTiming(env, clazz)	\
		(fieldID_netscape_applet_AppletClassLoader_wantTiming = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_AppletClassLoader_loaderTime;
#define name_netscape_applet_AppletClassLoader_loaderTime	"loaderTime"
#define sig_netscape_applet_AppletClassLoader_loaderTime 	"J"
#define use_netscape_applet_AppletClassLoader_loaderTime(env, clazz)	\
	(fieldID_netscape_applet_AppletClassLoader_loaderTime =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_loaderTime,	\
			sig_netscape_applet_AppletClassLoader_loaderTime))
#define unuse_netscape_applet_AppletClassLoader_loaderTime(env, clazz)	\
		(fieldID_netscape_applet_AppletClassLoader_loaderTime = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_AppletClassLoader_mayScript;
#define name_netscape_applet_AppletClassLoader_mayScript	"mayScript"
#define sig_netscape_applet_AppletClassLoader_mayScript 	"Z"
#define use_netscape_applet_AppletClassLoader_mayScript(env, clazz)	\
	(fieldID_netscape_applet_AppletClassLoader_mayScript =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_mayScript,	\
			sig_netscape_applet_AppletClassLoader_mayScript))
#define unuse_netscape_applet_AppletClassLoader_mayScript(env, clazz)	\
		(fieldID_netscape_applet_AppletClassLoader_mayScript = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_AppletClassLoader_classloaders;
#define name_netscape_applet_AppletClassLoader_classloaders	"classloaders"
#define sig_netscape_applet_AppletClassLoader_classloaders 	"Ljava/util/Vector;"
#define use_netscape_applet_AppletClassLoader_classloaders(env, clazz)	\
	(fieldID_netscape_applet_AppletClassLoader_classloaders =	\
		JRI_GetStaticFieldID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_classloaders,	\
			sig_netscape_applet_AppletClassLoader_classloaders))
#define unuse_netscape_applet_AppletClassLoader_classloaders(env, clazz)	\
		(fieldID_netscape_applet_AppletClassLoader_classloaders = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_AppletClassLoader_refCount;
#define name_netscape_applet_AppletClassLoader_refCount	"refCount"
#define sig_netscape_applet_AppletClassLoader_refCount 	"I"
#define use_netscape_applet_AppletClassLoader_refCount(env, clazz)	\
	(fieldID_netscape_applet_AppletClassLoader_refCount =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_refCount,	\
			sig_netscape_applet_AppletClassLoader_refCount))
#define unuse_netscape_applet_AppletClassLoader_refCount(env, clazz)	\
		(fieldID_netscape_applet_AppletClassLoader_refCount = JRIUninitialized)

/*******************************************************************************
 * Implementation Methods: 
 * You should only use these from within the native method definitions.
 ******************************************************************************/

#ifdef DEBUG

/*** static getClassLoader (Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;Ljava/net/URL;Z)Lnetscape/applet/AppletClassLoader; ***/
extern JRI_PUBLIC_API(struct netscape_applet_AppletClassLoader *)
netscape_applet_AppletClassLoader_getClassLoader(JRIEnv* env, struct java_lang_Class* clazz, struct netscape_applet_MozillaAppletContext *a, struct java_net_URL *b, struct java_net_URL *c, jbool d);

/*** releaseClassLoader ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_AppletClassLoader_releaseClassLoader(JRIEnv* env, struct netscape_applet_AppletClassLoader* self);

/*** <init> (Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;Ljava/net/URL;)V ***/
extern JRI_PUBLIC_API(struct netscape_applet_AppletClassLoader*)
netscape_applet_AppletClassLoader_new(JRIEnv* env, struct java_lang_Class* clazz, struct netscape_applet_MozillaAppletContext *a, struct java_net_URL *b, struct java_net_URL *c);

/*** native openZipFile (Ljava/io/InputStream;)I ***/
extern JRI_PUBLIC_API(jint)
netscape_applet_AppletClassLoader_openZipFile(JRIEnv* env, struct netscape_applet_AppletClassLoader* self, struct java_io_InputStream *a);

/*** native loadFromZipFile (ILjava/lang/String;)[B ***/
extern JRI_PUBLIC_API(jref)
netscape_applet_AppletClassLoader_loadFromZipFile(JRIEnv* env, struct netscape_applet_AppletClassLoader* self, jint a, struct java_lang_String *b);

/*** native closeZipFile (I)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_AppletClassLoader_closeZipFile(JRIEnv* env, struct netscape_applet_AppletClassLoader* self, jint a);

/*** close ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_AppletClassLoader_close(JRIEnv* env, struct netscape_applet_AppletClassLoader* self);

/*** protected finalize ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_AppletClassLoader_finalize(JRIEnv* env, struct netscape_applet_AppletClassLoader* self);

/*** mayScript ()Z ***/
extern JRI_PUBLIC_API(jbool)
netscape_applet_AppletClassLoader_mayScript(JRIEnv* env, struct netscape_applet_AppletClassLoader* self);

/*** private loadClass (Ljava/lang/String;Ljava/net/URL;)Ljava/lang/Class; ***/
extern JRI_PUBLIC_API(struct java_lang_Class *)
netscape_applet_AppletClassLoader_loadClass(JRIEnv* env, struct netscape_applet_AppletClassLoader* self, struct java_lang_String *a, struct java_net_URL *b);

/*** protected loadClass (Ljava/lang/String;Z)Ljava/lang/Class; ***/
extern JRI_PUBLIC_API(struct java_lang_Class *)
netscape_applet_AppletClassLoader_loadClass_2(JRIEnv* env, struct netscape_applet_AppletClassLoader* self, struct java_lang_String *a, jbool b);

/*** loadClass1 (Ljava/lang/String;Z)Ljava/lang/Class; ***/
extern JRI_PUBLIC_API(struct java_lang_Class *)
netscape_applet_AppletClassLoader_loadClass1(JRIEnv* env, struct netscape_applet_AppletClassLoader* self, struct java_lang_String *a, jbool b);

/*** private findClass (Ljava/lang/String;)Ljava/lang/Class; ***/
extern JRI_PUBLIC_API(struct java_lang_Class *)
netscape_applet_AppletClassLoader_findClass(JRIEnv* env, struct netscape_applet_AppletClassLoader* self, struct java_lang_String *a);

/*** getResource (Ljava/net/URL;)[B ***/
extern JRI_PUBLIC_API(jref)
netscape_applet_AppletClassLoader_getResource(JRIEnv* env, struct netscape_applet_AppletClassLoader* self, struct java_net_URL *a);

/*** readURL (Ljava/net/URL;)[B ***/
extern JRI_PUBLIC_API(jref)
netscape_applet_AppletClassLoader_readURL(JRIEnv* env, struct netscape_applet_AppletClassLoader* self, struct java_net_URL *a);

/*** static <clinit> ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_AppletClassLoader__0003cclinit_0003e(JRIEnv* env, struct java_lang_Class* clazz);

#else /* !DEBUG */

/*** static getClassLoader (Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;Ljava/net/URL;Z)Lnetscape/applet/AppletClassLoader; ***/
#define netscape_applet_AppletClassLoader_getClassLoader(env, clazz, a, b, c, d) \
	((struct netscape_applet_AppletClassLoader *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_AppletClassLoader_getClassLoader, a, b, c, d))

/*** releaseClassLoader ()V ***/
#define netscape_applet_AppletClassLoader_releaseClassLoader(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_releaseClassLoader))

/*** <init> (Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;Ljava/net/URL;)V ***/
#define netscape_applet_AppletClassLoader_new(env, clazz, a, b, c)	\
	((struct netscape_applet_AppletClassLoader*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_netscape_applet_AppletClassLoader_new, a, b, c))

/*** native openZipFile (Ljava/io/InputStream;)I ***/
#define netscape_applet_AppletClassLoader_openZipFile(env, obj, a) \
	(JRI_CallMethodInt(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_openZipFile, a))

/*** native loadFromZipFile (ILjava/lang/String;)[B ***/
#define netscape_applet_AppletClassLoader_loadFromZipFile(env, obj, a, b) \
	((jref)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_loadFromZipFile, a, b))

/*** native closeZipFile (I)V ***/
#define netscape_applet_AppletClassLoader_closeZipFile(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_closeZipFile, a))

/*** close ()V ***/
#define netscape_applet_AppletClassLoader_close(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_close))

/*** protected finalize ()V ***/
#define netscape_applet_AppletClassLoader_finalize(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_finalize))

/*** mayScript ()Z ***/
#define netscape_applet_AppletClassLoader_mayScript(env, obj) \
	(JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_mayScript))

/*** private loadClass (Ljava/lang/String;Ljava/net/URL;)Ljava/lang/Class; ***/
#define netscape_applet_AppletClassLoader_loadClass(env, obj, a, b) \
	((struct java_lang_Class *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_loadClass, a, b))

/*** protected loadClass (Ljava/lang/String;Z)Ljava/lang/Class; ***/
#define netscape_applet_AppletClassLoader_loadClass_2(env, obj, a, b) \
	((struct java_lang_Class *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_loadClass_2, a, b))

/*** loadClass1 (Ljava/lang/String;Z)Ljava/lang/Class; ***/
#define netscape_applet_AppletClassLoader_loadClass1(env, obj, a, b) \
	((struct java_lang_Class *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_loadClass1, a, b))

/*** private findClass (Ljava/lang/String;)Ljava/lang/Class; ***/
#define netscape_applet_AppletClassLoader_findClass(env, obj, a) \
	((struct java_lang_Class *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_findClass, a))

/*** getResource (Ljava/net/URL;)[B ***/
#define netscape_applet_AppletClassLoader_getResource(env, obj, a) \
	((jref)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_getResource, a))

/*** readURL (Ljava/net/URL;)[B ***/
#define netscape_applet_AppletClassLoader_readURL(env, obj, a) \
	((jref)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_AppletClassLoader_readURL, a))

/*** static <clinit> ()V ***/
#define netscape_applet_AppletClassLoader__0003cclinit_0003e(env, clazz) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_AppletClassLoader__0003cclinit_0003e))

#endif /* !DEBUG*/

/*** static getClassLoader (Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;Ljava/net/URL;Z)Lnetscape/applet/AppletClassLoader; ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_getClassLoader;
#define name_netscape_applet_AppletClassLoader_getClassLoader	"getClassLoader"
#define sig_netscape_applet_AppletClassLoader_getClassLoader 	"(Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;Ljava/net/URL;Z)Lnetscape/applet/AppletClassLoader;"
#define use_netscape_applet_AppletClassLoader_getClassLoader(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_getClassLoader =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_getClassLoader,	\
			sig_netscape_applet_AppletClassLoader_getClassLoader))
#define unuse_netscape_applet_AppletClassLoader_getClassLoader(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_getClassLoader = JRIUninitialized)

/*** releaseClassLoader ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_releaseClassLoader;
#define name_netscape_applet_AppletClassLoader_releaseClassLoader	"releaseClassLoader"
#define sig_netscape_applet_AppletClassLoader_releaseClassLoader 	"()V"
#define use_netscape_applet_AppletClassLoader_releaseClassLoader(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_releaseClassLoader =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_releaseClassLoader,	\
			sig_netscape_applet_AppletClassLoader_releaseClassLoader))
#define unuse_netscape_applet_AppletClassLoader_releaseClassLoader(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_releaseClassLoader = JRIUninitialized)

/*** <init> (Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;Ljava/net/URL;)V ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_new;
#define name_netscape_applet_AppletClassLoader_new	"<init>"
#define sig_netscape_applet_AppletClassLoader_new 	"(Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;Ljava/net/URL;)V"
#define use_netscape_applet_AppletClassLoader_new(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_new =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_new,	\
			sig_netscape_applet_AppletClassLoader_new))
#define unuse_netscape_applet_AppletClassLoader_new(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_new = JRIUninitialized)

/*** native openZipFile (Ljava/io/InputStream;)I ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_openZipFile;
#define name_netscape_applet_AppletClassLoader_openZipFile	"openZipFile"
#define sig_netscape_applet_AppletClassLoader_openZipFile 	"(Ljava/io/InputStream;)I"
#define use_netscape_applet_AppletClassLoader_openZipFile(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_openZipFile =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_openZipFile,	\
			sig_netscape_applet_AppletClassLoader_openZipFile))
#define unuse_netscape_applet_AppletClassLoader_openZipFile(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_openZipFile = JRIUninitialized)

/*** native loadFromZipFile (ILjava/lang/String;)[B ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_loadFromZipFile;
#define name_netscape_applet_AppletClassLoader_loadFromZipFile	"loadFromZipFile"
#define sig_netscape_applet_AppletClassLoader_loadFromZipFile 	"(ILjava/lang/String;)[B"
#define use_netscape_applet_AppletClassLoader_loadFromZipFile(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_loadFromZipFile =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_loadFromZipFile,	\
			sig_netscape_applet_AppletClassLoader_loadFromZipFile))
#define unuse_netscape_applet_AppletClassLoader_loadFromZipFile(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_loadFromZipFile = JRIUninitialized)

/*** native closeZipFile (I)V ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_closeZipFile;
#define name_netscape_applet_AppletClassLoader_closeZipFile	"closeZipFile"
#define sig_netscape_applet_AppletClassLoader_closeZipFile 	"(I)V"
#define use_netscape_applet_AppletClassLoader_closeZipFile(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_closeZipFile =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_closeZipFile,	\
			sig_netscape_applet_AppletClassLoader_closeZipFile))
#define unuse_netscape_applet_AppletClassLoader_closeZipFile(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_closeZipFile = JRIUninitialized)

/*** close ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_close;
#define name_netscape_applet_AppletClassLoader_close	"close"
#define sig_netscape_applet_AppletClassLoader_close 	"()V"
#define use_netscape_applet_AppletClassLoader_close(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_close =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_close,	\
			sig_netscape_applet_AppletClassLoader_close))
#define unuse_netscape_applet_AppletClassLoader_close(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_close = JRIUninitialized)

/*** protected finalize ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_finalize;
#define name_netscape_applet_AppletClassLoader_finalize	"finalize"
#define sig_netscape_applet_AppletClassLoader_finalize 	"()V"
#define use_netscape_applet_AppletClassLoader_finalize(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_finalize =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_finalize,	\
			sig_netscape_applet_AppletClassLoader_finalize))
#define unuse_netscape_applet_AppletClassLoader_finalize(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_finalize = JRIUninitialized)

/*** mayScript ()Z ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_mayScript;
#define name_netscape_applet_AppletClassLoader_mayScript	"mayScript"
#define sig_netscape_applet_AppletClassLoader_mayScript 	"()Z"
#define use_netscape_applet_AppletClassLoader_mayScript(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_mayScript =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_mayScript,	\
			sig_netscape_applet_AppletClassLoader_mayScript))
#define unuse_netscape_applet_AppletClassLoader_mayScript(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_mayScript = JRIUninitialized)

/*** private loadClass (Ljava/lang/String;Ljava/net/URL;)Ljava/lang/Class; ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_loadClass;
#define name_netscape_applet_AppletClassLoader_loadClass	"loadClass"
#define sig_netscape_applet_AppletClassLoader_loadClass 	"(Ljava/lang/String;Ljava/net/URL;)Ljava/lang/Class;"
#define use_netscape_applet_AppletClassLoader_loadClass(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_loadClass =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_loadClass,	\
			sig_netscape_applet_AppletClassLoader_loadClass))
#define unuse_netscape_applet_AppletClassLoader_loadClass(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_loadClass = JRIUninitialized)

/*** protected loadClass (Ljava/lang/String;Z)Ljava/lang/Class; ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_loadClass_2;
#define name_netscape_applet_AppletClassLoader_loadClass_2	"loadClass"
#define sig_netscape_applet_AppletClassLoader_loadClass_2 	"(Ljava/lang/String;Z)Ljava/lang/Class;"
#define use_netscape_applet_AppletClassLoader_loadClass_2(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_loadClass_2 =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_loadClass_2,	\
			sig_netscape_applet_AppletClassLoader_loadClass_2))
#define unuse_netscape_applet_AppletClassLoader_loadClass_2(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_loadClass_2 = JRIUninitialized)

/*** loadClass1 (Ljava/lang/String;Z)Ljava/lang/Class; ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_loadClass1;
#define name_netscape_applet_AppletClassLoader_loadClass1	"loadClass1"
#define sig_netscape_applet_AppletClassLoader_loadClass1 	"(Ljava/lang/String;Z)Ljava/lang/Class;"
#define use_netscape_applet_AppletClassLoader_loadClass1(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_loadClass1 =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_loadClass1,	\
			sig_netscape_applet_AppletClassLoader_loadClass1))
#define unuse_netscape_applet_AppletClassLoader_loadClass1(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_loadClass1 = JRIUninitialized)

/*** private findClass (Ljava/lang/String;)Ljava/lang/Class; ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_findClass;
#define name_netscape_applet_AppletClassLoader_findClass	"findClass"
#define sig_netscape_applet_AppletClassLoader_findClass 	"(Ljava/lang/String;)Ljava/lang/Class;"
#define use_netscape_applet_AppletClassLoader_findClass(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_findClass =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_findClass,	\
			sig_netscape_applet_AppletClassLoader_findClass))
#define unuse_netscape_applet_AppletClassLoader_findClass(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_findClass = JRIUninitialized)

/*** getResource (Ljava/net/URL;)[B ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_getResource;
#define name_netscape_applet_AppletClassLoader_getResource	"getResource"
#define sig_netscape_applet_AppletClassLoader_getResource 	"(Ljava/net/URL;)[B"
#define use_netscape_applet_AppletClassLoader_getResource(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_getResource =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_getResource,	\
			sig_netscape_applet_AppletClassLoader_getResource))
#define unuse_netscape_applet_AppletClassLoader_getResource(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_getResource = JRIUninitialized)

/*** readURL (Ljava/net/URL;)[B ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader_readURL;
#define name_netscape_applet_AppletClassLoader_readURL	"readURL"
#define sig_netscape_applet_AppletClassLoader_readURL 	"(Ljava/net/URL;)[B"
#define use_netscape_applet_AppletClassLoader_readURL(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_readURL =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader_readURL,	\
			sig_netscape_applet_AppletClassLoader_readURL))
#define unuse_netscape_applet_AppletClassLoader_readURL(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader_readURL = JRIUninitialized)

/*** static <clinit> ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_AppletClassLoader__0003cclinit_0003e;
#define name_netscape_applet_AppletClassLoader__0003cclinit_0003e	"<clinit>"
#define sig_netscape_applet_AppletClassLoader__0003cclinit_0003e 	"()V"
#define use_netscape_applet_AppletClassLoader__0003cclinit_0003e(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader__0003cclinit_0003e =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_AppletClassLoader__0003cclinit_0003e,	\
			sig_netscape_applet_AppletClassLoader__0003cclinit_0003e))
#define unuse_netscape_applet_AppletClassLoader__0003cclinit_0003e(env, clazz)	\
	(methodID_netscape_applet_AppletClassLoader__0003cclinit_0003e = JRIUninitialized)

#endif /* IMPLEMENT_netscape_applet_AppletClassLoader */

#ifdef __cplusplus
} /* extern "C" */

/*******************************************************************************
 * C++ Definitions
 ******************************************************************************/

#include "java_lang_ClassLoader.h"

struct netscape_applet_AppletClassLoader : virtual public java_lang_ClassLoader {

	static struct java_lang_Class* _use(JRIEnv* env) {
		return use_netscape_applet_AppletClassLoader(env);
	}

	static void _unuse(JRIEnv* env) {
		unuse_netscape_applet_AppletClassLoader(env);
	}

	static struct java_lang_Class* _register(JRIEnv* env) {
		return register_netscape_applet_AppletClassLoader(env);
	}

	static void _unregister(JRIEnv* env) {
		unregister_netscape_applet_AppletClassLoader(env);
	}

	static struct java_lang_Class* _class(JRIEnv* env) {
		return class_netscape_applet_AppletClassLoader(env);
	}

	/* Public Methods */
	/*** public loadClass (Ljava/lang/String;)Ljava/lang/Class; ***/
	struct java_lang_Class * loadClass(JRIEnv* env, struct java_lang_String *a) {
		return netscape_applet_AppletClassLoader_loadClass_1(env, this, a);
	}

#ifdef IMPLEMENT_netscape_applet_AppletClassLoader

	/* Protected Methods */
	/*** protected finalize ()V ***/
	void finalize(JRIEnv* env) {
		netscape_applet_AppletClassLoader_finalize(env, this);
	}

	/*** protected loadClass (Ljava/lang/String;Z)Ljava/lang/Class; ***/
	struct java_lang_Class * loadClass(JRIEnv* env, struct java_lang_String *a, jbool b) {
		return netscape_applet_AppletClassLoader_loadClass_2(env, this, a, b);
	}

	/* Private Methods */
	/*** private loadClass (Ljava/lang/String;Ljava/net/URL;)Ljava/lang/Class; ***/
	struct java_lang_Class * loadClass(JRIEnv* env, struct java_lang_String *a, struct java_net_URL *b) {
		return netscape_applet_AppletClassLoader_loadClass(env, this, a, b);
	}

	/*** private findClass (Ljava/lang/String;)Ljava/lang/Class; ***/
	struct java_lang_Class * findClass(JRIEnv* env, struct java_lang_String *a) {
		return netscape_applet_AppletClassLoader_findClass(env, this, a);
	}

#endif /* IMPLEMENT_netscape_applet_AppletClassLoader */
};

#endif /* __cplusplus */

#endif /* Class netscape/applet/AppletClassLoader */
