#! gmake

DEPTH = ../../../../..

PACKAGES = netscape/tools/ClassFileParser

include $(DEPTH)/sun-java/config/classes.mk

BUILD_CLASSPATH = $(BOOT_CLASSPATH):$(DIST_CLASSPATH):$(DEPTH)/sun-java/classsrc/

