#include "_stubs/sun_awt_image_ImageRepresentation.c"
#include "_stubs/sun_awt_image_OffScreenImageSource.c"
#include "_stubs/sun_awt_motif_MButtonPeer.c"
#include "_stubs/sun_awt_motif_MCanvasPeer.c"
#include "_stubs/sun_awt_motif_MCheckboxPeer.c"
#include "_stubs/sun_awt_motif_MCheckboxMenuItemPeer.c"
#include "_stubs/sun_awt_motif_MComponentPeer.c"
#include "_stubs/sun_awt_motif_MDialogPeer.c"
#include "_stubs/sun_awt_motif_MFileDialogPeer.c"
#include "_stubs/sun_awt_motif_MFramePeer.c"
#include "_stubs/sun_awt_motif_MLabelPeer.c"
#include "_stubs/sun_awt_motif_MListPeer.c"
#include "_stubs/sun_awt_motif_MMenuBarPeer.c"
#include "_stubs/sun_awt_motif_MMenuItemPeer.c"
#include "_stubs/sun_awt_motif_MMenuPeer.c"
#include "_stubs/sun_awt_motif_MScrollbarPeer.c"
#include "_stubs/sun_awt_motif_MTextAreaPeer.c"
#include "_stubs/sun_awt_motif_MTextFieldPeer.c"
#include "_stubs/sun_awt_motif_MToolkit.c"
#include "_stubs/sun_awt_motif_MWindowPeer.c"
#include "_stubs/sun_awt_motif_X11FontMetrics.c"
#include "_stubs/sun_awt_motif_X11Graphics.c"

void _java_awt_init(void) {}
