/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class java/io/InputStream */

#ifdef IMPLEMENT_java_io_InputStream
#define _implementing_java_io_InputStream
#endif /* IMPLEMENT_java_io_InputStream */
#define IMPLEMENT_java_io_InputStream
#include "java_io_InputStream.h"

#ifndef UNUSED_java_io_InputStream_read
JRIMethodID FAR methodID_java_io_InputStream_read = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_io_InputStream_read(JRIEnv* env, struct java_io_InputStream* self) {
	if (methodID_java_io_InputStream_read == JRIUninitialized) {
		assert(!"Forgot to call use_java_io_InputStream(env) before calling method read ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_io_InputStream_read);
}
#endif /* DEBUG */
#endif /* UNUSED_java_io_InputStream_read */

#ifndef UNUSED_java_io_InputStream_read_1
JRIMethodID FAR methodID_java_io_InputStream_read_1 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_io_InputStream_read_1(JRIEnv* env, struct java_io_InputStream* self, jbyteArray a) {
	if (methodID_java_io_InputStream_read_1 == JRIUninitialized) {
		assert(!"Forgot to call use_java_io_InputStream(env) before calling method read ([B)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_io_InputStream_read_1, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_io_InputStream_read_1 */

#ifndef UNUSED_java_io_InputStream_read_2
JRIMethodID FAR methodID_java_io_InputStream_read_2 = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_io_InputStream_read_2(JRIEnv* env, struct java_io_InputStream* self, jbyteArray a, jint b, jint c) {
	if (methodID_java_io_InputStream_read_2 == JRIUninitialized) {
		assert(!"Forgot to call use_java_io_InputStream(env) before calling method read ([BII)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_io_InputStream_read_2, a, b, c);
}
#endif /* DEBUG */
#endif /* UNUSED_java_io_InputStream_read_2 */

#ifndef UNUSED_java_io_InputStream_skip
JRIMethodID FAR methodID_java_io_InputStream_skip = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jlong)
java_io_InputStream_skip(JRIEnv* env, struct java_io_InputStream* self, jlong a) {
	if (methodID_java_io_InputStream_skip == JRIUninitialized) {
		assert(!"Forgot to call use_java_io_InputStream(env) before calling method skip (J)J");
	}
	return (jlong)JRI_CallMethodLong(env)(env, JRI_CallMethod_op, self, methodID_java_io_InputStream_skip, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_io_InputStream_skip */

#ifndef UNUSED_java_io_InputStream_available
JRIMethodID FAR methodID_java_io_InputStream_available = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
java_io_InputStream_available(JRIEnv* env, struct java_io_InputStream* self) {
	if (methodID_java_io_InputStream_available == JRIUninitialized) {
		assert(!"Forgot to call use_java_io_InputStream(env) before calling method available ()I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_java_io_InputStream_available);
}
#endif /* DEBUG */
#endif /* UNUSED_java_io_InputStream_available */

#ifndef UNUSED_java_io_InputStream_close
JRIMethodID FAR methodID_java_io_InputStream_close = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_io_InputStream_close(JRIEnv* env, struct java_io_InputStream* self) {
	if (methodID_java_io_InputStream_close == JRIUninitialized) {
		assert(!"Forgot to call use_java_io_InputStream(env) before calling method close ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_io_InputStream_close);
}
#endif /* DEBUG */
#endif /* UNUSED_java_io_InputStream_close */

#ifndef UNUSED_java_io_InputStream_mark
JRIMethodID FAR methodID_java_io_InputStream_mark = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_io_InputStream_mark(JRIEnv* env, struct java_io_InputStream* self, jint a) {
	if (methodID_java_io_InputStream_mark == JRIUninitialized) {
		assert(!"Forgot to call use_java_io_InputStream(env) before calling method mark (I)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_io_InputStream_mark, a);
}
#endif /* DEBUG */
#endif /* UNUSED_java_io_InputStream_mark */

#ifndef UNUSED_java_io_InputStream_reset
JRIMethodID FAR methodID_java_io_InputStream_reset = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
java_io_InputStream_reset(JRIEnv* env, struct java_io_InputStream* self) {
	if (methodID_java_io_InputStream_reset == JRIUninitialized) {
		assert(!"Forgot to call use_java_io_InputStream(env) before calling method reset ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_java_io_InputStream_reset);
}
#endif /* DEBUG */
#endif /* UNUSED_java_io_InputStream_reset */

#ifndef UNUSED_java_io_InputStream_markSupported
JRIMethodID FAR methodID_java_io_InputStream_markSupported = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jbool)
java_io_InputStream_markSupported(JRIEnv* env, struct java_io_InputStream* self) {
	if (methodID_java_io_InputStream_markSupported == JRIUninitialized) {
		assert(!"Forgot to call use_java_io_InputStream(env) before calling method markSupported ()Z");
	}
	return (jbool)JRI_CallMethodBoolean(env)(env, JRI_CallMethod_op, self, methodID_java_io_InputStream_markSupported);
}
#endif /* DEBUG */
#endif /* UNUSED_java_io_InputStream_markSupported */

#ifndef UNUSED_java_io_InputStream_new
JRIMethodID FAR methodID_java_io_InputStream_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_io_InputStream*)
java_io_InputStream_new(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_java_io_InputStream_new == JRIUninitialized) {
		assert(!"Forgot to call use_java_io_InputStream(env) before calling method <init> ()V");
	}
	return (struct java_io_InputStream*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_java_io_InputStream_new);
}
#endif /* DEBUG */
#endif /* UNUSED_java_io_InputStream_new */

#ifndef UNUSED_use_java_io_InputStream

static jglobal _globalclass_java_io_InputStream = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_java_io_InputStream(JRIEnv* env)
{
	if (_globalclass_java_io_InputStream == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_io_InputStream);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_java_io_InputStream);
			return NULL;
		}
		use_java_io_InputStream_read(env, clazz);
		use_java_io_InputStream_read_1(env, clazz);
		use_java_io_InputStream_read_2(env, clazz);
		use_java_io_InputStream_skip(env, clazz);
		use_java_io_InputStream_available(env, clazz);
		use_java_io_InputStream_close(env, clazz);
		use_java_io_InputStream_mark(env, clazz);
		use_java_io_InputStream_reset(env, clazz);
		use_java_io_InputStream_markSupported(env, clazz);
		use_java_io_InputStream_new(env, clazz);
		_globalclass_java_io_InputStream = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return JRI_GetGlobalRef(env, _globalclass_java_io_InputStream);
	}
}

JRI_PUBLIC_API(void)
unuse_java_io_InputStream(JRIEnv* env)
{
	if (_globalclass_java_io_InputStream != NULL) {
		struct java_lang_Class* clazz = JRI_GetGlobalRef(env, _globalclass_java_io_InputStream);
		unuse_java_io_InputStream_read(env, clazz);
		unuse_java_io_InputStream_read_1(env, clazz);
		unuse_java_io_InputStream_read_2(env, clazz);
		unuse_java_io_InputStream_skip(env, clazz);
		unuse_java_io_InputStream_available(env, clazz);
		unuse_java_io_InputStream_close(env, clazz);
		unuse_java_io_InputStream_mark(env, clazz);
		unuse_java_io_InputStream_reset(env, clazz);
		unuse_java_io_InputStream_markSupported(env, clazz);
		unuse_java_io_InputStream_new(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_java_io_InputStream);
		_globalclass_java_io_InputStream = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_java_io_InputStream */

#ifdef _implementing_java_io_InputStream

JRI_PUBLIC_API(struct java_lang_Class*)
register_java_io_InputStream(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		NULL
	};
	void* nativeProcs[] = {
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_io_InputStream);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_java_io_InputStream);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_java_io_InputStream(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_java_io_InputStream(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_java_io_InputStream);
	JRI_UnregisterNatives(env, clazz);
	unuse_java_io_InputStream(env);
}

#endif /* _implementing_java_io_InputStream */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK


#endif /* NO_JDK */

