/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class java/lang/Math */

/* SYMBOL: "java/lang/Math/sin(D)D", Java_java_lang_Math_sin_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_sin_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	extern double java_lang_Math_sin(void *, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_sin(NULL,GET_DOUBLE(_t0, _P_+0)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/cos(D)D", Java_java_lang_Math_cos_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_cos_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	extern double java_lang_Math_cos(void *, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_cos(NULL,GET_DOUBLE(_t0, _P_+0)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/tan(D)D", Java_java_lang_Math_tan_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_tan_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	extern double java_lang_Math_tan(void *, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_tan(NULL,GET_DOUBLE(_t0, _P_+0)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/asin(D)D", Java_java_lang_Math_asin_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_asin_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	extern double java_lang_Math_asin(void *, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_asin(NULL,GET_DOUBLE(_t0, _P_+0)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/acos(D)D", Java_java_lang_Math_acos_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_acos_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	extern double java_lang_Math_acos(void *, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_acos(NULL,GET_DOUBLE(_t0, _P_+0)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/atan(D)D", Java_java_lang_Math_atan_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_atan_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	extern double java_lang_Math_atan(void *, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_atan(NULL,GET_DOUBLE(_t0, _P_+0)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/exp(D)D", Java_java_lang_Math_exp_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_exp_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	extern double java_lang_Math_exp(void *, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_exp(NULL,GET_DOUBLE(_t0, _P_+0)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/log(D)D", Java_java_lang_Math_log_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_log_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	extern double java_lang_Math_log(void *, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_log(NULL,GET_DOUBLE(_t0, _P_+0)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/sqrt(D)D", Java_java_lang_Math_sqrt_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_sqrt_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	extern double java_lang_Math_sqrt(void *, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_sqrt(NULL,GET_DOUBLE(_t0, _P_+0)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/IEEEremainder(DD)D", Java_java_lang_Math_IEEEremainder_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_IEEEremainder_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	Java8 _t2;
	extern double java_lang_Math_IEEEremainder(void *, double, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_IEEEremainder(NULL,GET_DOUBLE(_t0, _P_+0),GET_DOUBLE(_t2, _P_+2)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/ceil(D)D", Java_java_lang_Math_ceil_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_ceil_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	extern double java_lang_Math_ceil(void *, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_ceil(NULL,GET_DOUBLE(_t0, _P_+0)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/floor(D)D", Java_java_lang_Math_floor_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_floor_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	extern double java_lang_Math_floor(void *, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_floor(NULL,GET_DOUBLE(_t0, _P_+0)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/rint(D)D", Java_java_lang_Math_rint_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_rint_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	extern double java_lang_Math_rint(void *, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_rint(NULL,GET_DOUBLE(_t0, _P_+0)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/atan2(DD)D", Java_java_lang_Math_atan2_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_atan2_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	Java8 _t2;
	extern double java_lang_Math_atan2(void *, double, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_atan2(NULL,GET_DOUBLE(_t0, _P_+0),GET_DOUBLE(_t2, _P_+2)));
	return _P_ + 2;
}

/* SYMBOL: "java/lang/Math/pow(DD)D", Java_java_lang_Math_pow_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Math_pow_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _tval;
	Java8 _t0;
	Java8 _t2;
	extern double java_lang_Math_pow(void *, double, double);
	SET_DOUBLE(_tval, _P_, java_lang_Math_pow(NULL,GET_DOUBLE(_t0, _P_+0),GET_DOUBLE(_t2, _P_+2)));
	return _P_ + 2;
}

