/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class netscape/javascript/JSObject */

#ifdef IMPLEMENT_netscape_javascript_JSObject
#define _implementing_netscape_javascript_JSObject
#endif /* IMPLEMENT_netscape_javascript_JSObject */
#define IMPLEMENT_netscape_javascript_JSObject
#include "netscape_javascript_JSObject.h"

#ifndef UNUSED_netscape_javascript_JSObject_internal
JRIFieldID FAR fieldID_netscape_javascript_JSObject_internal = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
get_netscape_javascript_JSObject_internal(JRIEnv* env, struct netscape_javascript_JSObject* obj) {
	if (fieldID_netscape_javascript_JSObject_internal == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before accessing field internal I");
	}
	return JRI_GetFieldInt(env, obj, fieldID_netscape_javascript_JSObject_internal);
}
JRI_PUBLIC_API(void)
set_netscape_javascript_JSObject_internal(JRIEnv* env, struct netscape_javascript_JSObject* obj, jint v) {
	if (fieldID_netscape_javascript_JSObject_internal == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before accessing field internal I");
	}
	JRI_SetFieldInt(env, obj, fieldID_netscape_javascript_JSObject_internal, v);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject_internal */

#ifndef UNUSED_netscape_javascript_JSObject_initClass
JRIMethodID FAR methodID_netscape_javascript_JSObject_initClass = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
netscape_javascript_JSObject_initClass(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_netscape_javascript_JSObject_initClass == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before calling method initClass ()V");
	}
	(void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_javascript_JSObject_initClass);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject_initClass */

#ifndef UNUSED_netscape_javascript_JSObject_new
JRIMethodID FAR methodID_netscape_javascript_JSObject_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct netscape_javascript_JSObject*)
netscape_javascript_JSObject_new(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_netscape_javascript_JSObject_new == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before calling method <init> ()V");
	}
	return (struct netscape_javascript_JSObject*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_netscape_javascript_JSObject_new);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject_new */

#ifndef UNUSED_netscape_javascript_JSObject_getMember
JRIMethodID FAR methodID_netscape_javascript_JSObject_getMember = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_Object *)
netscape_javascript_JSObject_getMember(JRIEnv* env, struct netscape_javascript_JSObject* self, struct java_lang_String *a) {
	if (methodID_netscape_javascript_JSObject_getMember == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before calling method getMember (Ljava/lang/String;)Ljava/lang/Object;");
	}
	return (struct java_lang_Object *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_netscape_javascript_JSObject_getMember, a);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject_getMember */

#ifndef UNUSED_netscape_javascript_JSObject_getSlot
JRIMethodID FAR methodID_netscape_javascript_JSObject_getSlot = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_Object *)
netscape_javascript_JSObject_getSlot(JRIEnv* env, struct netscape_javascript_JSObject* self, jint a) {
	if (methodID_netscape_javascript_JSObject_getSlot == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before calling method getSlot (I)Ljava/lang/Object;");
	}
	return (struct java_lang_Object *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_netscape_javascript_JSObject_getSlot, a);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject_getSlot */

#ifndef UNUSED_netscape_javascript_JSObject_setMember
JRIMethodID FAR methodID_netscape_javascript_JSObject_setMember = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
netscape_javascript_JSObject_setMember(JRIEnv* env, struct netscape_javascript_JSObject* self, struct java_lang_String *a, struct java_lang_Object *b) {
	if (methodID_netscape_javascript_JSObject_setMember == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before calling method setMember (Ljava/lang/String;Ljava/lang/Object;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_netscape_javascript_JSObject_setMember, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject_setMember */

#ifndef UNUSED_netscape_javascript_JSObject_setSlot
JRIMethodID FAR methodID_netscape_javascript_JSObject_setSlot = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
netscape_javascript_JSObject_setSlot(JRIEnv* env, struct netscape_javascript_JSObject* self, jint a, struct java_lang_Object *b) {
	if (methodID_netscape_javascript_JSObject_setSlot == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before calling method setSlot (ILjava/lang/Object;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_netscape_javascript_JSObject_setSlot, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject_setSlot */

#ifndef UNUSED_netscape_javascript_JSObject_removeMember
JRIMethodID FAR methodID_netscape_javascript_JSObject_removeMember = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
netscape_javascript_JSObject_removeMember(JRIEnv* env, struct netscape_javascript_JSObject* self, struct java_lang_String *a) {
	if (methodID_netscape_javascript_JSObject_removeMember == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before calling method removeMember (Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_netscape_javascript_JSObject_removeMember, a);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject_removeMember */

#ifndef UNUSED_netscape_javascript_JSObject_call
JRIMethodID FAR methodID_netscape_javascript_JSObject_call = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_Object *)
netscape_javascript_JSObject_call(JRIEnv* env, struct netscape_javascript_JSObject* self, struct java_lang_String *a, jobjectArray b) {
	if (methodID_netscape_javascript_JSObject_call == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before calling method call (Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;");
	}
	return (struct java_lang_Object *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_netscape_javascript_JSObject_call, a, b);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject_call */

#ifndef UNUSED_netscape_javascript_JSObject_eval
JRIMethodID FAR methodID_netscape_javascript_JSObject_eval = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_Object *)
netscape_javascript_JSObject_eval(JRIEnv* env, struct netscape_javascript_JSObject* self, struct java_lang_String *a) {
	if (methodID_netscape_javascript_JSObject_eval == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before calling method eval (Ljava/lang/String;)Ljava/lang/Object;");
	}
	return (struct java_lang_Object *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_netscape_javascript_JSObject_eval, a);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject_eval */

#ifndef UNUSED_netscape_javascript_JSObject_toString
JRIMethodID FAR methodID_netscape_javascript_JSObject_toString = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
netscape_javascript_JSObject_toString(JRIEnv* env, struct netscape_javascript_JSObject* self) {
	if (methodID_netscape_javascript_JSObject_toString == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before calling method toString ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_netscape_javascript_JSObject_toString);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject_toString */

#ifndef UNUSED_netscape_javascript_JSObject_getWindow
JRIMethodID FAR methodID_netscape_javascript_JSObject_getWindow = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct netscape_javascript_JSObject *)
netscape_javascript_JSObject_getWindow(JRIEnv* env, struct java_lang_Class* clazz, struct java_applet_Applet *a) {
	if (methodID_netscape_javascript_JSObject_getWindow == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before calling method getWindow (Ljava/applet/Applet;)Lnetscape/javascript/JSObject;");
	}
	return (struct netscape_javascript_JSObject *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_javascript_JSObject_getWindow, a);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject_getWindow */

#ifndef UNUSED_netscape_javascript_JSObject_finalize
JRIMethodID FAR methodID_netscape_javascript_JSObject_finalize = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
netscape_javascript_JSObject_finalize(JRIEnv* env, struct netscape_javascript_JSObject* self) {
	if (methodID_netscape_javascript_JSObject_finalize == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before calling method finalize ()V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_netscape_javascript_JSObject_finalize);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject_finalize */

#ifndef UNUSED_netscape_javascript_JSObject__0003cclinit_0003e
JRIMethodID FAR methodID_netscape_javascript_JSObject__0003cclinit_0003e = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
netscape_javascript_JSObject__0003cclinit_0003e(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_netscape_javascript_JSObject__0003cclinit_0003e == JRIUninitialized) {
		assert(!"Forgot to call use_netscape_javascript_JSObject(env) before calling method <clinit> ()V");
	}
	(void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_javascript_JSObject__0003cclinit_0003e);
}
#endif /* DEBUG */
#endif /* UNUSED_netscape_javascript_JSObject__0003cclinit_0003e */

#ifndef UNUSED_use_netscape_javascript_JSObject

static jglobal _globalclass_netscape_javascript_JSObject = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_netscape_javascript_JSObject(JRIEnv* env)
{
	if (_globalclass_netscape_javascript_JSObject == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_netscape_javascript_JSObject);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_netscape_javascript_JSObject);
			return NULL;
		}
		use_netscape_javascript_JSObject_internal(env, clazz);
		use_netscape_javascript_JSObject_initClass(env, clazz);
		use_netscape_javascript_JSObject_new(env, clazz);
		use_netscape_javascript_JSObject_getMember(env, clazz);
		use_netscape_javascript_JSObject_getSlot(env, clazz);
		use_netscape_javascript_JSObject_setMember(env, clazz);
		use_netscape_javascript_JSObject_setSlot(env, clazz);
		use_netscape_javascript_JSObject_removeMember(env, clazz);
		use_netscape_javascript_JSObject_call(env, clazz);
		use_netscape_javascript_JSObject_eval(env, clazz);
		use_netscape_javascript_JSObject_toString(env, clazz);
		use_netscape_javascript_JSObject_getWindow(env, clazz);
		use_netscape_javascript_JSObject_finalize(env, clazz);
		use_netscape_javascript_JSObject__0003cclinit_0003e(env, clazz);
		_globalclass_netscape_javascript_JSObject = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return JRI_GetGlobalRef(env, _globalclass_netscape_javascript_JSObject);
	}
}

JRI_PUBLIC_API(void)
unuse_netscape_javascript_JSObject(JRIEnv* env)
{
	if (_globalclass_netscape_javascript_JSObject != NULL) {
		struct java_lang_Class* clazz = JRI_GetGlobalRef(env, _globalclass_netscape_javascript_JSObject);
		unuse_netscape_javascript_JSObject_internal(env, clazz);
		unuse_netscape_javascript_JSObject_initClass(env, clazz);
		unuse_netscape_javascript_JSObject_new(env, clazz);
		unuse_netscape_javascript_JSObject_getMember(env, clazz);
		unuse_netscape_javascript_JSObject_getSlot(env, clazz);
		unuse_netscape_javascript_JSObject_setMember(env, clazz);
		unuse_netscape_javascript_JSObject_setSlot(env, clazz);
		unuse_netscape_javascript_JSObject_removeMember(env, clazz);
		unuse_netscape_javascript_JSObject_call(env, clazz);
		unuse_netscape_javascript_JSObject_eval(env, clazz);
		unuse_netscape_javascript_JSObject_toString(env, clazz);
		unuse_netscape_javascript_JSObject_getWindow(env, clazz);
		unuse_netscape_javascript_JSObject_finalize(env, clazz);
		unuse_netscape_javascript_JSObject__0003cclinit_0003e(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_netscape_javascript_JSObject);
		_globalclass_netscape_javascript_JSObject = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_netscape_javascript_JSObject */

#ifdef _implementing_netscape_javascript_JSObject

JRI_PUBLIC_API(struct java_lang_Class*)
register_netscape_javascript_JSObject(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		"initClass()V",
		"getMember(Ljava/lang/String;)Ljava/lang/Object;",
		"getSlot(I)Ljava/lang/Object;",
		"setMember(Ljava/lang/String;Ljava/lang/Object;)V",
		"setSlot(ILjava/lang/Object;)V",
		"removeMember(Ljava/lang/String;)V",
		"call(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;",
		"eval(Ljava/lang/String;)Ljava/lang/Object;",
		"toString()Ljava/lang/String;",
		"getWindow(Ljava/applet/Applet;)Lnetscape/javascript/JSObject;",
		"finalize()V",
		NULL
	};
	void* nativeProcs[] = {
		(void*)native_netscape_javascript_JSObject_initClass,
		(void*)native_netscape_javascript_JSObject_getMember,
		(void*)native_netscape_javascript_JSObject_getSlot,
		(void*)native_netscape_javascript_JSObject_setMember,
		(void*)native_netscape_javascript_JSObject_setSlot,
		(void*)native_netscape_javascript_JSObject_removeMember,
		(void*)native_netscape_javascript_JSObject_call,
		(void*)native_netscape_javascript_JSObject_eval,
		(void*)native_netscape_javascript_JSObject_toString,
		(void*)native_netscape_javascript_JSObject_getWindow,
		(void*)native_netscape_javascript_JSObject_finalize,
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_netscape_javascript_JSObject);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_netscape_javascript_JSObject);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_netscape_javascript_JSObject(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_netscape_javascript_JSObject(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_netscape_javascript_JSObject);
	JRI_UnregisterNatives(env, clazz);
	unuse_netscape_javascript_JSObject(env);
}

#endif /* _implementing_netscape_javascript_JSObject */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK

/* SYMBOL: "netscape/javascript/JSObject/initClass()V", Java_netscape_javascript_JSObject_initClass_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_netscape_javascript_JSObject_initClass_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_netscape_javascript_JSObject_initClass(_EE_,NULL);
	return _P_;
}

/* SYMBOL: "netscape/javascript/JSObject/getMember(Ljava/lang/String;)Ljava/lang/Object;", Java_netscape_javascript_JSObject_getMember_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_netscape_javascript_JSObject_getMember_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_netscape_javascript_JSObject_getMember(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

/* SYMBOL: "netscape/javascript/JSObject/getSlot(I)Ljava/lang/Object;", Java_netscape_javascript_JSObject_getSlot_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_netscape_javascript_JSObject_getSlot_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_netscape_javascript_JSObject_getSlot(_EE_,_P_[0].p,((_P_[1].i)));
	return _P_ + 1;
}

/* SYMBOL: "netscape/javascript/JSObject/setMember(Ljava/lang/String;Ljava/lang/Object;)V", Java_netscape_javascript_JSObject_setMember_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_netscape_javascript_JSObject_setMember_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_netscape_javascript_JSObject_setMember(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "netscape/javascript/JSObject/setSlot(ILjava/lang/Object;)V", Java_netscape_javascript_JSObject_setSlot_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_netscape_javascript_JSObject_setSlot_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_netscape_javascript_JSObject_setSlot(_EE_,_P_[0].p,((_P_[1].i)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "netscape/javascript/JSObject/removeMember(Ljava/lang/String;)V", Java_netscape_javascript_JSObject_removeMember_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_netscape_javascript_JSObject_removeMember_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_netscape_javascript_JSObject_removeMember(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "netscape/javascript/JSObject/call(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;", Java_netscape_javascript_JSObject_call_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_netscape_javascript_JSObject_call_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_netscape_javascript_JSObject_call(_EE_,_P_[0].p,((_P_[1].p)),((_P_[2].p)));
	return _P_ + 1;
}

/* SYMBOL: "netscape/javascript/JSObject/eval(Ljava/lang/String;)Ljava/lang/Object;", Java_netscape_javascript_JSObject_eval_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_netscape_javascript_JSObject_eval_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_netscape_javascript_JSObject_eval(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

/* SYMBOL: "netscape/javascript/JSObject/toString()Ljava/lang/String;", Java_netscape_javascript_JSObject_toString_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_netscape_javascript_JSObject_toString_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_netscape_javascript_JSObject_toString(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "netscape/javascript/JSObject/getWindow(Ljava/applet/Applet;)Lnetscape/javascript/JSObject;", Java_netscape_javascript_JSObject_getWindow_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_netscape_javascript_JSObject_getWindow_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_netscape_javascript_JSObject_getWindow(_EE_,NULL,((_P_[0].p)));
	return _P_ + 1;
}

/* SYMBOL: "netscape/javascript/JSObject/finalize()V", Java_netscape_javascript_JSObject_finalize_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_netscape_javascript_JSObject_finalize_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_netscape_javascript_JSObject_finalize(_EE_,_P_[0].p);
	return _P_;
}

#endif /* NO_JDK */

