/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/macos/MToolkit */

/* SYMBOL: "sun/awt/macos/MToolkit/makeColorModel()Ljava/awt/image/ColorModel;", Java_sun_awt_macos_MToolkit_makeColorModel_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MToolkit_makeColorModel_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void* sun_awt_macos_MToolkit_makeColorModel(void *);
	_P_[0].p = sun_awt_macos_MToolkit_makeColorModel(NULL);
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/macos/MToolkit/getScreenResolution()I", Java_sun_awt_macos_MToolkit_getScreenResolution_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MToolkit_getScreenResolution_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_macos_MToolkit_getScreenResolution(void *);
	_P_[0].i = sun_awt_macos_MToolkit_getScreenResolution(_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/macos/MToolkit/getScreenWidth()I", Java_sun_awt_macos_MToolkit_getScreenWidth_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MToolkit_getScreenWidth_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_macos_MToolkit_getScreenWidth(void *);
	_P_[0].i = sun_awt_macos_MToolkit_getScreenWidth(_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/macos/MToolkit/getScreenHeight()I", Java_sun_awt_macos_MToolkit_getScreenHeight_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MToolkit_getScreenHeight_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_macos_MToolkit_getScreenHeight(void *);
	_P_[0].i = sun_awt_macos_MToolkit_getScreenHeight(_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/macos/MToolkit/init()V", Java_sun_awt_macos_MToolkit_init_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MToolkit_init_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MToolkit_init(void *);
	(void) sun_awt_macos_MToolkit_init(_P_[0].p);
	return _P_;
}

