/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/macos/MMenuBarPeer */

/* SYMBOL: "sun/awt/macos/MMenuBarPeer/create(Ljava/awt/Frame;)V", Java_sun_awt_macos_MMenuBarPeer_create_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MMenuBarPeer_create_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MMenuBarPeer_create(void *, void *);
	(void) sun_awt_macos_MMenuBarPeer_create(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MMenuBarPeer/dispose()V", Java_sun_awt_macos_MMenuBarPeer_dispose_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MMenuBarPeer_dispose_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MMenuBarPeer_dispose(void *);
	(void) sun_awt_macos_MMenuBarPeer_dispose(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MMenuBarPeer/addMenu(Ljava/awt/Menu;)V", Java_sun_awt_macos_MMenuBarPeer_addMenu_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MMenuBarPeer_addMenu_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MMenuBarPeer_addMenu(void *, void *);
	(void) sun_awt_macos_MMenuBarPeer_addMenu(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MMenuBarPeer/delMenu(I)V", Java_sun_awt_macos_MMenuBarPeer_delMenu_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MMenuBarPeer_delMenu_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MMenuBarPeer_delMenu(void *, long);
	(void) sun_awt_macos_MMenuBarPeer_delMenu(_P_[0].p,((_P_[1].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MMenuBarPeer/addHelpMenu(Ljava/awt/Menu;)V", Java_sun_awt_macos_MMenuBarPeer_addHelpMenu_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MMenuBarPeer_addHelpMenu_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MMenuBarPeer_addHelpMenu(void *, void *);
	(void) sun_awt_macos_MMenuBarPeer_addHelpMenu(_P_[0].p,((_P_[1].p)));
	return _P_;
}

