/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/macos/MacGraphics */

/* SYMBOL: "sun/awt/macos/MacGraphics/createFromComponent(Lsun/awt/macos/MComponentPeer;)V", Java_sun_awt_macos_MacGraphics_createFromComponent_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_createFromComponent_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_createFromComponent(void *, void *);
	(void) sun_awt_macos_MacGraphics_createFromComponent(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/createFromGraphics(Lsun/awt/macos/MacGraphics;)V", Java_sun_awt_macos_MacGraphics_createFromGraphics_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_createFromGraphics_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_createFromGraphics(void *, void *);
	(void) sun_awt_macos_MacGraphics_createFromGraphics(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/createFromIRepresentation(Lsun/awt/image/ImageRepresentation;)V", Java_sun_awt_macos_MacGraphics_createFromIRepresentation_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_createFromIRepresentation_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_createFromIRepresentation(void *, void *);
	(void) sun_awt_macos_MacGraphics_createFromIRepresentation(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/pSetFont(Ljava/awt/Font;)V", Java_sun_awt_macos_MacGraphics_pSetFont_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_pSetFont_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_pSetFont(void *, void *);
	(void) sun_awt_macos_MacGraphics_pSetFont(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/pSetForeground(Ljava/awt/Color;)V", Java_sun_awt_macos_MacGraphics_pSetForeground_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_pSetForeground_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_pSetForeground(void *, void *);
	(void) sun_awt_macos_MacGraphics_pSetForeground(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/pSetScaling(FF)V", Java_sun_awt_macos_MacGraphics_pSetScaling_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_pSetScaling_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_pSetScaling(void *, float, float);
	(void) sun_awt_macos_MacGraphics_pSetScaling(_P_[0].p,((_P_[1].f)),((_P_[2].f)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/pSetOrigin(II)V", Java_sun_awt_macos_MacGraphics_pSetOrigin_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_pSetOrigin_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_pSetOrigin(void *, long, long);
	(void) sun_awt_macos_MacGraphics_pSetOrigin(_P_[0].p,((_P_[1].i)),((_P_[2].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/dispose()V", Java_sun_awt_macos_MacGraphics_dispose_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_dispose_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_dispose(void *);
	(void) sun_awt_macos_MacGraphics_dispose(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/setPaintMode()V", Java_sun_awt_macos_MacGraphics_setPaintMode_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_setPaintMode_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_setPaintMode(void *);
	(void) sun_awt_macos_MacGraphics_setPaintMode(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/setXORMode(Ljava/awt/Color;)V", Java_sun_awt_macos_MacGraphics_setXORMode_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_setXORMode_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_setXORMode(void *, void *);
	(void) sun_awt_macos_MacGraphics_setXORMode(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/getClipRect(Ljava/awt/Rectangle;)V", Java_sun_awt_macos_MacGraphics_getClipRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_getClipRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_getClipRect(void *, void *);
	(void) sun_awt_macos_MacGraphics_getClipRect(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/clipRect(IIII)V", Java_sun_awt_macos_MacGraphics_clipRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_clipRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_clipRect(void *, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_clipRect(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/clearRect(IIII)V", Java_sun_awt_macos_MacGraphics_clearRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_clearRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_clearRect(void *, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_clearRect(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/fillRect(IIII)V", Java_sun_awt_macos_MacGraphics_fillRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_fillRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_fillRect(void *, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_fillRect(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/drawRect(IIII)V", Java_sun_awt_macos_MacGraphics_drawRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_drawRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_drawRect(void *, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_drawRect(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/drawString(Ljava/lang/String;II)V", Java_sun_awt_macos_MacGraphics_drawString_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_drawString_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_drawString(void *, void *, long, long);
	(void) sun_awt_macos_MacGraphics_drawString(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/drawChars([CIIII)V", Java_sun_awt_macos_MacGraphics_drawChars_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_drawChars_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_drawChars(void *, void *, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_drawChars(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/drawBytes([BIIII)V", Java_sun_awt_macos_MacGraphics_drawBytes_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_drawBytes_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_drawBytes(void *, void *, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_drawBytes(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/drawStringWidth(Ljava/lang/String;II)I", Java_sun_awt_macos_MacGraphics_drawStringWidth_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_drawStringWidth_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_macos_MacGraphics_drawStringWidth(void *, void *, long, long);
	_P_[0].i = sun_awt_macos_MacGraphics_drawStringWidth(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)));
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/drawCharsWidth([CIIII)I", Java_sun_awt_macos_MacGraphics_drawCharsWidth_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_drawCharsWidth_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_macos_MacGraphics_drawCharsWidth(void *, void *, long, long, long, long);
	_P_[0].i = sun_awt_macos_MacGraphics_drawCharsWidth(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)));
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/drawBytesWidth([BIIII)I", Java_sun_awt_macos_MacGraphics_drawBytesWidth_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_drawBytesWidth_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_macos_MacGraphics_drawBytesWidth(void *, void *, long, long, long, long);
	_P_[0].i = sun_awt_macos_MacGraphics_drawBytesWidth(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)));
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/drawLine(IIII)V", Java_sun_awt_macos_MacGraphics_drawLine_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_drawLine_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_drawLine(void *, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_drawLine(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/copyArea(IIIIII)V", Java_sun_awt_macos_MacGraphics_copyArea_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_copyArea_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_copyArea(void *, long, long, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_copyArea(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)),((_P_[6].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/drawRoundRect(IIIIII)V", Java_sun_awt_macos_MacGraphics_drawRoundRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_drawRoundRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_drawRoundRect(void *, long, long, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_drawRoundRect(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)),((_P_[6].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/fillRoundRect(IIIIII)V", Java_sun_awt_macos_MacGraphics_fillRoundRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_fillRoundRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_fillRoundRect(void *, long, long, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_fillRoundRect(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)),((_P_[6].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/drawPolygon([I[II)V", Java_sun_awt_macos_MacGraphics_drawPolygon_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_drawPolygon_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_drawPolygon(void *, void *, void *, long);
	(void) sun_awt_macos_MacGraphics_drawPolygon(_P_[0].p,((_P_[1].p)),((_P_[2].p)),((_P_[3].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/fillPolygon([I[II)V", Java_sun_awt_macos_MacGraphics_fillPolygon_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_fillPolygon_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_fillPolygon(void *, void *, void *, long);
	(void) sun_awt_macos_MacGraphics_fillPolygon(_P_[0].p,((_P_[1].p)),((_P_[2].p)),((_P_[3].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/drawOval(IIII)V", Java_sun_awt_macos_MacGraphics_drawOval_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_drawOval_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_drawOval(void *, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_drawOval(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/fillOval(IIII)V", Java_sun_awt_macos_MacGraphics_fillOval_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_fillOval_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_fillOval(void *, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_fillOval(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/drawArc(IIIIII)V", Java_sun_awt_macos_MacGraphics_drawArc_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_drawArc_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_drawArc(void *, long, long, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_drawArc(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)),((_P_[6].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MacGraphics/fillArc(IIIIII)V", Java_sun_awt_macos_MacGraphics_fillArc_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MacGraphics_fillArc_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MacGraphics_fillArc(void *, long, long, long, long, long, long);
	(void) sun_awt_macos_MacGraphics_fillArc(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)),((_P_[6].i)));
	return _P_;
}

