/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/macos/MDialogPeer */

/* SYMBOL: "sun/awt/macos/MDialogPeer/create(Lsun/awt/macos/MComponentPeer;)V", Java_sun_awt_macos_MDialogPeer_create_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MDialogPeer_create_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MDialogPeer_create(void *, void *);
	(void) sun_awt_macos_MDialogPeer_create(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MDialogPeer/setTitle(Ljava/lang/String;)V", Java_sun_awt_macos_MDialogPeer_setTitle_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MDialogPeer_setTitle_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MDialogPeer_setTitle(void *, void *);
	(void) sun_awt_macos_MDialogPeer_setTitle(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MDialogPeer/setResizable(Z)V", Java_sun_awt_macos_MDialogPeer_setResizable_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MDialogPeer_setResizable_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MDialogPeer_setResizable(void *, long);
	(void) sun_awt_macos_MDialogPeer_setResizable(_P_[0].p,((_P_[1].i)));
	return _P_;
}

