/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/macos/MScrollbarPeer */

/* SYMBOL: "sun/awt/macos/MScrollbarPeer/create(Lsun/awt/macos/MComponentPeer;)V", Java_sun_awt_macos_MScrollbarPeer_create_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MScrollbarPeer_create_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MScrollbarPeer_create(void *, void *);
	(void) sun_awt_macos_MScrollbarPeer_create(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MScrollbarPeer/setValue(I)V", Java_sun_awt_macos_MScrollbarPeer_setValue_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MScrollbarPeer_setValue_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MScrollbarPeer_setValue(void *, long);
	(void) sun_awt_macos_MScrollbarPeer_setValue(_P_[0].p,((_P_[1].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MScrollbarPeer/setValues(IIII)V", Java_sun_awt_macos_MScrollbarPeer_setValues_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MScrollbarPeer_setValues_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MScrollbarPeer_setValues(void *, long, long, long, long);
	(void) sun_awt_macos_MScrollbarPeer_setValues(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MScrollbarPeer/setLineIncrement(I)V", Java_sun_awt_macos_MScrollbarPeer_setLineIncrement_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MScrollbarPeer_setLineIncrement_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MScrollbarPeer_setLineIncrement(void *, long);
	(void) sun_awt_macos_MScrollbarPeer_setLineIncrement(_P_[0].p,((_P_[1].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/macos/MScrollbarPeer/setPageIncrement(I)V", Java_sun_awt_macos_MScrollbarPeer_setPageIncrement_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_macos_MScrollbarPeer_setPageIncrement_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_macos_MScrollbarPeer_setPageIncrement(void *, long);
	(void) sun_awt_macos_MScrollbarPeer_setPageIncrement(_P_[0].p,((_P_[1].i)));
	return _P_;
}

