/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_lang_Runtime */

#ifndef _Included_java_lang_Runtime
#define _Included_java_lang_Runtime
struct Hjava_lang_String;

typedef struct Classjava_lang_Runtime {
/* Inaccessible static: currentRuntime */
    struct HArrayOfObject *paths;
} Classjava_lang_Runtime;
HandleTo(java_lang_Runtime);

extern void java_lang_Runtime_exitInternal(struct Hjava_lang_Runtime* self,long);
struct Hjava_lang_Process;
extern struct Hjava_lang_Process *java_lang_Runtime_execInternal(struct Hjava_lang_Runtime* self,HArrayOfString *,HArrayOfString *);
extern int64_t java_lang_Runtime_freeMemory(struct Hjava_lang_Runtime* self);
extern int64_t java_lang_Runtime_totalMemory(struct Hjava_lang_Runtime* self);
extern void java_lang_Runtime_gc(struct Hjava_lang_Runtime* self);
extern void java_lang_Runtime_runFinalization(struct Hjava_lang_Runtime* self);
extern void java_lang_Runtime_traceInstructions(struct Hjava_lang_Runtime* self,/*boolean*/ long);
extern void java_lang_Runtime_traceMethodCalls(struct Hjava_lang_Runtime* self,/*boolean*/ long);
extern struct Hjava_lang_String *java_lang_Runtime_initializeLinkerInternal(struct Hjava_lang_Runtime* self);
extern struct Hjava_lang_String *java_lang_Runtime_buildLibName(struct Hjava_lang_Runtime* self,struct Hjava_lang_String *,struct Hjava_lang_String *);
extern /*boolean*/ long java_lang_Runtime_loadFileInternal(struct Hjava_lang_Runtime* self,struct Hjava_lang_String *);
#endif
