/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_awt_Toolkit */

#ifndef _Included_java_awt_Toolkit
#define _Included_java_awt_Toolkit

typedef struct Classjava_awt_Toolkit {
/* Inaccessible static: toolkit */
    char PAD;	/* ANSI C requires structures to have a least one member */
} Classjava_awt_Toolkit;
HandleTo(java_awt_Toolkit);

#endif
