/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_io_RandomAccessFile */

#ifndef _Included_java_io_RandomAccessFile
#define _Included_java_io_RandomAccessFile
struct Hjava_io_FileDescriptor;

typedef struct Classjava_io_RandomAccessFile {
    struct Hjava_io_FileDescriptor *fd;
} Classjava_io_RandomAccessFile;
HandleTo(java_io_RandomAccessFile);

struct Hjava_lang_String;
extern void java_io_RandomAccessFile_open(struct Hjava_io_RandomAccessFile* self,struct Hjava_lang_String *,/*boolean*/ long);
extern long java_io_RandomAccessFile_read(struct Hjava_io_RandomAccessFile* self);
extern long java_io_RandomAccessFile_readBytes(struct Hjava_io_RandomAccessFile* self,HArrayOfByte *,long,long);
extern void java_io_RandomAccessFile_write(struct Hjava_io_RandomAccessFile* self,long);
extern void java_io_RandomAccessFile_writeBytes(struct Hjava_io_RandomAccessFile* self,HArrayOfByte *,long,long);
extern int64_t java_io_RandomAccessFile_getFilePointer(struct Hjava_io_RandomAccessFile* self);
extern void java_io_RandomAccessFile_seek(struct Hjava_io_RandomAccessFile* self,int64_t);
extern int64_t java_io_RandomAccessFile_length(struct Hjava_io_RandomAccessFile* self);
extern void java_io_RandomAccessFile_close(struct Hjava_io_RandomAccessFile* self);
#endif
