/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_lang_ClassLoader */

#ifndef _Included_java_lang_ClassLoader
#define _Included_java_lang_ClassLoader

typedef struct Classjava_lang_ClassLoader {
    /*boolean*/ long initialized;
} Classjava_lang_ClassLoader;
HandleTo(java_lang_ClassLoader);

struct Hjava_lang_String;
struct Hjava_lang_Class;
extern struct Hjava_lang_Class *java_lang_ClassLoader_defineClass(struct Hjava_lang_ClassLoader* self,struct Hjava_lang_String *,HArrayOfByte *,long,long);
extern void java_lang_ClassLoader_resolveClass(struct Hjava_lang_ClassLoader* self,struct Hjava_lang_Class *);
extern struct Hjava_lang_Class *java_lang_ClassLoader_findSystemClass(struct Hjava_lang_ClassLoader* self,struct Hjava_lang_String *);
extern void java_lang_ClassLoader_init(struct Hjava_lang_ClassLoader* self);
extern void java_lang_ClassLoader_checkInitialized(struct Hjava_lang_ClassLoader* self);
#endif
