/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_lang_OutOfMemoryError */

#ifndef _Included_java_lang_OutOfMemoryError
#define _Included_java_lang_OutOfMemoryError
struct Hjava_lang_Object;
struct Hjava_lang_String;

typedef struct Classjava_lang_OutOfMemoryError {
    struct Hjava_lang_Object *backtrace;
    struct Hjava_lang_String *detailMessage;
} Classjava_lang_OutOfMemoryError;
HandleTo(java_lang_OutOfMemoryError);

#endif
