/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_awt_Scrollbar */

#ifndef _Included_java_awt_Scrollbar
#define _Included_java_awt_Scrollbar
struct Hjava_awt_peer_ComponentPeer;
struct Hjava_awt_Container;
struct Hjava_awt_Color;
struct Hjava_awt_Font;

typedef struct Classjava_awt_Scrollbar {
    struct Hjava_awt_peer_ComponentPeer *peer;
    struct Hjava_awt_Container *parent;
    long x;
    long y;
    long width;
    long height;
    struct Hjava_awt_Color *foreground;
    struct Hjava_awt_Color *background;
    struct Hjava_awt_Font *font;
    /*boolean*/ long visible;
    /*boolean*/ long enabled;
    /*boolean*/ long valid;
#define java_awt_Scrollbar_HORIZONTAL	0L
#define java_awt_Scrollbar_VERTICAL	1L
    long value;
    long maximum;
    long minimum;
    long sVisible;
    long orientation;
    long lineIncrement;
    long pageIncrement;
} Classjava_awt_Scrollbar;
HandleTo(java_awt_Scrollbar);

#endif
