/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_awt_MenuBar */

#ifndef _Included_java_awt_MenuBar
#define _Included_java_awt_MenuBar
struct Hjava_awt_peer_MenuComponentPeer;
struct Hjava_awt_MenuContainer;
struct Hjava_awt_Font;
struct Hjava_util_Vector;
struct Hjava_awt_Menu;

typedef struct Classjava_awt_MenuBar {
    struct Hjava_awt_peer_MenuComponentPeer *peer;
    struct Hjava_awt_MenuContainer *parent;
    struct Hjava_awt_Font *font;
    struct Hjava_util_Vector *menus;
    struct Hjava_awt_Menu *helpMenu;
} Classjava_awt_MenuBar;
HandleTo(java_awt_MenuBar);

#endif
