/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_awt_image_ImageConsumer */

#ifndef _Included_java_awt_image_ImageConsumer
#define _Included_java_awt_image_ImageConsumer

typedef struct Classjava_awt_image_ImageConsumer {
#define java_awt_image_ImageConsumer_RANDOMPIXELORDER	1L
#define java_awt_image_ImageConsumer_TOPDOWNLEFTRIGHT	2L
#define java_awt_image_ImageConsumer_COMPLETESCANLINES	4L
#define java_awt_image_ImageConsumer_SINGLEPASS	8L
#define java_awt_image_ImageConsumer_SINGLEFRAME	16L
#define java_awt_image_ImageConsumer_IMAGEERROR	1L
#define java_awt_image_ImageConsumer_SINGLEFRAMEDONE	2L
#define java_awt_image_ImageConsumer_STATICIMAGEDONE	3L
#define java_awt_image_ImageConsumer_IMAGEABORTED	4L
    char PAD;	/* ANSI C requires structures to have a least one member */
} Classjava_awt_image_ImageConsumer;
HandleTo(java_awt_image_ImageConsumer);

#endif
