/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_awt_FileDialog */

#ifndef _Included_java_awt_FileDialog
#define _Included_java_awt_FileDialog
struct Hjava_awt_peer_ComponentPeer;
struct Hjava_awt_Container;
struct Hjava_awt_Color;
struct Hjava_awt_Font;
struct Hjava_awt_Component;
struct Hjava_awt_LayoutManager;
struct Hjava_lang_String;
struct Hjava_io_FilenameFilter;

typedef struct Classjava_awt_FileDialog {
    struct Hjava_awt_peer_ComponentPeer *peer;
    struct Hjava_awt_Container *parent;
    long x;
    long y;
    long width;
    long height;
    struct Hjava_awt_Color *foreground;
    struct Hjava_awt_Color *background;
    struct Hjava_awt_Font *font;
    /*boolean*/ long visible;
    /*boolean*/ long enabled;
    /*boolean*/ long valid;
    long ncomponents;
    struct HArrayOfObject *component;
    struct Hjava_awt_LayoutManager *layoutMgr;
    struct Hjava_lang_String *warningString;
    /*boolean*/ long resizable;
    /*boolean*/ long modal;
    struct Hjava_lang_String *title;
#define java_awt_FileDialog_LOAD	0L
#define java_awt_FileDialog_SAVE	1L
    long mode;
    struct Hjava_lang_String *dir;
    struct Hjava_lang_String *file;
    struct Hjava_io_FilenameFilter *filter;
} Classjava_awt_FileDialog;
HandleTo(java_awt_FileDialog);

#endif
