/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_io_FileInputStream */

#ifndef _Included_java_io_FileInputStream
#define _Included_java_io_FileInputStream
struct Hjava_io_FileDescriptor;

typedef struct Classjava_io_FileInputStream {
    struct Hjava_io_FileDescriptor *fd;
} Classjava_io_FileInputStream;
HandleTo(java_io_FileInputStream);

struct Hjava_lang_String;
extern void java_io_FileInputStream_open(struct Hjava_io_FileInputStream* self,struct Hjava_lang_String *);
extern long java_io_FileInputStream_read(struct Hjava_io_FileInputStream* self);
extern long java_io_FileInputStream_readBytes(struct Hjava_io_FileInputStream* self,HArrayOfByte *,long,long);
extern int64_t java_io_FileInputStream_skip(struct Hjava_io_FileInputStream* self,int64_t);
extern long java_io_FileInputStream_available(struct Hjava_io_FileInputStream* self);
extern void java_io_FileInputStream_close(struct Hjava_io_FileInputStream* self);
#endif
