/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_lang_UNIXProcess */

#ifndef _Included_java_lang_UNIXProcess
#define _Included_java_lang_UNIXProcess
struct Hjava_io_FileDescriptor;
struct Hjava_io_OutputStream;
struct Hjava_io_InputStream;

typedef struct Classjava_lang_UNIXProcess {
/* Inaccessible static: subprocs */
    /*boolean*/ long isalive;
    long exit_code;
    long pid;
    struct Hjava_io_FileDescriptor *sync_fd;
    struct Hjava_io_FileDescriptor *stdin_fd;
    struct Hjava_io_FileDescriptor *stdout_fd;
    struct Hjava_io_FileDescriptor *stderr_fd;
    struct Hjava_io_OutputStream *stdin_stream;
    struct Hjava_io_InputStream *stdout_stream;
    struct Hjava_io_InputStream *stderr_stream;
} Classjava_lang_UNIXProcess;
HandleTo(java_lang_UNIXProcess);

struct Hjava_lang_String;
extern void java_lang_UNIXProcess_exec(struct Hjava_lang_UNIXProcess* self,HArrayOfString *,HArrayOfString *);
extern long java_lang_UNIXProcess_fork(struct Hjava_lang_UNIXProcess* self);
extern long java_lang_UNIXProcess_waitForUNIXProcess(struct Hjava_lang_UNIXProcess* self);
extern void java_lang_UNIXProcess_destroy(struct Hjava_lang_UNIXProcess* self);
#endif
