/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_awt_Color */

#ifndef _Included_java_awt_Color
#define _Included_java_awt_Color

typedef struct Classjava_awt_Color {
/* Inaccessible static: white */
/* Inaccessible static: lightGray */
/* Inaccessible static: gray */
/* Inaccessible static: darkGray */
/* Inaccessible static: black */
/* Inaccessible static: red */
/* Inaccessible static: pink */
/* Inaccessible static: orange */
/* Inaccessible static: yellow */
/* Inaccessible static: green */
/* Inaccessible static: magenta */
/* Inaccessible static: cyan */
/* Inaccessible static: blue */
    long pData;
    long value;
#define java_awt_Color_FACTOR	0.7D
} Classjava_awt_Color;
HandleTo(java_awt_Color);

#endif
