/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Header for class netscape/applet/MozillaAppletContext */

#ifndef _netscape_applet_MozillaAppletContext_H_
#define _netscape_applet_MozillaAppletContext_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct netscape_applet_Mapping;
struct java_util_Hashtable;
struct java_net_URL;
struct java_lang_Integer;
struct java_io_PrintStream;
struct java_applet_AudioClip;
struct java_awt_Image;
struct java_lang_String;
struct java_applet_Applet;
struct java_util_Enumeration;
struct netscape_applet_MozillaAppletContext;
struct netscape_applet_EmbeddedAppletFrame;
struct java_lang_Object;
struct java_lang_Class;

/*******************************************************************************
 * Class netscape/applet/MozillaAppletContext
 ******************************************************************************/

typedef struct netscape_applet_MozillaAppletContext netscape_applet_MozillaAppletContext;

#define classname_netscape_applet_MozillaAppletContext	"netscape/applet/MozillaAppletContext"

#define class_netscape_applet_MozillaAppletContext(env) \
	((struct java_lang_Class*)JRI_FindClass(env, classname_netscape_applet_MozillaAppletContext))

/*******************************************************************************
 * Public Methods
 ******************************************************************************/

#ifdef DEBUG

/*** public getAudioClip (Ljava/net/URL;)Ljava/applet/AudioClip; ***/
extern JRI_PUBLIC_API(struct java_applet_AudioClip *)
netscape_applet_MozillaAppletContext_getAudioClip(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, struct java_net_URL *a);

/*** public getImage (Ljava/net/URL;)Ljava/awt/Image; ***/
extern JRI_PUBLIC_API(struct java_awt_Image *)
netscape_applet_MozillaAppletContext_getImage(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, struct java_net_URL *a);

/*** public getApplet (Ljava/lang/String;)Ljava/applet/Applet; ***/
extern JRI_PUBLIC_API(struct java_applet_Applet *)
netscape_applet_MozillaAppletContext_getApplet(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, struct java_lang_String *a);

/*** public getApplets ()Ljava/util/Enumeration; ***/
extern JRI_PUBLIC_API(struct java_util_Enumeration *)
netscape_applet_MozillaAppletContext_getApplets(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self);

/*** public showDocument (Ljava/net/URL;)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_showDocument(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, struct java_net_URL *a);

/*** public showDocument (Ljava/net/URL;Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_showDocument_1(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, struct java_net_URL *a, struct java_lang_String *b);

/*** public showStatus (Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_showStatus(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, struct java_lang_String *a);

/*** public mochaOnLoad (I)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_mochaOnLoad(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, jint a);

#else /* !DEBUG */

/*** public getAudioClip (Ljava/net/URL;)Ljava/applet/AudioClip; ***/
#define netscape_applet_MozillaAppletContext_getAudioClip(env, obj, a) \
	((struct java_applet_AudioClip *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_getAudioClip, a))

/*** public getImage (Ljava/net/URL;)Ljava/awt/Image; ***/
#define netscape_applet_MozillaAppletContext_getImage(env, obj, a) \
	((struct java_awt_Image *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_getImage, a))

/*** public getApplet (Ljava/lang/String;)Ljava/applet/Applet; ***/
#define netscape_applet_MozillaAppletContext_getApplet(env, obj, a) \
	((struct java_applet_Applet *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_getApplet, a))

/*** public getApplets ()Ljava/util/Enumeration; ***/
#define netscape_applet_MozillaAppletContext_getApplets(env, obj) \
	((struct java_util_Enumeration *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_getApplets))

/*** public showDocument (Ljava/net/URL;)V ***/
#define netscape_applet_MozillaAppletContext_showDocument(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_showDocument, a))

/*** public showDocument (Ljava/net/URL;Ljava/lang/String;)V ***/
#define netscape_applet_MozillaAppletContext_showDocument_1(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_showDocument_1, a, b))

/*** public showStatus (Ljava/lang/String;)V ***/
#define netscape_applet_MozillaAppletContext_showStatus(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_showStatus, a))

/*** public mochaOnLoad (I)V ***/
#define netscape_applet_MozillaAppletContext_mochaOnLoad(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_mochaOnLoad, a))

#endif /* !DEBUG*/

/*** public getAudioClip (Ljava/net/URL;)Ljava/applet/AudioClip; ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_getAudioClip;
#define name_netscape_applet_MozillaAppletContext_getAudioClip	"getAudioClip"
#define sig_netscape_applet_MozillaAppletContext_getAudioClip 	"(Ljava/net/URL;)Ljava/applet/AudioClip;"
#define use_netscape_applet_MozillaAppletContext_getAudioClip(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_getAudioClip =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_getAudioClip,	\
			sig_netscape_applet_MozillaAppletContext_getAudioClip))
#define unuse_netscape_applet_MozillaAppletContext_getAudioClip(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_getAudioClip = JRIUninitialized)

/*** public getImage (Ljava/net/URL;)Ljava/awt/Image; ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_getImage;
#define name_netscape_applet_MozillaAppletContext_getImage	"getImage"
#define sig_netscape_applet_MozillaAppletContext_getImage 	"(Ljava/net/URL;)Ljava/awt/Image;"
#define use_netscape_applet_MozillaAppletContext_getImage(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_getImage =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_getImage,	\
			sig_netscape_applet_MozillaAppletContext_getImage))
#define unuse_netscape_applet_MozillaAppletContext_getImage(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_getImage = JRIUninitialized)

/*** public getApplet (Ljava/lang/String;)Ljava/applet/Applet; ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_getApplet;
#define name_netscape_applet_MozillaAppletContext_getApplet	"getApplet"
#define sig_netscape_applet_MozillaAppletContext_getApplet 	"(Ljava/lang/String;)Ljava/applet/Applet;"
#define use_netscape_applet_MozillaAppletContext_getApplet(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_getApplet =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_getApplet,	\
			sig_netscape_applet_MozillaAppletContext_getApplet))
#define unuse_netscape_applet_MozillaAppletContext_getApplet(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_getApplet = JRIUninitialized)

/*** public getApplets ()Ljava/util/Enumeration; ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_getApplets;
#define name_netscape_applet_MozillaAppletContext_getApplets	"getApplets"
#define sig_netscape_applet_MozillaAppletContext_getApplets 	"()Ljava/util/Enumeration;"
#define use_netscape_applet_MozillaAppletContext_getApplets(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_getApplets =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_getApplets,	\
			sig_netscape_applet_MozillaAppletContext_getApplets))
#define unuse_netscape_applet_MozillaAppletContext_getApplets(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_getApplets = JRIUninitialized)

/*** public showDocument (Ljava/net/URL;)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_showDocument;
#define name_netscape_applet_MozillaAppletContext_showDocument	"showDocument"
#define sig_netscape_applet_MozillaAppletContext_showDocument 	"(Ljava/net/URL;)V"
#define use_netscape_applet_MozillaAppletContext_showDocument(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_showDocument =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_showDocument,	\
			sig_netscape_applet_MozillaAppletContext_showDocument))
#define unuse_netscape_applet_MozillaAppletContext_showDocument(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_showDocument = JRIUninitialized)

/*** public showDocument (Ljava/net/URL;Ljava/lang/String;)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_showDocument_1;
#define name_netscape_applet_MozillaAppletContext_showDocument_1	"showDocument"
#define sig_netscape_applet_MozillaAppletContext_showDocument_1 	"(Ljava/net/URL;Ljava/lang/String;)V"
#define use_netscape_applet_MozillaAppletContext_showDocument_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_showDocument_1 =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_showDocument_1,	\
			sig_netscape_applet_MozillaAppletContext_showDocument_1))
#define unuse_netscape_applet_MozillaAppletContext_showDocument_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_showDocument_1 = JRIUninitialized)

/*** public showStatus (Ljava/lang/String;)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_showStatus;
#define name_netscape_applet_MozillaAppletContext_showStatus	"showStatus"
#define sig_netscape_applet_MozillaAppletContext_showStatus 	"(Ljava/lang/String;)V"
#define use_netscape_applet_MozillaAppletContext_showStatus(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_showStatus =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_showStatus,	\
			sig_netscape_applet_MozillaAppletContext_showStatus))
#define unuse_netscape_applet_MozillaAppletContext_showStatus(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_showStatus = JRIUninitialized)

/*** public mochaOnLoad (I)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_mochaOnLoad;
#define name_netscape_applet_MozillaAppletContext_mochaOnLoad	"mochaOnLoad"
#define sig_netscape_applet_MozillaAppletContext_mochaOnLoad 	"(I)V"
#define use_netscape_applet_MozillaAppletContext_mochaOnLoad(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_mochaOnLoad =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_mochaOnLoad,	\
			sig_netscape_applet_MozillaAppletContext_mochaOnLoad))
#define unuse_netscape_applet_MozillaAppletContext_mochaOnLoad(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_mochaOnLoad = JRIUninitialized)

/*******************************************************************************
 * IMPLEMENTATION SECTION: 
 * Define the IMPLEMENT_netscape_applet_MozillaAppletContext symbol 
 * if you intend to implement the native methods of this class. This 
 * symbol makes the private and protected methods available. You should 
 * also call the register_netscape_applet_MozillaAppletContext routine 
 * to make your native methods available.
 ******************************************************************************/

extern JRI_PUBLIC_API(struct java_lang_Class*)
use_netscape_applet_MozillaAppletContext(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unuse_netscape_applet_MozillaAppletContext(JRIEnv* env);

extern JRI_PUBLIC_API(struct java_lang_Class*)
register_netscape_applet_MozillaAppletContext(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unregister_netscape_applet_MozillaAppletContext(JRIEnv* env);

#ifdef IMPLEMENT_netscape_applet_MozillaAppletContext

/*******************************************************************************
 * Native Methods: 
 * These are the signatures of the native methods which you must implement.
 ******************************************************************************/

/*** private native pShowDocument (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
native_netscape_applet_MozillaAppletContext_pShowDocument(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, struct java_lang_String *a, struct java_lang_String *b, struct java_lang_String *c);

/*** private native pShowStatus (Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
native_netscape_applet_MozillaAppletContext_pShowStatus(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, struct java_lang_String *a);

/*** private native pMochaOnLoad (I)V ***/
extern JRI_PUBLIC_API(void)
native_netscape_applet_MozillaAppletContext_pMochaOnLoad(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, jint a);

/*** static native setConsoleState0 (I)V ***/
extern JRI_PUBLIC_API(void)
native_netscape_applet_MozillaAppletContext_setConsoleState0(JRIEnv* env, struct java_lang_Class* clazz, jint a);

/*******************************************************************************
 * Implementation Field Accessors: 
 * You should only use these from within the native method definitions.
 ******************************************************************************/

#ifdef DEBUG

/*** frameMWContext I ***/
extern JRI_PUBLIC_API(jint)
get_netscape_applet_MozillaAppletContext_frameMWContext(JRIEnv* env, netscape_applet_MozillaAppletContext* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_MozillaAppletContext_frameMWContext(JRIEnv* env, netscape_applet_MozillaAppletContext* obj, jint v);

/*** appletFrames Lnetscape/applet/Mapping; ***/
extern JRI_PUBLIC_API(struct netscape_applet_Mapping *)
get_netscape_applet_MozillaAppletContext_appletFrames(JRIEnv* env, netscape_applet_MozillaAppletContext* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_MozillaAppletContext_appletFrames(JRIEnv* env, netscape_applet_MozillaAppletContext* obj, struct netscape_applet_Mapping * v);

/*** imageCache Ljava/util/Hashtable; ***/
extern JRI_PUBLIC_API(struct java_util_Hashtable *)
get_netscape_applet_MozillaAppletContext_imageCache(JRIEnv* env, netscape_applet_MozillaAppletContext* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_MozillaAppletContext_imageCache(JRIEnv* env, netscape_applet_MozillaAppletContext* obj, struct java_util_Hashtable * v);

/*** audioClipCache Ljava/util/Hashtable; ***/
extern JRI_PUBLIC_API(struct java_util_Hashtable *)
get_netscape_applet_MozillaAppletContext_audioClipCache(JRIEnv* env, netscape_applet_MozillaAppletContext* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_MozillaAppletContext_audioClipCache(JRIEnv* env, netscape_applet_MozillaAppletContext* obj, struct java_util_Hashtable * v);

/*** documentURL Ljava/net/URL; ***/
extern JRI_PUBLIC_API(struct java_net_URL *)
get_netscape_applet_MozillaAppletContext_documentURL(JRIEnv* env, netscape_applet_MozillaAppletContext* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_MozillaAppletContext_documentURL(JRIEnv* env, netscape_applet_MozillaAppletContext* obj, struct java_net_URL * v);

/*** contextID Ljava/lang/Integer; ***/
extern JRI_PUBLIC_API(struct java_lang_Integer *)
get_netscape_applet_MozillaAppletContext_contextID(JRIEnv* env, netscape_applet_MozillaAppletContext* obj);
extern JRI_PUBLIC_API(void)
set_netscape_applet_MozillaAppletContext_contextID(JRIEnv* env, netscape_applet_MozillaAppletContext* obj, struct java_lang_Integer * v);

/*** static console Lnetscape/applet/Console; ***/
extern JRI_PUBLIC_API(struct netscape_applet_Console *)
get_netscape_applet_MozillaAppletContext_console(JRIEnv* env, struct java_lang_Class* clazz);
extern JRI_PUBLIC_API(void)
set_netscape_applet_MozillaAppletContext_console(JRIEnv* env, struct java_lang_Class* clazz, struct netscape_applet_Console * v);

/*** static totalApplets I ***/
extern JRI_PUBLIC_API(jint)
get_netscape_applet_MozillaAppletContext_totalApplets(JRIEnv* env, struct java_lang_Class* clazz);
extern JRI_PUBLIC_API(void)
set_netscape_applet_MozillaAppletContext_totalApplets(JRIEnv* env, struct java_lang_Class* clazz, jint v);

/*** static trimThreshold I ***/
extern JRI_PUBLIC_API(jint)
get_netscape_applet_MozillaAppletContext_trimThreshold(JRIEnv* env, struct java_lang_Class* clazz);
extern JRI_PUBLIC_API(void)
set_netscape_applet_MozillaAppletContext_trimThreshold(JRIEnv* env, struct java_lang_Class* clazz, jint v);

/*** static noisyTrimming Z ***/
extern JRI_PUBLIC_API(jbool)
get_netscape_applet_MozillaAppletContext_noisyTrimming(JRIEnv* env, struct java_lang_Class* clazz);
extern JRI_PUBLIC_API(void)
set_netscape_applet_MozillaAppletContext_noisyTrimming(JRIEnv* env, struct java_lang_Class* clazz, jbool v);

/*** static appletContexts Lnetscape/applet/Mapping; ***/
extern JRI_PUBLIC_API(struct netscape_applet_Mapping *)
get_netscape_applet_MozillaAppletContext_appletContexts(JRIEnv* env, struct java_lang_Class* clazz);
extern JRI_PUBLIC_API(void)
set_netscape_applet_MozillaAppletContext_appletContexts(JRIEnv* env, struct java_lang_Class* clazz, struct netscape_applet_Mapping * v);

/*** static debug I ***/
extern JRI_PUBLIC_API(jint)
get_netscape_applet_MozillaAppletContext_debug(JRIEnv* env, struct java_lang_Class* clazz);
extern JRI_PUBLIC_API(void)
set_netscape_applet_MozillaAppletContext_debug(JRIEnv* env, struct java_lang_Class* clazz, jint v);

#else /* !DEBUG */

/*** frameMWContext I ***/
#define get_netscape_applet_MozillaAppletContext_frameMWContext(env, obj) \
	(JRI_GetFieldInt(env, obj, fieldID_netscape_applet_MozillaAppletContext_frameMWContext))
#define set_netscape_applet_MozillaAppletContext_frameMWContext(env, obj, v) \
	JRI_SetFieldInt(env, obj, fieldID_netscape_applet_MozillaAppletContext_frameMWContext, v)

/*** appletFrames Lnetscape/applet/Mapping; ***/
#define get_netscape_applet_MozillaAppletContext_appletFrames(env, obj) \
	((struct netscape_applet_Mapping *)JRI_GetField(env, obj, fieldID_netscape_applet_MozillaAppletContext_appletFrames))
#define set_netscape_applet_MozillaAppletContext_appletFrames(env, obj, v) \
	JRI_SetField(env, obj, fieldID_netscape_applet_MozillaAppletContext_appletFrames, v)

/*** imageCache Ljava/util/Hashtable; ***/
#define get_netscape_applet_MozillaAppletContext_imageCache(env, obj) \
	((struct java_util_Hashtable *)JRI_GetField(env, obj, fieldID_netscape_applet_MozillaAppletContext_imageCache))
#define set_netscape_applet_MozillaAppletContext_imageCache(env, obj, v) \
	JRI_SetField(env, obj, fieldID_netscape_applet_MozillaAppletContext_imageCache, v)

/*** audioClipCache Ljava/util/Hashtable; ***/
#define get_netscape_applet_MozillaAppletContext_audioClipCache(env, obj) \
	((struct java_util_Hashtable *)JRI_GetField(env, obj, fieldID_netscape_applet_MozillaAppletContext_audioClipCache))
#define set_netscape_applet_MozillaAppletContext_audioClipCache(env, obj, v) \
	JRI_SetField(env, obj, fieldID_netscape_applet_MozillaAppletContext_audioClipCache, v)

/*** documentURL Ljava/net/URL; ***/
#define get_netscape_applet_MozillaAppletContext_documentURL(env, obj) \
	((struct java_net_URL *)JRI_GetField(env, obj, fieldID_netscape_applet_MozillaAppletContext_documentURL))
#define set_netscape_applet_MozillaAppletContext_documentURL(env, obj, v) \
	JRI_SetField(env, obj, fieldID_netscape_applet_MozillaAppletContext_documentURL, v)

/*** contextID Ljava/lang/Integer; ***/
#define get_netscape_applet_MozillaAppletContext_contextID(env, obj) \
	((struct java_lang_Integer *)JRI_GetField(env, obj, fieldID_netscape_applet_MozillaAppletContext_contextID))
#define set_netscape_applet_MozillaAppletContext_contextID(env, obj, v) \
	JRI_SetField(env, obj, fieldID_netscape_applet_MozillaAppletContext_contextID, v)

/*** static console Lnetscape/applet/Console; ***/
#define get_netscape_applet_MozillaAppletContext_console(env, clazz) \
	((struct netscape_applet_Console *)JRI_GetStaticField(env, clazz, fieldID_netscape_applet_MozillaAppletContext_console))
#define set_netscape_applet_MozillaAppletContext_console(env, clazz, v) \
	JRI_SetStaticField(env, clazz, fieldID_netscape_applet_MozillaAppletContext_console, v)

/*** static totalApplets I ***/
#define get_netscape_applet_MozillaAppletContext_totalApplets(env, clazz) \
	(JRI_GetStaticFieldInt(env, clazz, fieldID_netscape_applet_MozillaAppletContext_totalApplets))
#define set_netscape_applet_MozillaAppletContext_totalApplets(env, clazz, v) \
	JRI_SetStaticFieldInt(env, clazz, fieldID_netscape_applet_MozillaAppletContext_totalApplets, v)

/*** static trimThreshold I ***/
#define get_netscape_applet_MozillaAppletContext_trimThreshold(env, clazz) \
	(JRI_GetStaticFieldInt(env, clazz, fieldID_netscape_applet_MozillaAppletContext_trimThreshold))
#define set_netscape_applet_MozillaAppletContext_trimThreshold(env, clazz, v) \
	JRI_SetStaticFieldInt(env, clazz, fieldID_netscape_applet_MozillaAppletContext_trimThreshold, v)

/*** static noisyTrimming Z ***/
#define get_netscape_applet_MozillaAppletContext_noisyTrimming(env, clazz) \
	(JRI_GetStaticFieldBoolean(env, clazz, fieldID_netscape_applet_MozillaAppletContext_noisyTrimming))
#define set_netscape_applet_MozillaAppletContext_noisyTrimming(env, clazz, v) \
	JRI_SetStaticFieldBoolean(env, clazz, fieldID_netscape_applet_MozillaAppletContext_noisyTrimming, v)

/*** static appletContexts Lnetscape/applet/Mapping; ***/
#define get_netscape_applet_MozillaAppletContext_appletContexts(env, clazz) \
	((struct netscape_applet_Mapping *)JRI_GetStaticField(env, clazz, fieldID_netscape_applet_MozillaAppletContext_appletContexts))
#define set_netscape_applet_MozillaAppletContext_appletContexts(env, clazz, v) \
	JRI_SetStaticField(env, clazz, fieldID_netscape_applet_MozillaAppletContext_appletContexts, v)

/*** static debug I ***/
#define get_netscape_applet_MozillaAppletContext_debug(env, clazz) \
	(JRI_GetStaticFieldInt(env, clazz, fieldID_netscape_applet_MozillaAppletContext_debug))
#define set_netscape_applet_MozillaAppletContext_debug(env, clazz, v) \
	JRI_SetStaticFieldInt(env, clazz, fieldID_netscape_applet_MozillaAppletContext_debug, v)

#endif /* !DEBUG*/

extern JRIFieldID FAR fieldID_netscape_applet_MozillaAppletContext_frameMWContext;
#define name_netscape_applet_MozillaAppletContext_frameMWContext	"frameMWContext"
#define sig_netscape_applet_MozillaAppletContext_frameMWContext 	"I"
#define use_netscape_applet_MozillaAppletContext_frameMWContext(env, clazz)	\
	(fieldID_netscape_applet_MozillaAppletContext_frameMWContext =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_frameMWContext,	\
			sig_netscape_applet_MozillaAppletContext_frameMWContext))
#define unuse_netscape_applet_MozillaAppletContext_frameMWContext(env, clazz)	\
		(fieldID_netscape_applet_MozillaAppletContext_frameMWContext = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_MozillaAppletContext_appletFrames;
#define name_netscape_applet_MozillaAppletContext_appletFrames	"appletFrames"
#define sig_netscape_applet_MozillaAppletContext_appletFrames 	"Lnetscape/applet/Mapping;"
#define use_netscape_applet_MozillaAppletContext_appletFrames(env, clazz)	\
	(fieldID_netscape_applet_MozillaAppletContext_appletFrames =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_appletFrames,	\
			sig_netscape_applet_MozillaAppletContext_appletFrames))
#define unuse_netscape_applet_MozillaAppletContext_appletFrames(env, clazz)	\
		(fieldID_netscape_applet_MozillaAppletContext_appletFrames = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_MozillaAppletContext_imageCache;
#define name_netscape_applet_MozillaAppletContext_imageCache	"imageCache"
#define sig_netscape_applet_MozillaAppletContext_imageCache 	"Ljava/util/Hashtable;"
#define use_netscape_applet_MozillaAppletContext_imageCache(env, clazz)	\
	(fieldID_netscape_applet_MozillaAppletContext_imageCache =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_imageCache,	\
			sig_netscape_applet_MozillaAppletContext_imageCache))
#define unuse_netscape_applet_MozillaAppletContext_imageCache(env, clazz)	\
		(fieldID_netscape_applet_MozillaAppletContext_imageCache = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_MozillaAppletContext_audioClipCache;
#define name_netscape_applet_MozillaAppletContext_audioClipCache	"audioClipCache"
#define sig_netscape_applet_MozillaAppletContext_audioClipCache 	"Ljava/util/Hashtable;"
#define use_netscape_applet_MozillaAppletContext_audioClipCache(env, clazz)	\
	(fieldID_netscape_applet_MozillaAppletContext_audioClipCache =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_audioClipCache,	\
			sig_netscape_applet_MozillaAppletContext_audioClipCache))
#define unuse_netscape_applet_MozillaAppletContext_audioClipCache(env, clazz)	\
		(fieldID_netscape_applet_MozillaAppletContext_audioClipCache = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_MozillaAppletContext_documentURL;
#define name_netscape_applet_MozillaAppletContext_documentURL	"documentURL"
#define sig_netscape_applet_MozillaAppletContext_documentURL 	"Ljava/net/URL;"
#define use_netscape_applet_MozillaAppletContext_documentURL(env, clazz)	\
	(fieldID_netscape_applet_MozillaAppletContext_documentURL =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_documentURL,	\
			sig_netscape_applet_MozillaAppletContext_documentURL))
#define unuse_netscape_applet_MozillaAppletContext_documentURL(env, clazz)	\
		(fieldID_netscape_applet_MozillaAppletContext_documentURL = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_MozillaAppletContext_contextID;
#define name_netscape_applet_MozillaAppletContext_contextID	"contextID"
#define sig_netscape_applet_MozillaAppletContext_contextID 	"Ljava/lang/Integer;"
#define use_netscape_applet_MozillaAppletContext_contextID(env, clazz)	\
	(fieldID_netscape_applet_MozillaAppletContext_contextID =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_contextID,	\
			sig_netscape_applet_MozillaAppletContext_contextID))
#define unuse_netscape_applet_MozillaAppletContext_contextID(env, clazz)	\
		(fieldID_netscape_applet_MozillaAppletContext_contextID = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_MozillaAppletContext_console;
#define name_netscape_applet_MozillaAppletContext_console	"console"
#define sig_netscape_applet_MozillaAppletContext_console 	"Lnetscape/applet/Console;"
#define use_netscape_applet_MozillaAppletContext_console(env, clazz)	\
	(fieldID_netscape_applet_MozillaAppletContext_console =	\
		JRI_GetStaticFieldID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_console,	\
			sig_netscape_applet_MozillaAppletContext_console))
#define unuse_netscape_applet_MozillaAppletContext_console(env, clazz)	\
		(fieldID_netscape_applet_MozillaAppletContext_console = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_MozillaAppletContext_totalApplets;
#define name_netscape_applet_MozillaAppletContext_totalApplets	"totalApplets"
#define sig_netscape_applet_MozillaAppletContext_totalApplets 	"I"
#define use_netscape_applet_MozillaAppletContext_totalApplets(env, clazz)	\
	(fieldID_netscape_applet_MozillaAppletContext_totalApplets =	\
		JRI_GetStaticFieldID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_totalApplets,	\
			sig_netscape_applet_MozillaAppletContext_totalApplets))
#define unuse_netscape_applet_MozillaAppletContext_totalApplets(env, clazz)	\
		(fieldID_netscape_applet_MozillaAppletContext_totalApplets = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_MozillaAppletContext_trimThreshold;
#define name_netscape_applet_MozillaAppletContext_trimThreshold	"trimThreshold"
#define sig_netscape_applet_MozillaAppletContext_trimThreshold 	"I"
#define use_netscape_applet_MozillaAppletContext_trimThreshold(env, clazz)	\
	(fieldID_netscape_applet_MozillaAppletContext_trimThreshold =	\
		JRI_GetStaticFieldID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_trimThreshold,	\
			sig_netscape_applet_MozillaAppletContext_trimThreshold))
#define unuse_netscape_applet_MozillaAppletContext_trimThreshold(env, clazz)	\
		(fieldID_netscape_applet_MozillaAppletContext_trimThreshold = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_MozillaAppletContext_noisyTrimming;
#define name_netscape_applet_MozillaAppletContext_noisyTrimming	"noisyTrimming"
#define sig_netscape_applet_MozillaAppletContext_noisyTrimming 	"Z"
#define use_netscape_applet_MozillaAppletContext_noisyTrimming(env, clazz)	\
	(fieldID_netscape_applet_MozillaAppletContext_noisyTrimming =	\
		JRI_GetStaticFieldID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_noisyTrimming,	\
			sig_netscape_applet_MozillaAppletContext_noisyTrimming))
#define unuse_netscape_applet_MozillaAppletContext_noisyTrimming(env, clazz)	\
		(fieldID_netscape_applet_MozillaAppletContext_noisyTrimming = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_MozillaAppletContext_appletContexts;
#define name_netscape_applet_MozillaAppletContext_appletContexts	"appletContexts"
#define sig_netscape_applet_MozillaAppletContext_appletContexts 	"Lnetscape/applet/Mapping;"
#define use_netscape_applet_MozillaAppletContext_appletContexts(env, clazz)	\
	(fieldID_netscape_applet_MozillaAppletContext_appletContexts =	\
		JRI_GetStaticFieldID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_appletContexts,	\
			sig_netscape_applet_MozillaAppletContext_appletContexts))
#define unuse_netscape_applet_MozillaAppletContext_appletContexts(env, clazz)	\
		(fieldID_netscape_applet_MozillaAppletContext_appletContexts = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_applet_MozillaAppletContext_debug;
#define name_netscape_applet_MozillaAppletContext_debug	"debug"
#define sig_netscape_applet_MozillaAppletContext_debug 	"I"
#define use_netscape_applet_MozillaAppletContext_debug(env, clazz)	\
	(fieldID_netscape_applet_MozillaAppletContext_debug =	\
		JRI_GetStaticFieldID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_debug,	\
			sig_netscape_applet_MozillaAppletContext_debug))
#define unuse_netscape_applet_MozillaAppletContext_debug(env, clazz)	\
		(fieldID_netscape_applet_MozillaAppletContext_debug = JRIUninitialized)

/*******************************************************************************
 * Implementation Methods: 
 * You should only use these from within the native method definitions.
 ******************************************************************************/

#ifdef DEBUG

/*** <init> (Ljava/lang/Integer;)V ***/
extern JRI_PUBLIC_API(struct netscape_applet_MozillaAppletContext*)
netscape_applet_MozillaAppletContext_new(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_Integer *a);

/*** static indent (Ljava/io/PrintStream;I)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_indent(JRIEnv* env, struct java_lang_Class* clazz, struct java_io_PrintStream *a, jint b);

/*** dumpState (Ljava/io/PrintStream;I)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_dumpState(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, struct java_io_PrintStream *a, jint b);

/*** destroy ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_destroy(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self);

/*** private native pShowDocument (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_pShowDocument(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, struct java_lang_String *a, struct java_lang_String *b, struct java_lang_String *c);

/*** private native pShowStatus (Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_pShowStatus(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, struct java_lang_String *a);

/*** private native pMochaOnLoad (I)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_pMochaOnLoad(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, jint a);

/*** static lookupAudioClip (Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;)Ljava/applet/AudioClip; ***/
extern JRI_PUBLIC_API(struct java_applet_AudioClip *)
netscape_applet_MozillaAppletContext_lookupAudioClip(JRIEnv* env, struct java_lang_Class* clazz, struct netscape_applet_MozillaAppletContext *a, struct java_net_URL *b);

/*** static lookupImage (Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;)Ljava/awt/Image; ***/
extern JRI_PUBLIC_API(struct java_awt_Image *)
netscape_applet_MozillaAppletContext_lookupImage(JRIEnv* env, struct java_lang_Class* clazz, struct netscape_applet_MozillaAppletContext *a, struct java_net_URL *b);

/*** initApplet (ILjava/lang/String;Ljava/util/Hashtable;)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_initApplet(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, jint a, struct java_lang_String *b, struct java_util_Hashtable *c);

/*** getAppletFrame (Ljava/lang/Integer;)Lnetscape/applet/EmbeddedAppletFrame; ***/
extern JRI_PUBLIC_API(struct netscape_applet_EmbeddedAppletFrame *)
netscape_applet_MozillaAppletContext_getAppletFrame(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, struct java_lang_Integer *a);

/*** startApplet (I)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_startApplet(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, jint a);

/*** stopApplet (I)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_stopApplet(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, jint a);

/*** destroyApplet (Ljava/lang/Integer;)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_destroyApplet(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, struct java_lang_Integer *a);

/*** iconifyApplets ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_iconifyApplets(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self);

/*** uniconifyApplets ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_uniconifyApplets(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self);

/*** reflectApplet (I)Ljava/lang/Object; ***/
extern JRI_PUBLIC_API(struct java_lang_Object *)
netscape_applet_MozillaAppletContext_reflectApplet(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self, jint a);

/*** destroyApplets ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_destroyApplets(JRIEnv* env, struct netscape_applet_MozillaAppletContext* self);

/*** static init ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_init(JRIEnv* env, struct java_lang_Class* clazz);

/*** static setConsoleState (I)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_setConsoleState(JRIEnv* env, struct java_lang_Class* clazz, jint a);

/*** static native setConsoleState0 (I)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_setConsoleState0(JRIEnv* env, struct java_lang_Class* clazz, jint a);

/*** static showConsole ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_showConsole(JRIEnv* env, struct java_lang_Class* clazz);

/*** static hideConsole ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_hideConsole(JRIEnv* env, struct java_lang_Class* clazz);

/*** static trimApplets (IZ)I ***/
extern JRI_PUBLIC_API(jint)
netscape_applet_MozillaAppletContext_trimApplets(JRIEnv* env, struct java_lang_Class* clazz, jint a, jbool b);

/*** static trimApplets1 (IZ)I ***/
extern JRI_PUBLIC_API(jint)
netscape_applet_MozillaAppletContext_trimApplets1(JRIEnv* env, struct java_lang_Class* clazz, jint a, jbool b);

/*** static trimApplets ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_trimApplets_1(JRIEnv* env, struct java_lang_Class* clazz);

/*** static getAppletContext (I)Lnetscape/applet/MozillaAppletContext; ***/
extern JRI_PUBLIC_API(struct netscape_applet_MozillaAppletContext *)
netscape_applet_MozillaAppletContext_getAppletContext(JRIEnv* env, struct java_lang_Class* clazz, jint a);

/*** static ensureAppletContext (I)Lnetscape/applet/MozillaAppletContext; ***/
extern JRI_PUBLIC_API(struct netscape_applet_MozillaAppletContext *)
netscape_applet_MozillaAppletContext_ensureAppletContext(JRIEnv* env, struct java_lang_Class* clazz, jint a);

/*** static initApplet (IIII[Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_initApplet_1(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c, jint d, jstringArray e);

/*** static startApplet (III)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_startApplet_1(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b, jint c);

/*** static stopApplet (II)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_stopApplet_1(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b);

/*** static destroyApplet (II)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_destroyApplet_1(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b);

/*** static reflectApplet (II)Ljava/lang/Object; ***/
extern JRI_PUBLIC_API(struct java_lang_Object *)
netscape_applet_MozillaAppletContext_reflectApplet_1(JRIEnv* env, struct java_lang_Class* clazz, jint a, jint b);

/*** static iconifyApplets (I)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_iconifyApplets_1(JRIEnv* env, struct java_lang_Class* clazz, jint a);

/*** static uniconifyApplets (I)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_uniconifyApplets_1(JRIEnv* env, struct java_lang_Class* clazz, jint a);

/*** static destroyApplets (I)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_destroyApplets_1(JRIEnv* env, struct java_lang_Class* clazz, jint a);

/*** static destroyAll ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_destroyAll(JRIEnv* env, struct java_lang_Class* clazz);

/*** static dumpState (Ljava/io/PrintStream;)V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext_dumpState_1(JRIEnv* env, struct java_lang_Class* clazz, struct java_io_PrintStream *a);

/*** static <clinit> ()V ***/
extern JRI_PUBLIC_API(void)
netscape_applet_MozillaAppletContext__0003cclinit_0003e(JRIEnv* env, struct java_lang_Class* clazz);

#else /* !DEBUG */

/*** <init> (Ljava/lang/Integer;)V ***/
#define netscape_applet_MozillaAppletContext_new(env, clazz, a)	\
	((struct netscape_applet_MozillaAppletContext*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_netscape_applet_MozillaAppletContext_new, a))

/*** static indent (Ljava/io/PrintStream;I)V ***/
#define netscape_applet_MozillaAppletContext_indent(env, clazz, a, b) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_indent, a, b))

/*** dumpState (Ljava/io/PrintStream;I)V ***/
#define netscape_applet_MozillaAppletContext_dumpState(env, obj, a, b) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_dumpState, a, b))

/*** destroy ()V ***/
#define netscape_applet_MozillaAppletContext_destroy(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_destroy))

/*** private native pShowDocument (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V ***/
#define netscape_applet_MozillaAppletContext_pShowDocument(env, obj, a, b, c) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_pShowDocument, a, b, c))

/*** private native pShowStatus (Ljava/lang/String;)V ***/
#define netscape_applet_MozillaAppletContext_pShowStatus(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_pShowStatus, a))

/*** private native pMochaOnLoad (I)V ***/
#define netscape_applet_MozillaAppletContext_pMochaOnLoad(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_pMochaOnLoad, a))

/*** static lookupAudioClip (Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;)Ljava/applet/AudioClip; ***/
#define netscape_applet_MozillaAppletContext_lookupAudioClip(env, clazz, a, b) \
	((struct java_applet_AudioClip *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_lookupAudioClip, a, b))

/*** static lookupImage (Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;)Ljava/awt/Image; ***/
#define netscape_applet_MozillaAppletContext_lookupImage(env, clazz, a, b) \
	((struct java_awt_Image *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_lookupImage, a, b))

/*** initApplet (ILjava/lang/String;Ljava/util/Hashtable;)V ***/
#define netscape_applet_MozillaAppletContext_initApplet(env, obj, a, b, c) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_initApplet, a, b, c))

/*** getAppletFrame (Ljava/lang/Integer;)Lnetscape/applet/EmbeddedAppletFrame; ***/
#define netscape_applet_MozillaAppletContext_getAppletFrame(env, obj, a) \
	((struct netscape_applet_EmbeddedAppletFrame *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_getAppletFrame, a))

/*** startApplet (I)V ***/
#define netscape_applet_MozillaAppletContext_startApplet(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_startApplet, a))

/*** stopApplet (I)V ***/
#define netscape_applet_MozillaAppletContext_stopApplet(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_stopApplet, a))

/*** destroyApplet (Ljava/lang/Integer;)V ***/
#define netscape_applet_MozillaAppletContext_destroyApplet(env, obj, a) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_destroyApplet, a))

/*** iconifyApplets ()V ***/
#define netscape_applet_MozillaAppletContext_iconifyApplets(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_iconifyApplets))

/*** uniconifyApplets ()V ***/
#define netscape_applet_MozillaAppletContext_uniconifyApplets(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_uniconifyApplets))

/*** reflectApplet (I)Ljava/lang/Object; ***/
#define netscape_applet_MozillaAppletContext_reflectApplet(env, obj, a) \
	((struct java_lang_Object *)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_reflectApplet, a))

/*** destroyApplets ()V ***/
#define netscape_applet_MozillaAppletContext_destroyApplets(env, obj) \
	((void)JRI_CallMethod(env)(env, JRI_CallMethod_op, obj, methodID_netscape_applet_MozillaAppletContext_destroyApplets))

/*** static init ()V ***/
#define netscape_applet_MozillaAppletContext_init(env, clazz) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_init))

/*** static setConsoleState (I)V ***/
#define netscape_applet_MozillaAppletContext_setConsoleState(env, clazz, a) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_setConsoleState, a))

/*** static native setConsoleState0 (I)V ***/
#define netscape_applet_MozillaAppletContext_setConsoleState0(env, clazz, a) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_setConsoleState0, a))

/*** static showConsole ()V ***/
#define netscape_applet_MozillaAppletContext_showConsole(env, clazz) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_showConsole))

/*** static hideConsole ()V ***/
#define netscape_applet_MozillaAppletContext_hideConsole(env, clazz) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_hideConsole))

/*** static trimApplets (IZ)I ***/
#define netscape_applet_MozillaAppletContext_trimApplets(env, clazz, a, b) \
	((jint)JRI_CallStaticMethodInt(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_trimApplets, a, b))

/*** static trimApplets1 (IZ)I ***/
#define netscape_applet_MozillaAppletContext_trimApplets1(env, clazz, a, b) \
	((jint)JRI_CallStaticMethodInt(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_trimApplets1, a, b))

/*** static trimApplets ()V ***/
#define netscape_applet_MozillaAppletContext_trimApplets_1(env, clazz) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_trimApplets_1))

/*** static getAppletContext (I)Lnetscape/applet/MozillaAppletContext; ***/
#define netscape_applet_MozillaAppletContext_getAppletContext(env, clazz, a) \
	((struct netscape_applet_MozillaAppletContext *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_getAppletContext, a))

/*** static ensureAppletContext (I)Lnetscape/applet/MozillaAppletContext; ***/
#define netscape_applet_MozillaAppletContext_ensureAppletContext(env, clazz, a) \
	((struct netscape_applet_MozillaAppletContext *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_ensureAppletContext, a))

/*** static initApplet (IIII[Ljava/lang/String;)V ***/
#define netscape_applet_MozillaAppletContext_initApplet_1(env, clazz, a, b, c, d, e) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_initApplet_1, a, b, c, d, e))

/*** static startApplet (III)V ***/
#define netscape_applet_MozillaAppletContext_startApplet_1(env, clazz, a, b, c) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_startApplet_1, a, b, c))

/*** static stopApplet (II)V ***/
#define netscape_applet_MozillaAppletContext_stopApplet_1(env, clazz, a, b) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_stopApplet_1, a, b))

/*** static destroyApplet (II)V ***/
#define netscape_applet_MozillaAppletContext_destroyApplet_1(env, clazz, a, b) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_destroyApplet_1, a, b))

/*** static reflectApplet (II)Ljava/lang/Object; ***/
#define netscape_applet_MozillaAppletContext_reflectApplet_1(env, clazz, a, b) \
	((struct java_lang_Object *)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_reflectApplet_1, a, b))

/*** static iconifyApplets (I)V ***/
#define netscape_applet_MozillaAppletContext_iconifyApplets_1(env, clazz, a) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_iconifyApplets_1, a))

/*** static uniconifyApplets (I)V ***/
#define netscape_applet_MozillaAppletContext_uniconifyApplets_1(env, clazz, a) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_uniconifyApplets_1, a))

/*** static destroyApplets (I)V ***/
#define netscape_applet_MozillaAppletContext_destroyApplets_1(env, clazz, a) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_destroyApplets_1, a))

/*** static destroyAll ()V ***/
#define netscape_applet_MozillaAppletContext_destroyAll(env, clazz) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_destroyAll))

/*** static dumpState (Ljava/io/PrintStream;)V ***/
#define netscape_applet_MozillaAppletContext_dumpState_1(env, clazz, a) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext_dumpState_1, a))

/*** static <clinit> ()V ***/
#define netscape_applet_MozillaAppletContext__0003cclinit_0003e(env, clazz) \
	((void)JRI_CallStaticMethod(env)(env, JRI_CallStaticMethod_op, clazz, methodID_netscape_applet_MozillaAppletContext__0003cclinit_0003e))

#endif /* !DEBUG*/

/*** <init> (Ljava/lang/Integer;)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_new;
#define name_netscape_applet_MozillaAppletContext_new	"<init>"
#define sig_netscape_applet_MozillaAppletContext_new 	"(Ljava/lang/Integer;)V"
#define use_netscape_applet_MozillaAppletContext_new(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_new =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_new,	\
			sig_netscape_applet_MozillaAppletContext_new))
#define unuse_netscape_applet_MozillaAppletContext_new(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_new = JRIUninitialized)

/*** static indent (Ljava/io/PrintStream;I)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_indent;
#define name_netscape_applet_MozillaAppletContext_indent	"indent"
#define sig_netscape_applet_MozillaAppletContext_indent 	"(Ljava/io/PrintStream;I)V"
#define use_netscape_applet_MozillaAppletContext_indent(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_indent =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_indent,	\
			sig_netscape_applet_MozillaAppletContext_indent))
#define unuse_netscape_applet_MozillaAppletContext_indent(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_indent = JRIUninitialized)

/*** dumpState (Ljava/io/PrintStream;I)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_dumpState;
#define name_netscape_applet_MozillaAppletContext_dumpState	"dumpState"
#define sig_netscape_applet_MozillaAppletContext_dumpState 	"(Ljava/io/PrintStream;I)V"
#define use_netscape_applet_MozillaAppletContext_dumpState(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_dumpState =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_dumpState,	\
			sig_netscape_applet_MozillaAppletContext_dumpState))
#define unuse_netscape_applet_MozillaAppletContext_dumpState(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_dumpState = JRIUninitialized)

/*** destroy ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_destroy;
#define name_netscape_applet_MozillaAppletContext_destroy	"destroy"
#define sig_netscape_applet_MozillaAppletContext_destroy 	"()V"
#define use_netscape_applet_MozillaAppletContext_destroy(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_destroy =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_destroy,	\
			sig_netscape_applet_MozillaAppletContext_destroy))
#define unuse_netscape_applet_MozillaAppletContext_destroy(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_destroy = JRIUninitialized)

/*** private native pShowDocument (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_pShowDocument;
#define name_netscape_applet_MozillaAppletContext_pShowDocument	"pShowDocument"
#define sig_netscape_applet_MozillaAppletContext_pShowDocument 	"(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V"
#define use_netscape_applet_MozillaAppletContext_pShowDocument(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_pShowDocument =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_pShowDocument,	\
			sig_netscape_applet_MozillaAppletContext_pShowDocument))
#define unuse_netscape_applet_MozillaAppletContext_pShowDocument(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_pShowDocument = JRIUninitialized)

/*** private native pShowStatus (Ljava/lang/String;)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_pShowStatus;
#define name_netscape_applet_MozillaAppletContext_pShowStatus	"pShowStatus"
#define sig_netscape_applet_MozillaAppletContext_pShowStatus 	"(Ljava/lang/String;)V"
#define use_netscape_applet_MozillaAppletContext_pShowStatus(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_pShowStatus =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_pShowStatus,	\
			sig_netscape_applet_MozillaAppletContext_pShowStatus))
#define unuse_netscape_applet_MozillaAppletContext_pShowStatus(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_pShowStatus = JRIUninitialized)

/*** private native pMochaOnLoad (I)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_pMochaOnLoad;
#define name_netscape_applet_MozillaAppletContext_pMochaOnLoad	"pMochaOnLoad"
#define sig_netscape_applet_MozillaAppletContext_pMochaOnLoad 	"(I)V"
#define use_netscape_applet_MozillaAppletContext_pMochaOnLoad(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_pMochaOnLoad =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_pMochaOnLoad,	\
			sig_netscape_applet_MozillaAppletContext_pMochaOnLoad))
#define unuse_netscape_applet_MozillaAppletContext_pMochaOnLoad(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_pMochaOnLoad = JRIUninitialized)

/*** static lookupAudioClip (Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;)Ljava/applet/AudioClip; ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_lookupAudioClip;
#define name_netscape_applet_MozillaAppletContext_lookupAudioClip	"lookupAudioClip"
#define sig_netscape_applet_MozillaAppletContext_lookupAudioClip 	"(Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;)Ljava/applet/AudioClip;"
#define use_netscape_applet_MozillaAppletContext_lookupAudioClip(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_lookupAudioClip =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_lookupAudioClip,	\
			sig_netscape_applet_MozillaAppletContext_lookupAudioClip))
#define unuse_netscape_applet_MozillaAppletContext_lookupAudioClip(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_lookupAudioClip = JRIUninitialized)

/*** static lookupImage (Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;)Ljava/awt/Image; ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_lookupImage;
#define name_netscape_applet_MozillaAppletContext_lookupImage	"lookupImage"
#define sig_netscape_applet_MozillaAppletContext_lookupImage 	"(Lnetscape/applet/MozillaAppletContext;Ljava/net/URL;)Ljava/awt/Image;"
#define use_netscape_applet_MozillaAppletContext_lookupImage(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_lookupImage =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_lookupImage,	\
			sig_netscape_applet_MozillaAppletContext_lookupImage))
#define unuse_netscape_applet_MozillaAppletContext_lookupImage(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_lookupImage = JRIUninitialized)

/*** initApplet (ILjava/lang/String;Ljava/util/Hashtable;)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_initApplet;
#define name_netscape_applet_MozillaAppletContext_initApplet	"initApplet"
#define sig_netscape_applet_MozillaAppletContext_initApplet 	"(ILjava/lang/String;Ljava/util/Hashtable;)V"
#define use_netscape_applet_MozillaAppletContext_initApplet(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_initApplet =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_initApplet,	\
			sig_netscape_applet_MozillaAppletContext_initApplet))
#define unuse_netscape_applet_MozillaAppletContext_initApplet(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_initApplet = JRIUninitialized)

/*** getAppletFrame (Ljava/lang/Integer;)Lnetscape/applet/EmbeddedAppletFrame; ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_getAppletFrame;
#define name_netscape_applet_MozillaAppletContext_getAppletFrame	"getAppletFrame"
#define sig_netscape_applet_MozillaAppletContext_getAppletFrame 	"(Ljava/lang/Integer;)Lnetscape/applet/EmbeddedAppletFrame;"
#define use_netscape_applet_MozillaAppletContext_getAppletFrame(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_getAppletFrame =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_getAppletFrame,	\
			sig_netscape_applet_MozillaAppletContext_getAppletFrame))
#define unuse_netscape_applet_MozillaAppletContext_getAppletFrame(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_getAppletFrame = JRIUninitialized)

/*** startApplet (I)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_startApplet;
#define name_netscape_applet_MozillaAppletContext_startApplet	"startApplet"
#define sig_netscape_applet_MozillaAppletContext_startApplet 	"(I)V"
#define use_netscape_applet_MozillaAppletContext_startApplet(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_startApplet =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_startApplet,	\
			sig_netscape_applet_MozillaAppletContext_startApplet))
#define unuse_netscape_applet_MozillaAppletContext_startApplet(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_startApplet = JRIUninitialized)

/*** stopApplet (I)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_stopApplet;
#define name_netscape_applet_MozillaAppletContext_stopApplet	"stopApplet"
#define sig_netscape_applet_MozillaAppletContext_stopApplet 	"(I)V"
#define use_netscape_applet_MozillaAppletContext_stopApplet(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_stopApplet =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_stopApplet,	\
			sig_netscape_applet_MozillaAppletContext_stopApplet))
#define unuse_netscape_applet_MozillaAppletContext_stopApplet(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_stopApplet = JRIUninitialized)

/*** destroyApplet (Ljava/lang/Integer;)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_destroyApplet;
#define name_netscape_applet_MozillaAppletContext_destroyApplet	"destroyApplet"
#define sig_netscape_applet_MozillaAppletContext_destroyApplet 	"(Ljava/lang/Integer;)V"
#define use_netscape_applet_MozillaAppletContext_destroyApplet(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_destroyApplet =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_destroyApplet,	\
			sig_netscape_applet_MozillaAppletContext_destroyApplet))
#define unuse_netscape_applet_MozillaAppletContext_destroyApplet(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_destroyApplet = JRIUninitialized)

/*** iconifyApplets ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_iconifyApplets;
#define name_netscape_applet_MozillaAppletContext_iconifyApplets	"iconifyApplets"
#define sig_netscape_applet_MozillaAppletContext_iconifyApplets 	"()V"
#define use_netscape_applet_MozillaAppletContext_iconifyApplets(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_iconifyApplets =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_iconifyApplets,	\
			sig_netscape_applet_MozillaAppletContext_iconifyApplets))
#define unuse_netscape_applet_MozillaAppletContext_iconifyApplets(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_iconifyApplets = JRIUninitialized)

/*** uniconifyApplets ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_uniconifyApplets;
#define name_netscape_applet_MozillaAppletContext_uniconifyApplets	"uniconifyApplets"
#define sig_netscape_applet_MozillaAppletContext_uniconifyApplets 	"()V"
#define use_netscape_applet_MozillaAppletContext_uniconifyApplets(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_uniconifyApplets =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_uniconifyApplets,	\
			sig_netscape_applet_MozillaAppletContext_uniconifyApplets))
#define unuse_netscape_applet_MozillaAppletContext_uniconifyApplets(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_uniconifyApplets = JRIUninitialized)

/*** reflectApplet (I)Ljava/lang/Object; ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_reflectApplet;
#define name_netscape_applet_MozillaAppletContext_reflectApplet	"reflectApplet"
#define sig_netscape_applet_MozillaAppletContext_reflectApplet 	"(I)Ljava/lang/Object;"
#define use_netscape_applet_MozillaAppletContext_reflectApplet(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_reflectApplet =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_reflectApplet,	\
			sig_netscape_applet_MozillaAppletContext_reflectApplet))
#define unuse_netscape_applet_MozillaAppletContext_reflectApplet(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_reflectApplet = JRIUninitialized)

/*** destroyApplets ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_destroyApplets;
#define name_netscape_applet_MozillaAppletContext_destroyApplets	"destroyApplets"
#define sig_netscape_applet_MozillaAppletContext_destroyApplets 	"()V"
#define use_netscape_applet_MozillaAppletContext_destroyApplets(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_destroyApplets =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_destroyApplets,	\
			sig_netscape_applet_MozillaAppletContext_destroyApplets))
#define unuse_netscape_applet_MozillaAppletContext_destroyApplets(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_destroyApplets = JRIUninitialized)

/*** static init ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_init;
#define name_netscape_applet_MozillaAppletContext_init	"init"
#define sig_netscape_applet_MozillaAppletContext_init 	"()V"
#define use_netscape_applet_MozillaAppletContext_init(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_init =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_init,	\
			sig_netscape_applet_MozillaAppletContext_init))
#define unuse_netscape_applet_MozillaAppletContext_init(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_init = JRIUninitialized)

/*** static setConsoleState (I)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_setConsoleState;
#define name_netscape_applet_MozillaAppletContext_setConsoleState	"setConsoleState"
#define sig_netscape_applet_MozillaAppletContext_setConsoleState 	"(I)V"
#define use_netscape_applet_MozillaAppletContext_setConsoleState(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_setConsoleState =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_setConsoleState,	\
			sig_netscape_applet_MozillaAppletContext_setConsoleState))
#define unuse_netscape_applet_MozillaAppletContext_setConsoleState(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_setConsoleState = JRIUninitialized)

/*** static native setConsoleState0 (I)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_setConsoleState0;
#define name_netscape_applet_MozillaAppletContext_setConsoleState0	"setConsoleState0"
#define sig_netscape_applet_MozillaAppletContext_setConsoleState0 	"(I)V"
#define use_netscape_applet_MozillaAppletContext_setConsoleState0(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_setConsoleState0 =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_setConsoleState0,	\
			sig_netscape_applet_MozillaAppletContext_setConsoleState0))
#define unuse_netscape_applet_MozillaAppletContext_setConsoleState0(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_setConsoleState0 = JRIUninitialized)

/*** static showConsole ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_showConsole;
#define name_netscape_applet_MozillaAppletContext_showConsole	"showConsole"
#define sig_netscape_applet_MozillaAppletContext_showConsole 	"()V"
#define use_netscape_applet_MozillaAppletContext_showConsole(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_showConsole =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_showConsole,	\
			sig_netscape_applet_MozillaAppletContext_showConsole))
#define unuse_netscape_applet_MozillaAppletContext_showConsole(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_showConsole = JRIUninitialized)

/*** static hideConsole ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_hideConsole;
#define name_netscape_applet_MozillaAppletContext_hideConsole	"hideConsole"
#define sig_netscape_applet_MozillaAppletContext_hideConsole 	"()V"
#define use_netscape_applet_MozillaAppletContext_hideConsole(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_hideConsole =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_hideConsole,	\
			sig_netscape_applet_MozillaAppletContext_hideConsole))
#define unuse_netscape_applet_MozillaAppletContext_hideConsole(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_hideConsole = JRIUninitialized)

/*** static trimApplets (IZ)I ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_trimApplets;
#define name_netscape_applet_MozillaAppletContext_trimApplets	"trimApplets"
#define sig_netscape_applet_MozillaAppletContext_trimApplets 	"(IZ)I"
#define use_netscape_applet_MozillaAppletContext_trimApplets(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_trimApplets =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_trimApplets,	\
			sig_netscape_applet_MozillaAppletContext_trimApplets))
#define unuse_netscape_applet_MozillaAppletContext_trimApplets(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_trimApplets = JRIUninitialized)

/*** static trimApplets1 (IZ)I ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_trimApplets1;
#define name_netscape_applet_MozillaAppletContext_trimApplets1	"trimApplets1"
#define sig_netscape_applet_MozillaAppletContext_trimApplets1 	"(IZ)I"
#define use_netscape_applet_MozillaAppletContext_trimApplets1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_trimApplets1 =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_trimApplets1,	\
			sig_netscape_applet_MozillaAppletContext_trimApplets1))
#define unuse_netscape_applet_MozillaAppletContext_trimApplets1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_trimApplets1 = JRIUninitialized)

/*** static trimApplets ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_trimApplets_1;
#define name_netscape_applet_MozillaAppletContext_trimApplets_1	"trimApplets"
#define sig_netscape_applet_MozillaAppletContext_trimApplets_1 	"()V"
#define use_netscape_applet_MozillaAppletContext_trimApplets_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_trimApplets_1 =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_trimApplets_1,	\
			sig_netscape_applet_MozillaAppletContext_trimApplets_1))
#define unuse_netscape_applet_MozillaAppletContext_trimApplets_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_trimApplets_1 = JRIUninitialized)

/*** static getAppletContext (I)Lnetscape/applet/MozillaAppletContext; ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_getAppletContext;
#define name_netscape_applet_MozillaAppletContext_getAppletContext	"getAppletContext"
#define sig_netscape_applet_MozillaAppletContext_getAppletContext 	"(I)Lnetscape/applet/MozillaAppletContext;"
#define use_netscape_applet_MozillaAppletContext_getAppletContext(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_getAppletContext =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_getAppletContext,	\
			sig_netscape_applet_MozillaAppletContext_getAppletContext))
#define unuse_netscape_applet_MozillaAppletContext_getAppletContext(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_getAppletContext = JRIUninitialized)

/*** static ensureAppletContext (I)Lnetscape/applet/MozillaAppletContext; ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_ensureAppletContext;
#define name_netscape_applet_MozillaAppletContext_ensureAppletContext	"ensureAppletContext"
#define sig_netscape_applet_MozillaAppletContext_ensureAppletContext 	"(I)Lnetscape/applet/MozillaAppletContext;"
#define use_netscape_applet_MozillaAppletContext_ensureAppletContext(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_ensureAppletContext =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_ensureAppletContext,	\
			sig_netscape_applet_MozillaAppletContext_ensureAppletContext))
#define unuse_netscape_applet_MozillaAppletContext_ensureAppletContext(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_ensureAppletContext = JRIUninitialized)

/*** static initApplet (IIII[Ljava/lang/String;)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_initApplet_1;
#define name_netscape_applet_MozillaAppletContext_initApplet_1	"initApplet"
#define sig_netscape_applet_MozillaAppletContext_initApplet_1 	"(IIII[Ljava/lang/String;)V"
#define use_netscape_applet_MozillaAppletContext_initApplet_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_initApplet_1 =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_initApplet_1,	\
			sig_netscape_applet_MozillaAppletContext_initApplet_1))
#define unuse_netscape_applet_MozillaAppletContext_initApplet_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_initApplet_1 = JRIUninitialized)

/*** static startApplet (III)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_startApplet_1;
#define name_netscape_applet_MozillaAppletContext_startApplet_1	"startApplet"
#define sig_netscape_applet_MozillaAppletContext_startApplet_1 	"(III)V"
#define use_netscape_applet_MozillaAppletContext_startApplet_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_startApplet_1 =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_startApplet_1,	\
			sig_netscape_applet_MozillaAppletContext_startApplet_1))
#define unuse_netscape_applet_MozillaAppletContext_startApplet_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_startApplet_1 = JRIUninitialized)

/*** static stopApplet (II)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_stopApplet_1;
#define name_netscape_applet_MozillaAppletContext_stopApplet_1	"stopApplet"
#define sig_netscape_applet_MozillaAppletContext_stopApplet_1 	"(II)V"
#define use_netscape_applet_MozillaAppletContext_stopApplet_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_stopApplet_1 =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_stopApplet_1,	\
			sig_netscape_applet_MozillaAppletContext_stopApplet_1))
#define unuse_netscape_applet_MozillaAppletContext_stopApplet_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_stopApplet_1 = JRIUninitialized)

/*** static destroyApplet (II)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_destroyApplet_1;
#define name_netscape_applet_MozillaAppletContext_destroyApplet_1	"destroyApplet"
#define sig_netscape_applet_MozillaAppletContext_destroyApplet_1 	"(II)V"
#define use_netscape_applet_MozillaAppletContext_destroyApplet_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_destroyApplet_1 =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_destroyApplet_1,	\
			sig_netscape_applet_MozillaAppletContext_destroyApplet_1))
#define unuse_netscape_applet_MozillaAppletContext_destroyApplet_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_destroyApplet_1 = JRIUninitialized)

/*** static reflectApplet (II)Ljava/lang/Object; ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_reflectApplet_1;
#define name_netscape_applet_MozillaAppletContext_reflectApplet_1	"reflectApplet"
#define sig_netscape_applet_MozillaAppletContext_reflectApplet_1 	"(II)Ljava/lang/Object;"
#define use_netscape_applet_MozillaAppletContext_reflectApplet_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_reflectApplet_1 =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_reflectApplet_1,	\
			sig_netscape_applet_MozillaAppletContext_reflectApplet_1))
#define unuse_netscape_applet_MozillaAppletContext_reflectApplet_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_reflectApplet_1 = JRIUninitialized)

/*** static iconifyApplets (I)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_iconifyApplets_1;
#define name_netscape_applet_MozillaAppletContext_iconifyApplets_1	"iconifyApplets"
#define sig_netscape_applet_MozillaAppletContext_iconifyApplets_1 	"(I)V"
#define use_netscape_applet_MozillaAppletContext_iconifyApplets_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_iconifyApplets_1 =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_iconifyApplets_1,	\
			sig_netscape_applet_MozillaAppletContext_iconifyApplets_1))
#define unuse_netscape_applet_MozillaAppletContext_iconifyApplets_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_iconifyApplets_1 = JRIUninitialized)

/*** static uniconifyApplets (I)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_uniconifyApplets_1;
#define name_netscape_applet_MozillaAppletContext_uniconifyApplets_1	"uniconifyApplets"
#define sig_netscape_applet_MozillaAppletContext_uniconifyApplets_1 	"(I)V"
#define use_netscape_applet_MozillaAppletContext_uniconifyApplets_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_uniconifyApplets_1 =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_uniconifyApplets_1,	\
			sig_netscape_applet_MozillaAppletContext_uniconifyApplets_1))
#define unuse_netscape_applet_MozillaAppletContext_uniconifyApplets_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_uniconifyApplets_1 = JRIUninitialized)

/*** static destroyApplets (I)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_destroyApplets_1;
#define name_netscape_applet_MozillaAppletContext_destroyApplets_1	"destroyApplets"
#define sig_netscape_applet_MozillaAppletContext_destroyApplets_1 	"(I)V"
#define use_netscape_applet_MozillaAppletContext_destroyApplets_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_destroyApplets_1 =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_destroyApplets_1,	\
			sig_netscape_applet_MozillaAppletContext_destroyApplets_1))
#define unuse_netscape_applet_MozillaAppletContext_destroyApplets_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_destroyApplets_1 = JRIUninitialized)

/*** static destroyAll ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_destroyAll;
#define name_netscape_applet_MozillaAppletContext_destroyAll	"destroyAll"
#define sig_netscape_applet_MozillaAppletContext_destroyAll 	"()V"
#define use_netscape_applet_MozillaAppletContext_destroyAll(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_destroyAll =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_destroyAll,	\
			sig_netscape_applet_MozillaAppletContext_destroyAll))
#define unuse_netscape_applet_MozillaAppletContext_destroyAll(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_destroyAll = JRIUninitialized)

/*** static dumpState (Ljava/io/PrintStream;)V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext_dumpState_1;
#define name_netscape_applet_MozillaAppletContext_dumpState_1	"dumpState"
#define sig_netscape_applet_MozillaAppletContext_dumpState_1 	"(Ljava/io/PrintStream;)V"
#define use_netscape_applet_MozillaAppletContext_dumpState_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_dumpState_1 =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext_dumpState_1,	\
			sig_netscape_applet_MozillaAppletContext_dumpState_1))
#define unuse_netscape_applet_MozillaAppletContext_dumpState_1(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext_dumpState_1 = JRIUninitialized)

/*** static <clinit> ()V ***/
extern JRIMethodID FAR methodID_netscape_applet_MozillaAppletContext__0003cclinit_0003e;
#define name_netscape_applet_MozillaAppletContext__0003cclinit_0003e	"<clinit>"
#define sig_netscape_applet_MozillaAppletContext__0003cclinit_0003e 	"()V"
#define use_netscape_applet_MozillaAppletContext__0003cclinit_0003e(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext__0003cclinit_0003e =	\
		JRI_GetStaticMethodID(env, clazz,	\
			name_netscape_applet_MozillaAppletContext__0003cclinit_0003e,	\
			sig_netscape_applet_MozillaAppletContext__0003cclinit_0003e))
#define unuse_netscape_applet_MozillaAppletContext__0003cclinit_0003e(env, clazz)	\
	(methodID_netscape_applet_MozillaAppletContext__0003cclinit_0003e = JRIUninitialized)

#endif /* IMPLEMENT_netscape_applet_MozillaAppletContext */

#ifdef __cplusplus
} /* extern "C" */

/*******************************************************************************
 * C++ Definitions
 ******************************************************************************/

#include "java_applet_AppletContext.h"
#include "java_lang_Object.h"

struct netscape_applet_MozillaAppletContext : virtual public java_applet_AppletContext, public java_lang_Object {

	static struct java_lang_Class* _use(JRIEnv* env) {
		return use_netscape_applet_MozillaAppletContext(env);
	}

	static void _unuse(JRIEnv* env) {
		unuse_netscape_applet_MozillaAppletContext(env);
	}

	static struct java_lang_Class* _register(JRIEnv* env) {
		return register_netscape_applet_MozillaAppletContext(env);
	}

	static void _unregister(JRIEnv* env) {
		unregister_netscape_applet_MozillaAppletContext(env);
	}

	static struct java_lang_Class* _class(JRIEnv* env) {
		return class_netscape_applet_MozillaAppletContext(env);
	}

	/* Public Methods */
	/*** public getAudioClip (Ljava/net/URL;)Ljava/applet/AudioClip; ***/
	struct java_applet_AudioClip * getAudioClip(JRIEnv* env, struct java_net_URL *a) {
		return netscape_applet_MozillaAppletContext_getAudioClip(env, this, a);
	}

	/*** public getImage (Ljava/net/URL;)Ljava/awt/Image; ***/
	struct java_awt_Image * getImage(JRIEnv* env, struct java_net_URL *a) {
		return netscape_applet_MozillaAppletContext_getImage(env, this, a);
	}

	/*** public getApplet (Ljava/lang/String;)Ljava/applet/Applet; ***/
	struct java_applet_Applet * getApplet(JRIEnv* env, struct java_lang_String *a) {
		return netscape_applet_MozillaAppletContext_getApplet(env, this, a);
	}

	/*** public getApplets ()Ljava/util/Enumeration; ***/
	struct java_util_Enumeration * getApplets(JRIEnv* env) {
		return netscape_applet_MozillaAppletContext_getApplets(env, this);
	}

	/*** public showDocument (Ljava/net/URL;)V ***/
	void showDocument(JRIEnv* env, struct java_net_URL *a) {
		netscape_applet_MozillaAppletContext_showDocument(env, this, a);
	}

	/*** public showDocument (Ljava/net/URL;Ljava/lang/String;)V ***/
	void showDocument(JRIEnv* env, struct java_net_URL *a, struct java_lang_String *b) {
		netscape_applet_MozillaAppletContext_showDocument_1(env, this, a, b);
	}

	/*** public showStatus (Ljava/lang/String;)V ***/
	void showStatus(JRIEnv* env, struct java_lang_String *a) {
		netscape_applet_MozillaAppletContext_showStatus(env, this, a);
	}

	/*** public mochaOnLoad (I)V ***/
	void mochaOnLoad(JRIEnv* env, jint a) {
		netscape_applet_MozillaAppletContext_mochaOnLoad(env, this, a);
	}

#ifdef IMPLEMENT_netscape_applet_MozillaAppletContext

	/* Private Methods */
	/*** private native pShowDocument (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V ***/
	void pShowDocument(JRIEnv* env, struct java_lang_String *a, struct java_lang_String *b, struct java_lang_String *c) {
		netscape_applet_MozillaAppletContext_pShowDocument(env, this, a, b, c);
	}

	/*** private native pShowStatus (Ljava/lang/String;)V ***/
	void pShowStatus(JRIEnv* env, struct java_lang_String *a) {
		netscape_applet_MozillaAppletContext_pShowStatus(env, this, a);
	}

	/*** private native pMochaOnLoad (I)V ***/
	void pMochaOnLoad(JRIEnv* env, jint a) {
		netscape_applet_MozillaAppletContext_pMochaOnLoad(env, this, a);
	}

#endif /* IMPLEMENT_netscape_applet_MozillaAppletContext */
};

#endif /* __cplusplus */

#endif /* Class netscape/applet/MozillaAppletContext */
