/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Header for class netscape/javascript/JSException */

#ifndef _netscape_javascript_JSException_H_
#define _netscape_javascript_JSException_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct java_lang_String;
struct java_lang_Class;

/*******************************************************************************
 * Class netscape/javascript/JSException
 ******************************************************************************/

typedef struct netscape_javascript_JSException netscape_javascript_JSException;

#define classname_netscape_javascript_JSException	"netscape/javascript/JSException"

#define class_netscape_javascript_JSException(env) \
	((struct java_lang_Class*)JRI_FindClass(env, classname_netscape_javascript_JSException))

/*******************************************************************************
 * Public Methods
 ******************************************************************************/

#ifdef DEBUG

/*** public <init> ()V ***/
extern JRI_PUBLIC_API(struct netscape_javascript_JSException*)
netscape_javascript_JSException_new(JRIEnv* env, struct java_lang_Class* clazz);

/*** public <init> (Ljava/lang/String;)V ***/
extern JRI_PUBLIC_API(struct netscape_javascript_JSException*)
netscape_javascript_JSException_new_1(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a);

/*** public <init> (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;I)V ***/
extern JRI_PUBLIC_API(struct netscape_javascript_JSException*)
netscape_javascript_JSException_new_2(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a, struct java_lang_String *b, jint c, struct java_lang_String *d, jint e);

#else /* !DEBUG */

/*** public <init> ()V ***/
#define netscape_javascript_JSException_new(env, clazz)	\
	((struct netscape_javascript_JSException*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_netscape_javascript_JSException_new))

/*** public <init> (Ljava/lang/String;)V ***/
#define netscape_javascript_JSException_new_1(env, clazz, a)	\
	((struct netscape_javascript_JSException*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_netscape_javascript_JSException_new_1, a))

/*** public <init> (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;I)V ***/
#define netscape_javascript_JSException_new_2(env, clazz, a, b, c, d, e)	\
	((struct netscape_javascript_JSException*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_netscape_javascript_JSException_new_2, a, b, c, d, e))

#endif /* !DEBUG*/

/*** public <init> ()V ***/
extern JRIMethodID FAR methodID_netscape_javascript_JSException_new;
#define name_netscape_javascript_JSException_new	"<init>"
#define sig_netscape_javascript_JSException_new 	"()V"
#define use_netscape_javascript_JSException_new(env, clazz)	\
	(methodID_netscape_javascript_JSException_new =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_javascript_JSException_new,	\
			sig_netscape_javascript_JSException_new))
#define unuse_netscape_javascript_JSException_new(env, clazz)	\
	(methodID_netscape_javascript_JSException_new = JRIUninitialized)

/*** public <init> (Ljava/lang/String;)V ***/
extern JRIMethodID FAR methodID_netscape_javascript_JSException_new_1;
#define name_netscape_javascript_JSException_new_1	"<init>"
#define sig_netscape_javascript_JSException_new_1 	"(Ljava/lang/String;)V"
#define use_netscape_javascript_JSException_new_1(env, clazz)	\
	(methodID_netscape_javascript_JSException_new_1 =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_javascript_JSException_new_1,	\
			sig_netscape_javascript_JSException_new_1))
#define unuse_netscape_javascript_JSException_new_1(env, clazz)	\
	(methodID_netscape_javascript_JSException_new_1 = JRIUninitialized)

/*** public <init> (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;I)V ***/
extern JRIMethodID FAR methodID_netscape_javascript_JSException_new_2;
#define name_netscape_javascript_JSException_new_2	"<init>"
#define sig_netscape_javascript_JSException_new_2 	"(Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;I)V"
#define use_netscape_javascript_JSException_new_2(env, clazz)	\
	(methodID_netscape_javascript_JSException_new_2 =	\
		JRI_GetMethodID(env, clazz,	\
			name_netscape_javascript_JSException_new_2,	\
			sig_netscape_javascript_JSException_new_2))
#define unuse_netscape_javascript_JSException_new_2(env, clazz)	\
	(methodID_netscape_javascript_JSException_new_2 = JRIUninitialized)

/*******************************************************************************
 * IMPLEMENTATION SECTION: 
 * Define the IMPLEMENT_netscape_javascript_JSException symbol 
 * if you intend to implement the native methods of this class. This 
 * symbol makes the private and protected methods available. You should 
 * also call the register_netscape_javascript_JSException routine 
 * to make your native methods available.
 ******************************************************************************/

extern JRI_PUBLIC_API(struct java_lang_Class*)
use_netscape_javascript_JSException(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unuse_netscape_javascript_JSException(JRIEnv* env);

extern JRI_PUBLIC_API(struct java_lang_Class*)
register_netscape_javascript_JSException(JRIEnv* env);

extern JRI_PUBLIC_API(void)
unregister_netscape_javascript_JSException(JRIEnv* env);

#ifdef IMPLEMENT_netscape_javascript_JSException

/*******************************************************************************
 * Implementation Field Accessors: 
 * You should only use these from within the native method definitions.
 ******************************************************************************/

#ifdef DEBUG

/*** filename Ljava/lang/String; ***/
extern JRI_PUBLIC_API(struct java_lang_String *)
get_netscape_javascript_JSException_filename(JRIEnv* env, netscape_javascript_JSException* obj);
extern JRI_PUBLIC_API(void)
set_netscape_javascript_JSException_filename(JRIEnv* env, netscape_javascript_JSException* obj, struct java_lang_String * v);

/*** lineno I ***/
extern JRI_PUBLIC_API(jint)
get_netscape_javascript_JSException_lineno(JRIEnv* env, netscape_javascript_JSException* obj);
extern JRI_PUBLIC_API(void)
set_netscape_javascript_JSException_lineno(JRIEnv* env, netscape_javascript_JSException* obj, jint v);

/*** source Ljava/lang/String; ***/
extern JRI_PUBLIC_API(struct java_lang_String *)
get_netscape_javascript_JSException_source(JRIEnv* env, netscape_javascript_JSException* obj);
extern JRI_PUBLIC_API(void)
set_netscape_javascript_JSException_source(JRIEnv* env, netscape_javascript_JSException* obj, struct java_lang_String * v);

/*** tokenIndex I ***/
extern JRI_PUBLIC_API(jint)
get_netscape_javascript_JSException_tokenIndex(JRIEnv* env, netscape_javascript_JSException* obj);
extern JRI_PUBLIC_API(void)
set_netscape_javascript_JSException_tokenIndex(JRIEnv* env, netscape_javascript_JSException* obj, jint v);

#else /* !DEBUG */

/*** filename Ljava/lang/String; ***/
#define get_netscape_javascript_JSException_filename(env, obj) \
	((struct java_lang_String *)JRI_GetField(env, obj, fieldID_netscape_javascript_JSException_filename))
#define set_netscape_javascript_JSException_filename(env, obj, v) \
	JRI_SetField(env, obj, fieldID_netscape_javascript_JSException_filename, v)

/*** lineno I ***/
#define get_netscape_javascript_JSException_lineno(env, obj) \
	(JRI_GetFieldInt(env, obj, fieldID_netscape_javascript_JSException_lineno))
#define set_netscape_javascript_JSException_lineno(env, obj, v) \
	JRI_SetFieldInt(env, obj, fieldID_netscape_javascript_JSException_lineno, v)

/*** source Ljava/lang/String; ***/
#define get_netscape_javascript_JSException_source(env, obj) \
	((struct java_lang_String *)JRI_GetField(env, obj, fieldID_netscape_javascript_JSException_source))
#define set_netscape_javascript_JSException_source(env, obj, v) \
	JRI_SetField(env, obj, fieldID_netscape_javascript_JSException_source, v)

/*** tokenIndex I ***/
#define get_netscape_javascript_JSException_tokenIndex(env, obj) \
	(JRI_GetFieldInt(env, obj, fieldID_netscape_javascript_JSException_tokenIndex))
#define set_netscape_javascript_JSException_tokenIndex(env, obj, v) \
	JRI_SetFieldInt(env, obj, fieldID_netscape_javascript_JSException_tokenIndex, v)

#endif /* !DEBUG*/

extern JRIFieldID FAR fieldID_netscape_javascript_JSException_filename;
#define name_netscape_javascript_JSException_filename	"filename"
#define sig_netscape_javascript_JSException_filename 	"Ljava/lang/String;"
#define use_netscape_javascript_JSException_filename(env, clazz)	\
	(fieldID_netscape_javascript_JSException_filename =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_javascript_JSException_filename,	\
			sig_netscape_javascript_JSException_filename))
#define unuse_netscape_javascript_JSException_filename(env, clazz)	\
		(fieldID_netscape_javascript_JSException_filename = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_javascript_JSException_lineno;
#define name_netscape_javascript_JSException_lineno	"lineno"
#define sig_netscape_javascript_JSException_lineno 	"I"
#define use_netscape_javascript_JSException_lineno(env, clazz)	\
	(fieldID_netscape_javascript_JSException_lineno =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_javascript_JSException_lineno,	\
			sig_netscape_javascript_JSException_lineno))
#define unuse_netscape_javascript_JSException_lineno(env, clazz)	\
		(fieldID_netscape_javascript_JSException_lineno = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_javascript_JSException_source;
#define name_netscape_javascript_JSException_source	"source"
#define sig_netscape_javascript_JSException_source 	"Ljava/lang/String;"
#define use_netscape_javascript_JSException_source(env, clazz)	\
	(fieldID_netscape_javascript_JSException_source =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_javascript_JSException_source,	\
			sig_netscape_javascript_JSException_source))
#define unuse_netscape_javascript_JSException_source(env, clazz)	\
		(fieldID_netscape_javascript_JSException_source = JRIUninitialized)

extern JRIFieldID FAR fieldID_netscape_javascript_JSException_tokenIndex;
#define name_netscape_javascript_JSException_tokenIndex	"tokenIndex"
#define sig_netscape_javascript_JSException_tokenIndex 	"I"
#define use_netscape_javascript_JSException_tokenIndex(env, clazz)	\
	(fieldID_netscape_javascript_JSException_tokenIndex =	\
		JRI_GetFieldID(env, clazz,	\
			name_netscape_javascript_JSException_tokenIndex,	\
			sig_netscape_javascript_JSException_tokenIndex))
#define unuse_netscape_javascript_JSException_tokenIndex(env, clazz)	\
		(fieldID_netscape_javascript_JSException_tokenIndex = JRIUninitialized)

#endif /* IMPLEMENT_netscape_javascript_JSException */

#ifdef __cplusplus
} /* extern "C" */

/*******************************************************************************
 * C++ Definitions
 ******************************************************************************/

#include "java_lang_Exception.h"

struct netscape_javascript_JSException : public java_lang_Exception {

	static struct java_lang_Class* _use(JRIEnv* env) {
		return use_netscape_javascript_JSException(env);
	}

	static void _unuse(JRIEnv* env) {
		unuse_netscape_javascript_JSException(env);
	}

	static struct java_lang_Class* _register(JRIEnv* env) {
		return register_netscape_javascript_JSException(env);
	}

	static void _unregister(JRIEnv* env) {
		unregister_netscape_javascript_JSException(env);
	}

	static struct java_lang_Class* _class(JRIEnv* env) {
		return class_netscape_javascript_JSException(env);
	}

	/* Public Methods */
	/*** public <init> ()V ***/
	static netscape_javascript_JSException* _new(JRIEnv* env, struct java_lang_Class* clazz) {
		return netscape_javascript_JSException_new(env, clazz);
	}

	/*** public <init> (Ljava/lang/String;)V ***/
	static netscape_javascript_JSException* _new(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a) {
		return netscape_javascript_JSException_new_1(env, clazz, a);
	}

	/*** public <init> (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;I)V ***/
	static netscape_javascript_JSException* _new(JRIEnv* env, struct java_lang_Class* clazz, struct java_lang_String *a, struct java_lang_String *b, jint c, struct java_lang_String *d, jint e) {
		return netscape_javascript_JSException_new_2(env, clazz, a, b, c, d, e);
	}

#ifdef IMPLEMENT_netscape_javascript_JSException

#endif /* IMPLEMENT_netscape_javascript_JSException */
};

#endif /* __cplusplus */

#endif /* Class netscape/javascript/JSException */
