/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class s_a_m_MCheckboxMenuItemPeer */

#ifndef _Included_sun_awt_macos_MCheckboxMenuItemPeer
#define _Included_sun_awt_macos_MCheckboxMenuItemPeer
struct Hjava_awt_MenuItem;

typedef struct Classsun_awt_macos_MCheckboxMenuItemPeer {
    /*boolean*/ long isCheckItem;
    struct Hjava_awt_MenuItem *target;
} Classsun_awt_macos_MCheckboxMenuItemPeer;
HandleTo(sun_awt_macos_MCheckboxMenuItemPeer);

#endif
