/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class sun_awt_macos_MButtonPeer */

#ifndef _Included_sun_awt_macos_MButtonPeer
#define _Included_sun_awt_macos_MButtonPeer
struct Hjava_awt_Component;
struct Hjava_awt_Color;

typedef struct Classsun_awt_macos_MButtonPeer {
    struct Hjava_awt_Component *target;
    long pData;
    long pInternationalData;
    long mOwnerPane;
    long mFont;
    long mSize;
    long mStyle;
    struct Hjava_awt_Color *mForeColor;
    struct Hjava_awt_Color *mBackColor;
    /*boolean*/ long mRecalculateClip;
    /*boolean*/ long mIsContainer;
    /*boolean*/ long mIsButton;
    /*boolean*/ long mIsChoice;
    /*boolean*/ long mIsResizableFrame;
    long mObscuredRgn;
    long mClipRgn;
} Classsun_awt_macos_MButtonPeer;
HandleTo(sun_awt_macos_MButtonPeer);

struct Hsun_awt_macos_MComponentPeer;
extern void sun_awt_macos_MButtonPeer_create(struct Hsun_awt_macos_MButtonPeer* self,struct Hsun_awt_macos_MComponentPeer *);
struct Hjava_lang_String;
extern void sun_awt_macos_MButtonPeer_setLabel(struct Hsun_awt_macos_MButtonPeer* self,struct Hjava_lang_String *);
#endif
