/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class sun_awt_macos_MacGraphics */

#ifndef _Included_sun_awt_macos_MacGraphics
#define _Included_sun_awt_macos_MacGraphics
struct Hjava_awt_Color;
struct Hjava_awt_Font;
struct Hsun_awt_image_ImageRepresentation;
struct Hsun_awt_macos_MComponentPeer;

typedef struct Classsun_awt_macos_MacGraphics {
    long pData;
    struct Hjava_awt_Color *foreground;
    struct Hjava_awt_Font *font;
    long originX;
    long originY;
    float scaleX;
    float scaleY;
    struct Hsun_awt_image_ImageRepresentation *imageRepresentation;
    struct Hsun_awt_macos_MComponentPeer *componentPeer;
} Classsun_awt_macos_MacGraphics;
HandleTo(sun_awt_macos_MacGraphics);

extern void sun_awt_macos_MacGraphics_createFromComponent(struct Hsun_awt_macos_MacGraphics* self,struct Hsun_awt_macos_MComponentPeer *);
struct Hsun_awt_macos_MacGraphics;
extern void sun_awt_macos_MacGraphics_createFromGraphics(struct Hsun_awt_macos_MacGraphics* self,struct Hsun_awt_macos_MacGraphics *);
extern void sun_awt_macos_MacGraphics_createFromIRepresentation(struct Hsun_awt_macos_MacGraphics* self,struct Hsun_awt_image_ImageRepresentation *);
extern void sun_awt_macos_MacGraphics_pSetFont(struct Hsun_awt_macos_MacGraphics* self,struct Hjava_awt_Font *);
extern void sun_awt_macos_MacGraphics_pSetForeground(struct Hsun_awt_macos_MacGraphics* self,struct Hjava_awt_Color *);
extern void sun_awt_macos_MacGraphics_pSetScaling(struct Hsun_awt_macos_MacGraphics* self,float,float);
extern void sun_awt_macos_MacGraphics_pSetOrigin(struct Hsun_awt_macos_MacGraphics* self,long,long);
extern void sun_awt_macos_MacGraphics_dispose(struct Hsun_awt_macos_MacGraphics* self);
extern void sun_awt_macos_MacGraphics_setPaintMode(struct Hsun_awt_macos_MacGraphics* self);
extern void sun_awt_macos_MacGraphics_setXORMode(struct Hsun_awt_macos_MacGraphics* self,struct Hjava_awt_Color *);
struct Hjava_awt_Rectangle;
extern void sun_awt_macos_MacGraphics_getClipRect(struct Hsun_awt_macos_MacGraphics* self,struct Hjava_awt_Rectangle *);
extern void sun_awt_macos_MacGraphics_clipRect(struct Hsun_awt_macos_MacGraphics* self,long,long,long,long);
extern void sun_awt_macos_MacGraphics_clearRect(struct Hsun_awt_macos_MacGraphics* self,long,long,long,long);
extern void sun_awt_macos_MacGraphics_fillRect(struct Hsun_awt_macos_MacGraphics* self,long,long,long,long);
extern void sun_awt_macos_MacGraphics_drawRect(struct Hsun_awt_macos_MacGraphics* self,long,long,long,long);
struct Hjava_lang_String;
extern void sun_awt_macos_MacGraphics_drawString(struct Hsun_awt_macos_MacGraphics* self,struct Hjava_lang_String *,long,long);
extern void sun_awt_macos_MacGraphics_drawChars(struct Hsun_awt_macos_MacGraphics* self,HArrayOfChar *,long,long,long,long);
extern void sun_awt_macos_MacGraphics_drawBytes(struct Hsun_awt_macos_MacGraphics* self,HArrayOfByte *,long,long,long,long);
extern long sun_awt_macos_MacGraphics_drawStringWidth(struct Hsun_awt_macos_MacGraphics* self,struct Hjava_lang_String *,long,long);
extern long sun_awt_macos_MacGraphics_drawCharsWidth(struct Hsun_awt_macos_MacGraphics* self,HArrayOfChar *,long,long,long,long);
extern long sun_awt_macos_MacGraphics_drawBytesWidth(struct Hsun_awt_macos_MacGraphics* self,HArrayOfByte *,long,long,long,long);
extern void sun_awt_macos_MacGraphics_drawLine(struct Hsun_awt_macos_MacGraphics* self,long,long,long,long);
extern void sun_awt_macos_MacGraphics_copyArea(struct Hsun_awt_macos_MacGraphics* self,long,long,long,long,long,long);
extern void sun_awt_macos_MacGraphics_drawRoundRect(struct Hsun_awt_macos_MacGraphics* self,long,long,long,long,long,long);
extern void sun_awt_macos_MacGraphics_fillRoundRect(struct Hsun_awt_macos_MacGraphics* self,long,long,long,long,long,long);
extern void sun_awt_macos_MacGraphics_drawPolygon(struct Hsun_awt_macos_MacGraphics* self,HArrayOfInt *,HArrayOfInt *,long);
extern void sun_awt_macos_MacGraphics_fillPolygon(struct Hsun_awt_macos_MacGraphics* self,HArrayOfInt *,HArrayOfInt *,long);
extern void sun_awt_macos_MacGraphics_drawOval(struct Hsun_awt_macos_MacGraphics* self,long,long,long,long);
extern void sun_awt_macos_MacGraphics_fillOval(struct Hsun_awt_macos_MacGraphics* self,long,long,long,long);
extern void sun_awt_macos_MacGraphics_drawArc(struct Hsun_awt_macos_MacGraphics* self,long,long,long,long,long,long);
extern void sun_awt_macos_MacGraphics_fillArc(struct Hsun_awt_macos_MacGraphics* self,long,long,long,long,long,long);
#endif
