/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class sun_awt_macos_MTextAreaPeer */

#ifndef _Included_sun_awt_macos_MTextAreaPeer
#define _Included_sun_awt_macos_MTextAreaPeer
struct Hjava_awt_Component;
struct Hjava_awt_Color;
struct Hjava_lang_Boolean;

typedef struct Classsun_awt_macos_MTextAreaPeer {
    struct Hjava_awt_Component *target;
    long pData;
    long pInternationalData;
    long mOwnerPane;
    long mFont;
    long mSize;
    long mStyle;
    struct Hjava_awt_Color *mForeColor;
    struct Hjava_awt_Color *mBackColor;
    /*boolean*/ long mRecalculateClip;
    /*boolean*/ long mIsContainer;
    /*boolean*/ long mIsButton;
    /*boolean*/ long mIsChoice;
    /*boolean*/ long mIsResizableFrame;
    long mObscuredRgn;
    long mClipRgn;
    struct Hjava_lang_Boolean *mEditable;
} Classsun_awt_macos_MTextAreaPeer;
HandleTo(sun_awt_macos_MTextAreaPeer);

struct Hsun_awt_macos_MComponentPeer;
extern void sun_awt_macos_MTextAreaPeer_create(struct Hsun_awt_macos_MTextAreaPeer* self,struct Hsun_awt_macos_MComponentPeer *);
extern void sun_awt_macos_MTextAreaPeer_setEditable(struct Hsun_awt_macos_MTextAreaPeer* self,/*boolean*/ long);
extern void sun_awt_macos_MTextAreaPeer_select(struct Hsun_awt_macos_MTextAreaPeer* self,long,long);
extern long sun_awt_macos_MTextAreaPeer_getSelectionStart(struct Hsun_awt_macos_MTextAreaPeer* self);
extern long sun_awt_macos_MTextAreaPeer_getSelectionEnd(struct Hsun_awt_macos_MTextAreaPeer* self);
struct Hjava_lang_String;
extern void sun_awt_macos_MTextAreaPeer_setText(struct Hsun_awt_macos_MTextAreaPeer* self,struct Hjava_lang_String *);
extern struct Hjava_lang_String *sun_awt_macos_MTextAreaPeer_getText(struct Hsun_awt_macos_MTextAreaPeer* self);
extern void sun_awt_macos_MTextAreaPeer_insertText(struct Hsun_awt_macos_MTextAreaPeer* self,struct Hjava_lang_String *,long);
extern void sun_awt_macos_MTextAreaPeer_replaceText(struct Hsun_awt_macos_MTextAreaPeer* self,struct Hjava_lang_String *,long,long);
extern void sun_awt_macos_MTextAreaPeer_reshape(struct Hsun_awt_macos_MTextAreaPeer* self,long,long,long,long);
#endif
