/* This file is generated from secprefs.html.  Do not edit.
   (see ns/security/lib/nav/convhtml.sh) */
static char *secprefsheader = "<HTML> \n"
"<HEAD>\n"
"<SCRIPT LANGUAGE=\"JavaScript\">\n"
"var sa_action = \"internal-dialog-handler\";\n"
"var sa_handle = '";
#ifndef XP_WIN
static char *secprefsfooter = "\n"
"var dogbert_p = (navigator.appVersion.substring(0,1) != '3');\n"
"var have_ldap = dogbert_p;\n"
"var have_help = dogbert_p;\n"
"function sa_init_array()\n"
"{\n"
" var num_args = sa_init_array.arguments.length;\n"
" var a = new Array(num_args);\n"
" for ( var i = 0; i < num_args; i++ ) {\n"
" a[i] = sa_init_array.arguments[i];\n"
" }\n"
" return a;\n"
"}\n"
"function sa_init_sorted_array()\n"
"{\n"
" var num_args = sa_init_sorted_array.arguments.length;\n"
" var a = new Array(num_args);\n"
" for ( var i = 0; i < num_args; i++ ) {\n"
" a[i] = sa_init_sorted_array.arguments[i];\n"
" }\n"
" a.sort();\n"
" return a;\n"
"}\n"
"</SCRIPT>\n"
"<SCRIPT>\n"
"function sa_open_form(form_name)\n"
"{\n"
" return '<FORM ACTION=' + sa_action + ' TARGET=_top METHOD=POST NAME=\"' +\n"
" form_name + '\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=handle VALUE=\"' + sa_handle + '\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_current_page VALUE=\"' + sa_curpage + '\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_ssl_cert VALUE=\"' +\n"
" sa_selected_ssl_cert + '\">'+\n"
" '<INPUT TYPE=HIDDEN NAME=submit_mail_cert VALUE=\"' +\n"
" sa_selected_mail_cert + '\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_enter VALUE=\"' +\n"
" sa_warn_enter_secure + '\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_leave VALUE=\"' +\n"
" sa_warn_leave_secure + '\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_mixed VALUE=\"' + sa_warn_mixed + '\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_send VALUE=\"' + sa_warn_send_clear + '\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_ssl2 VALUE=\"' + sa_enable_ssl2 + '\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_ssl3 VALUE=\"' + sa_enable_ssl3 + '\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_password_ask_type VALUE=\"' +\n"
" sa_password_ask_type + '\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_password_ask_interval VALUE=\"' +\n"
" sa_password_ask_interval + '\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_encrypt_always VALUE=\"' +\n"
" sa_encrypt_always +'\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_sign_mail_always VALUE=\"' +\n"
" sa_sign_mail_always +'\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_sign_news_always VALUE=\"' +\n"
" sa_sign_news_always +'\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_encrypt_this VALUE=\"' +\n"
" sa_encrypt_this +'\">' +\n"
" '<INPUT TYPE=HIDDEN NAME=submit_sign_this VALUE=\"' + sa_sign_this +'\">'\n"
"}\n"
"function sa_close_form()\n"
"{\n"
" return \"</FORM>\";\n"
"}\n"
"function sa_save_form_secinfo_status(win)\n"
"{\n"
" with (win.document) {\n"
" if (forms.secinfo_form) {\n"
" if (forms.secinfo_form.encrypt_this_checkbox) \n"
" sa_encrypt_this = forms.secinfo_form.encrypt_this_checkbox.checked;\n"
" if (forms.secinfo_form.sign_this_checkbox)\n"
" sa_sign_this = forms.secinfo_form.sign_this_checkbox.checked;\n"
" }\n"
" }\n"
"}\n"
"function sa_save_form_navigator_status(win)\n"
"{\n"
" with ( win.document ) {\n"
" sa_warn_enter_secure = forms.navigator_form.enter_secure.checked;\n"
" sa_warn_leave_secure = forms.navigator_form.leave_secure.checked;\n"
" sa_warn_mixed = forms.navigator_form.enter_mixed.checked;\n"
" sa_warn_send_clear = forms.navigator_form.send_clear.checked;\n"
" sa_enable_ssl2 = forms.navigator_form.enable_ssl2.checked;\n"
" sa_enable_ssl3 = forms.navigator_form.enable_ssl3.checked;\n"
" if ( forms.navigator_form.site_cert.selectedIndex == 0 ) {\n"
" sa_selected_ssl_cert = sa_ask_sa_every_time_label;\n"
" } else if ( forms.navigator_form.site_cert.selectedIndex == 1 ) {\n"
" sa_selected_ssl_cert = sa_select_auto_label;\n"
" } else {\n"
" sa_selected_ssl_cert =\n"
" sa_your_ssl_certs[forms.navigator_form.site_cert.selectedIndex - 2];\n"
" }\n"
" }\n"
"}\n"
"function sa_save_form_messenger_status(win)\n"
"{\n"
" with ( win.document ) {\n"
" sa_encrypt_always = forms.messenger_form.enable_encrypt_always.checked;\n"
" sa_sign_mail_always = forms.messenger_form.enable_sign_mail_always.checked;\n"
" sa_sign_news_always = forms.messenger_form.enable_sign_news_always.checked;\n"
" if (forms.messenger_form.mail_cert) {\n"
" sa_selected_mail_cert =\n"
" sa_your_mail_certs[forms.messenger_form.mail_cert.selectedIndex];\n"
" } else {\n"
" sa_selected_mail_cert = \"\";\n"
" }\n"
" }\n"
"}\n"
"function sa_save_form_passwords_status(win)\n"
"{\n"
" with ( win.document ) {\n"
" nradio = forms.passwords_form.password_ask.length;\n"
" for ( var i = 0; i < nradio; i++ ) {\n"
" if ( forms.passwords_form.password_ask[i].checked ) {\n"
" sa_password_ask_type = i;\n"
" }\n"
" }\n"
" sa_password_ask_interval = forms.passwords_form.password_interval.value;\n"
" }\n"
"}\n"
"function sa_save_pane(win, pane)\n"
"{\n"
" \n"
" \n"
" if ( pane == 1 ) { sa_save_form_secinfo_status(win); }\n"
" else if ( pane == 2 ) { sa_save_form_passwords_status(win); }\n"
" else if ( pane == 3 ) { sa_save_form_navigator_status(win); }\n"
" else if ( pane == 4 ) { sa_save_form_messenger_status(win); }\n"
"}\n"
"function sa_switch_pane(top_window, old_pane, new_pane)\n"
"{\n"
" sa_save_pane(top_window.frames.content, old_pane);\n"
" sa_make_dialog(top_window, new_pane);\n"
"}\n"
"function sa_prepare_form(form_arg)\n"
"{\n"
" with(form_arg) {\n"
" submit_ssl_cert.value = sa_selected_ssl_cert;\n"
" submit_mail_cert.value = sa_selected_mail_cert;\n"
" submit_enter.value = sa_warn_enter_secure;\n"
" submit_leave.value = sa_warn_leave_secure;\n"
" submit_mixed.value = sa_warn_mixed;\n"
" submit_send.value = sa_warn_send_clear;\n"
" submit_ssl2.value = sa_enable_ssl2;\n"
" submit_ssl3.value = sa_enable_ssl3;\n"
" submit_password_ask_type.value = sa_password_ask_type;\n"
" submit_password_ask_interval.value = sa_password_ask_interval;\n"
" submit_encrypt_always.value = sa_encrypt_always;\n"
" submit_sign_mail_always.value = sa_sign_mail_always;\n"
" submit_sign_news_always.value = sa_sign_news_always;\n"
" submit_encrypt_this.value = sa_encrypt_this;\n"
" submit_sign_this.value = sa_sign_this;\n"
" }\n"
"}\n"
"function sa_ready_submit(top_window, cur_pane)\n"
"{\n"
" sa_save_pane(top_window.frames.content, cur_pane);\n"
" sa_prepare_form(top_window.frames.content.document.forms[0]);\n"
" sa_prepare_form(top_window.frames.buttons.document.forms[0]);\n"
" return false;\n"
"}\n"
"function sa_make_buttons()\n"
"{\n"
" var n_buttons = sa_make_buttons.arguments.length;\n"
" var button_label;\n"
" var ret_string = \"\";\n"
" \n"
" ret_string += '<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0>';\n"
" for ( var i = 0; i < n_buttons; i++ ) {\n"
" button_label = sa_make_buttons.arguments[i];\n"
" ret_string += '<TR><TD WIDTH=10></TD><TD VALIGN=TOP>';\n"
" ret_string += ('<INPUT TYPE=SUBMIT NAME=button VALUE=\"'\n"
" + button_label + '\">');\n"
" ret_string += '</TD>';\n"
" }\n"
" ret_string += '</TABLE>';\n"
" return(ret_string);\n"
"}\n"
"function sa_make_checkboxes()\n"
"{\n"
" var nboxes = ( sa_make_checkboxes.arguments.length / 3 );\n"
" var box_name;\n"
" var box_label;\n"
" var box_checked;\n"
" var ret_string = \"\";\n"
" \n"
" ret_string += '<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0>';\n"
" for ( var i = 0; i < nboxes; i++ ) {\n"
" box_name = sa_make_checkboxes.arguments[i*3];\n"
" box_label = sa_make_checkboxes.arguments[i*3+1];\n"
" box_checked = sa_make_checkboxes.arguments[i*3+2];\n"
" \n"
" ret_string += '<TR><TD WIDTH=20></TD><TD VALIGN=TOP>';\n"
" ret_string += ('<INPUT TYPE=CHECKBOX NAME=\"' + box_name + '\"' +\n"
" ( box_checked ? ' CHECKED' : '' ) + '>');\n"
" ret_string += '</TD><TD WIDTH=10></TD><TD VALIGN=MIDDLE>';\n"
" ret_string += box_label;\n"
" ret_string += '</TD></TR>';\n"
" }\n"
" ret_string += '</TABLE>';\n"
" return(ret_string);\n"
"}\n"
"function sa_make_radio_buttons(radio_name, checked)\n"
"{\n"
" var n_buttons = ( ( sa_make_radio_buttons.arguments.length - 2 ) / 2 );\n"
" var submit_value;\n"
" var radio_label;\n"
" var ret_string = \"\";\n"
" \n"
" for ( var i = 0; i < n_buttons; i++ ) {\n"
" submit_value = sa_make_radio_buttons.arguments[i*2+2];\n"
" radio_label = sa_make_radio_buttons.arguments[i*2+3];\n"
" \n"
" if ( i != 0 ) {\n"
" ret_string += '<BR>';\n"
" }\n"
" ret_string += ('<INPUT TYPE=RADIO NAME=\"' + radio_name + '\"' +\n"
" ( i == checked ? ' CHECKED' : '' ) +\n"
" ' VALUE=\"' + submit_value +\n"
" '\">' + radio_label);\n"
" }\n"
" return(ret_string);\n"
"}\n"
"function sa_make_menu(menu_name, menu_label, selected)\n"
"{\n"
" var nitems = ( sa_make_menu.arguments.length ) - 3;\n"
" var item;\n"
" var count = 0;\n"
" var ret_string = \"\";\n"
" \n"
" ret_string += '<TABLE><TR>';\n"
" if (typeof(menu_label) == 'string') {\n"
" ret_string += '<TD VALIGN=TOP>' + menu_label;\n"
" } else {\n"
" ret_string += '<TD WIDTH=35>';\n"
" }\n"
" ret_string += '</TD><TD VALIGN=TOP><SELECT NAME=\"' + menu_name + '\">';\n"
" for ( var i = 0; i < nitems; i++ ) {\n"
" item = sa_make_menu.arguments[i+3];\n"
" if ( typeof(item) == 'string' ) {\n"
" ret_string += ('<OPTION' +\n"
" ( ( item == selected ) ? ' SELECTED>' : '>' ) +\n"
" item);\n"
" count++;\n"
" } else { /* its an array */\n"
" for ( var j = 0; j < item.length; j++ ) {\n"
" ret_string += ('<OPTION' +\n"
" ( ( item[j] == selected ) ? ' SELECTED>' : '>' ) +\n"
" item[j]);\n"
" \n"
" count++;\n"
" }\n"
" }\n"
" }\n"
" ret_string += '</SELECT></TD></TR></TABLE>';\n"
" return(ret_string);\n"
"}\n"
"function sa_make_page_intro(title, bgcolor)\n"
"{\n"
" var style = '<STYLE TYPE=\"text/css\">BODY{' +\n"
" 'font-family: Geneva,MS Sans Serif,Arial,Lucida,Helvetica,sans-serif;' +\n"
" 'font-size: 10pt;' +\n"
" '}' +\n"
" 'TD{' +\n"
" 'font-family: Geneva,MS Sans Serif,Arial,Lucida,Helvetica,sans-serif;' +\n"
" 'font-size: 10pt;}' +\n"
" '</STYLE>';\n"
" if (bgcolor == null) { bgcolor = \"#C0C0C0\"; }\n"
" return '<HTML><HEAD>' +\n"
" '<TITLE>' + title + '</TITLE>' +\n"
" '</HEAD>' +\n"
" '<BODY TEXT=\"#000000\" LINK=\"#000000\" VLINK=\"#000000\" ALINK=\"#FF0000\" ' +\n"
" 'BGCOLOR=\"' + bgcolor + '\">';\n"
"}\n"
"function sa_make_secinfo_page()\n"
"{\n"
" if (sa_info_context == 1) { return sa_make_secinfo_compose_page(); }\n"
" else if (sa_info_context == 2) { return sa_make_secinfo_message_page(false);}\n"
" else if (sa_info_context == 3) { return sa_make_secinfo_message_page(true); }\n"
" else if (sa_info_context == 4) { return sa_make_secinfo_message_page(true); }\n"
" else if (sa_info_context == 5) { return sa_make_secinfo_nav_page(); }\n"
" else if (sa_info_context == 7) { return sa_make_secinfo_thread_page(true); }\n"
" else {\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_secinfo_index_label, null);\n"
" ret_string += sa_open_form('secinfo_form');\n"
" ret_string += \"<TABLE BORDER=0 HEIGHT=99%><TR VALIGN=CENTER>\" +\n"
" \"<TD ALIGN=CENTER>\";\n"
" ret_string += sa_not_me_subtitle;\n"
" ret_string += \"</TD></TR><TR><TD VALIGN=TOP ALIGN=LEFT>\" +\n"
" sa_not_me_desc_1 + sa_not_me_desc_2;\n"
" ret_string += \"</TD></TR></TABLE>\";\n"
" ret_string += sa_close_form();\n"
" return ret_string;\n"
" }\n"
"}\n"
"function sa_make_secinfo_compose_page()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_secinfo_index_label, null);\n"
" ret_string += sa_open_form('secinfo_form');\n"
" var etitle_string = \"<B><FONT SIZE=+1>\" + sa_compose_encrypt_subtitle\n"
" + \"</FONT></B><P>\";\n"
" var stitle_string = \"<B><FONT SIZE=+1>\" + sa_compose_sign_subtitle\n"
" + \"</FONT></B><P>\";\n"
" ret_string += \"<TABLE BORDER HEIGHT=100% VALIGN=TOP CELLPADDING=0>\" +\n"
" \"<TR VALIGN=TOP><TD HEIGHT=200>\";\n"
" if (sa_encrypt_errors.length == 1 && sa_encrypt_errors[0] == 0) {\n"
" ret_string += \"<IMG SRC=internal-sa-encrypted ALIGN=RIGHT>\" +\n"
" etitle_string;\n"
" ret_string += sa_can_encrypt + \"<P>\";\n"
" ret_string += sa_make_checkboxes('encrypt_this_checkbox',\n"
" sa_encrypt_this_checkbox_label,\n"
" sa_encrypt_this)\n"
" + \"<P>\";\n"
" ret_string += sa_send_encrypt_desc;\n"
" } else {\n"
" ret_string += \"<IMG SRC=internal-sa-nonencrypted ALIGN=RIGHT>\" +\n"
" etitle_string;\n"
" ret_string += sa_cannot_encrypt_head + \"<BR>\";\n"
" if (sa_encrypt_errors[0] == 1) {\n"
" ret_string += \"<BR>\" + sa_no_recipients_desc + \"<BR>\";\n"
" } else {\n"
" ret_string += \"<TABLE WIDTH='100%'><TR><TD VALIGN=TOP>\"\n"
" + \"<SELECT SIZE=4 NAME=errors>\";\n"
" for ( var i = 0; i < sa_dest_names.length; i++ ) {\n"
" ret_string += (\"<OPTION>\" + sa_dest_names[i]);\n"
" if (sa_encrypt_errors[i] == 2) {\n"
" ret_string += sa_cert_missing_tail;\n"
" } else if (sa_encrypt_errors[i] == 3) {\n"
" ret_string += sa_cert_has_exp_tail;\n"
" } else if (sa_encrypt_errors[i] == 4) {\n"
" ret_string += sa_cert_has_revoke_tail;\n"
" } else if (sa_encrypt_errors[i] == 5) {\n"
" ret_string += sa_cert_no_alias_tail;\n"
" } else if (sa_encrypt_errors[i] == 6) {\n"
" ret_string += sa_cert_newsgroup_tail;\n"
" } else if (sa_encrypt_errors[i] == 7) {\n"
" ret_string += sa_cert_invalid_tail;\n"
" } else if (sa_encrypt_errors[i] == 8) {\n"
" ret_string += sa_cert_untrusted_tail;\n"
" } else if (sa_encrypt_errors[i] == 9) {\n"
" ret_string += sa_cert_issuer_untrusted_tail;\n"
" } else if (sa_encrypt_errors[i] == 10) {\n"
" ret_string += sa_cert_issuer_unknown_tail;\n"
" } else {\n"
" ret_string += sa_cert_unknown_error_tail;\n"
" }\n"
" }\n"
" ret_string += \"</SELECT></TD>\";\n"
" if (have_ldap) {\n"
" ret_string += \"<TD>\" +\n"
" \"<INPUT TYPE=SUBMIT NAME=button VALUE=\\\"\" +\n"
" sa_get_certs_button_label + '\">' +\n"
" \"</TD>\";\n"
" }\n"
" ret_string += \"</TR></TABLE>\";\n"
" if (have_ldap) {\n"
" ret_string +=\n"
" sa_how_to_get_their_cert_1 +\n"
" sa_how_to_get_their_cert_2;\n"
" } else {\n"
" ret_string +=\n"
" sa_how_to_get_their_nondirectory_cert_1 +\n"
" sa_how_to_get_their_nondirectory_cert_2;\n"
" }\n"
" }\n"
" }\n"
" ret_string += \"</TD></TR><TR VALIGN=TOP><TD>\";\n"
" if (sa_sign_error == 0) {\n"
" ret_string += \"<IMG SRC=internal-sa-signed ALIGN=RIGHT>\" + stitle_string;\n"
" ret_string += sa_can_be_signed + \"<P>\";\n"
" ret_string += sa_make_checkboxes('sign_this_checkbox',\n"
" sa_sign_this_checkbox_label,\n"
" sa_sign_this)\n"
" + \"<BR>\";\n"
" ret_string += sa_can_sign_desc + \"<P>\" + sa_sign_disclaimer;\n"
" } else if (sa_sign_error == 1) {\n"
" ret_string += \"<IMG SRC=internal-sa-signed-bad ALIGN=RIGHT>\" +\n"
" stitle_string;\n"
" ret_string += sa_cannot_be_signed + \"<P>\";\n"
" ret_string += sa_cannot_sign_desc_1 + sa_cannot_sign_desc_2;\n"
" ret_string += \"<P>\" + sa_sign_disclaimer + \"<BR>\";\n"
" ret_string += \"<BR><INPUT TYPE=SUBMIT NAME=button VALUE=\\\"\" +\n"
" sa_get_cert_button_label + '\">';\n"
" }\n"
" ret_string += \"</TD></TR></TABLE>\";\n"
" ret_string += sa_close_form();\n"
" return ret_string;\n"
"}\n"
"</SCRIPT>";
static char *secprefsfooter2 = "<SCRIPT>\n"
"function sa_make_secinfo_message_page(news_p)\n"
"{\n"
" var etitle_string;\n"
" var stitle_string;\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_secinfo_index_label, null);\n"
" ret_string += sa_open_form('secinfo_form');\n"
" etitle_string = \"<B><FONT SIZE=+1>\" +\n"
" (news_p ? sa_news_encrypt_subtitle : sa_message_encrypt_subtitle) +\n"
" \"</FONT></B><P>\";\n"
" stitle_string = \"<B><FONT SIZE=+1>\" +\n"
" sa_message_sign_subtitle +\n"
" \"</FONT></B><P>\";\n"
" if (sa_encrypt_errors[0] == 0) {\n"
" ret_string += \"<IMG SRC=internal-sa-encrypted ALIGN=RIGHT>\" +\n"
" etitle_string +\n"
" (news_p ? (sa_news_encrypted_1 + sa_news_encrypted_2)\n"
" : sa_was_encrypted);\n"
" } else if (sa_encrypt_errors[0] == 1) {\n"
" sa_encryption_algorithm = \"\";\n"
" ret_string += \"<IMG SRC=internal-sa-nonencrypted ALIGN=RIGHT>\" +\n"
" etitle_string +\n"
" (news_p ? sa_news_not_encrypted : sa_was_not_encrypted);\n"
" } else if (sa_encrypt_errors[0] == 2) {\n"
" ret_string += \"<IMG SRC=internal-sa-encrypted-bad ALIGN=RIGHT>\" +\n"
" etitle_string +\n"
" sa_was_encrypted_for_other_1 + sa_was_encrypted_for_other_2;\n"
" } else {\n"
" ret_string += \"<IMG SRC=internal-sa-encrypted-bad ALIGN=RIGHT>\" +\n"
" etitle_string + \"<P>\" + sa_encryption_invalid + sa_encrypt_error_str;\n"
" }\n"
" if (sa_encryption_algorithm != \"\") {\n"
" ret_string += \"<P>\" +\n"
" sa_encryption_algorithm_was + sa_encryption_algorithm + \".\";\n"
" }\n"
" ret_string += \"<P><HR><P>\";\n"
" ret_string += \"<IMG SRC=\" +\n"
" ((sa_sign_error == 0) ? \"internal-sa-signed\" : \"internal-sa-signed-bad\") +\n"
" \" ALIGN=RIGHT>\" + stitle_string;\n"
" if (sa_sign_error == 0) {\n"
" ret_string += sa_was_signed_head + \"<B>\" + sa_signer_name + \"</B>\";\n"
" if (sa_signing_time) {\n"
" ret_string += sa_was_signed_at + sa_signing_time;\n"
" }\n"
" ret_string += \".<P> \";\n"
" } else if (sa_sign_error == 1) {\n"
" ret_string += sa_was_not_signed;\n"
" \n"
" } else if (sa_sign_error == 3) {\n"
" ret_string += sa_sig_tampered_1 + sa_sig_tampered_2;\n"
" } else if (sa_sign_error == 4) {\n"
" ret_string += sa_addr_mismatch_part1 + sa_sender_addr;\n"
" ret_string += sa_addr_mismatch_part2 + sa_signer_addr;\n"
" ret_string += sa_addr_mismatch_part3;\n"
" } else {\n"
" ret_string += sa_sig_invalid;\n"
" ret_string += \"<P>\" + sa_sign_error_intro;\n"
" ret_string += sa_sign_error_str;\n"
" }\n"
" if (sa_sign_error != 0 && sa_sign_error != 1) {\n"
" ret_string += \"<P>\" + sa_included_cert_desc_head + \"<B>\" +\n"
" sa_signer_name + \"</B>\";\n"
" if (sa_signing_time) {\n"
" ret_string += sa_included_cert_desc_signed_at + sa_signing_time;\n"
" }\n"
" ret_string += \". \";\n"
" }\n"
" if (sa_sign_error != 1) {\n"
" ret_string += sa_was_signed_desc_tail_1 + sa_was_signed_desc_tail_2;\n"
" ret_string += \"<P>\" + sa_make_buttons(sa_view_button_label);\n"
" }\n"
" ret_string += sa_close_form();\n"
" return ret_string;\n"
"}\n"
"function sa_make_secinfo_thread_page(news_p)\n"
"{\n"
" var etitle_string;\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_secinfo_index_label, null);\n"
" ret_string += sa_open_form('secinfo_form');\n"
" etitle_string = \"<B><FONT SIZE=+1>\" +\n"
" (news_p ? sa_news_encrypt_subtitle : sa_message_encrypt_subtitle) +\n"
" \"</FONT></B><P>\";\n"
" if (sa_nav_info_encrypted == true) {\n"
" ret_string += \"<IMG SRC=internal-sa-encrypted ALIGN=RIGHT>\";\n"
" } else {\n"
" ret_string += \"<IMG SRC=internal-sa-nonencrypted ALIGN=RIGHT>\";\n"
" }\n"
" ret_string += etitle_string;\n"
" if (sa_nav_info_encrypted == true) {\n"
" ret_string += (news_p ? (sa_news_encrypted_1 + sa_news_encrypted_2) : '');\n"
" } else {\n"
" sa_encryption_algorithm = \"\";\n"
" ret_string += (news_p ? sa_news_not_encrypted : '');\n"
" }\n"
" ret_string += sa_close_form();\n"
" return ret_string;\n"
"}\n"
"function sa_make_nav_no_encrypt_info()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_nav_no_encrypt_desc_1;\n"
" ret_string += sa_nav_no_encrypt_desc_2;\n"
" ret_string += \"<P>\";\n"
" return ret_string;\n"
"}\n"
"function sa_make_nav_encrypt_info()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_nav_encrypt_desc_1;\n"
" ret_string += sa_nav_encrypt_desc_2;\n"
" ret_string += sa_nav_encrypt_desc_3;\n"
" ret_string += \"<P><INPUT TYPE=SUBMIT NAME=button VALUE=\\\"\" +\n"
" sa_view_cert_button_label + '\">';\n"
" return ret_string;\n"
"}\n"
"function sa_make_nav_no_encrypt_mix_info()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_nav_no_encrypt_mix_desc_1;\n"
" ret_string += sa_nav_no_encrypt_mix_desc_2;\n"
" ret_string += sa_nav_no_encrypt_mix_desc_3;\n"
" ret_string += \"<P>\";\n"
" return ret_string;\n"
"}\n"
"function sa_make_nav_encrypt_mix_info()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_nav_encrypt_mix_desc_1;\n"
" ret_string += sa_nav_encrypt_mix_desc_2;\n"
" ret_string += sa_nav_encrypt_mix_desc_3;\n"
" ret_string += sa_nav_encrypt_mix_desc_4;\n"
" ret_string += sa_nav_encrypt_mix_desc_5;\n"
" ret_string += \"<P><INPUT TYPE=SUBMIT NAME=button VALUE=\\\"\" +\n"
" sa_view_cert_button_label + '\">';\n"
" return ret_string;\n"
"}\n"
"function sa_make_nav_verify_info()\n"
"{\n"
" var ret_string = '';\n"
" var last;\n"
" if (sa_nav_info_site_name == \"\")\n"
" return '';\n"
" ret_string+= \"<P><HR><P>\";\n"
" ret_string += \"<B><FONT SIZE=+1>\" + sa_nav_verification_subtitle +\n"
" \"</FONT></B><P>\";\n"
" ret_string += \"<UL>\";\n"
" if (sa_nav_info_encrypted) {\n"
" ret_string += \"<LI>\" + sa_nav_verify_cert_desc;\n"
" }\n"
" ret_string += \"<LI>\" + sa_nav_verify_domain_desc + sa_nav_info_site_name;\n"
" if (sa_nav_info_chrome_missing) {\n"
" if (sa_nav_info_missing_status) {\n"
" last = 4;\n"
" } else if (sa_nav_info_missing_location) {\n"
" last = 3;\n"
" } else if (sa_nav_info_missing_personalbar) {\n"
" last = 2;\n"
" } else if (sa_nav_info_missing_toolbar) {\n"
" last = 1;\n"
" } else {\n"
" last = 0;\n"
" }\n"
" ret_string += \"<LI>\" + sa_nav_verify_missing_desc_1;\n"
" if (sa_nav_info_missing_menubar) {\n"
" ret_string += sa_nav_info_menubar_name;\n"
" if (last != 0) {\n"
" ret_string += \", \";\n"
" }\n"
" }\n"
" if (sa_nav_info_missing_toolbar) {\n"
" ret_string += sa_nav_info_toolbar_name;\n"
" if (last != 1) {\n"
" ret_string += \", \";\n"
" }\n"
" }\n"
" if (sa_nav_info_missing_personalbar) {\n"
" ret_string += sa_nav_info_personalbar_name;\n"
" if (last != 2) {\n"
" ret_string += \", \";\n"
" }\n"
" }\n"
" if (sa_nav_info_missing_location) {\n"
" ret_string += sa_nav_info_location_name;\n"
" if (last != 3) {\n"
" ret_string += \", \";\n"
" }\n"
" }\n"
" if (sa_nav_info_missing_status) {\n"
" ret_string += sa_nav_info_status_name;\n"
" }\n"
" ret_string += sa_nav_verify_missing_desc_2;\n"
" }\n"
" if (sa_nav_info_java) {\n"
" ret_string += \"<LI>\" + sa_nav_verify_java_desc_1;\n"
" ret_string += sa_nav_info_creator_name;\n"
" ret_string += sa_nav_verify_java_desc_2;\n"
" } else if (sa_nav_info_js) {\n"
" ret_string += \"<LI>\" + sa_nav_verify_js_desc_1;\n"
" ret_string += sa_nav_info_creator_name;\n"
" ret_string += sa_nav_verify_js_desc_2;\n"
" }\n"
" ret_string += \"</UL>\";\n"
" return ret_string;\n"
"}\n"
"function sa_make_secinfo_nav_page()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_secinfo_index_label, null);\n"
" ret_string += sa_open_form('secinfo_form');\n"
" if (sa_nav_info_encrypted) {\n"
" ret_string += \"<IMG SRC=internal-sa-encrypted ALIGN=RIGHT>\";\n"
" } else {\n"
" ret_string += \"<IMG SRC=internal-sa-nonencrypted ALIGN=RIGHT>\";\n"
" }\n"
" ret_string += \"<B><FONT SIZE=+1>\" + sa_nav_encryption_subtitle +\n"
" \"</FONT></B><P>\";\n"
" if (sa_nav_info_encrypted) {\n"
" if (sa_nav_info_mixed) {\n"
" ret_string += sa_make_nav_encrypt_mix_info();\n"
" } else {\n"
" ret_string += sa_make_nav_encrypt_info();\n"
" }\n"
" } else {\n"
" if (sa_nav_info_mixed) {\n"
" ret_string += sa_make_nav_no_encrypt_mix_info();\n"
" } else {\n"
" ret_string += sa_make_nav_no_encrypt_info();\n"
" }\n"
" }\n"
" ret_string += \"<INPUT TYPE=SUBMIT NAME=button VALUE=\\\"\" +\n"
" sa_page_info_label + \"\\\">\";\n"
" ret_string += sa_make_nav_verify_info();\n"
" ret_string += sa_close_form();\n"
" return ret_string;\n"
"}\n"
"function sa_make_passwords_page()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_passwords_index_label, null);\n"
" ret_string += sa_open_form('passwords_form');\n"
" ret_string += sa_password_desc_1 + sa_password_desc_2;\n"
" if ( sa_password_set ) {\n"
" ret_string += sa_make_buttons(sa_change_password_label);\n"
" } else {\n"
" ret_string += sa_make_buttons(sa_set_password_label);\n"
" }\n"
" ret_string += '<P>';\n"
" ret_string += sa_ask_for_password_label;\n"
" ret_string += '<UL>';\n"
" ret_string += sa_make_radio_buttons('password_ask', sa_password_ask_type,\n"
" 'once', sa_once_per_session_label,\n"
" 'every', sa_every_time_label,\n"
" 'timeout', sa_after_label);\n"
" ret_string += (\"<INPUT TYPE=INT SIZE=4 NAME=password_interval VALUE=\\\"\" +\n"
" sa_password_ask_interval + \"\\\">\");\n"
" ret_string += sa_minutes_label;\n"
" ret_string += '</UL>';\n"
" ret_string += sa_close_form();\n"
" return(ret_string);\n"
"}\n"
"function sa_make_navigator_page()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_navigator_index_label, null);\n"
" ret_string += sa_open_form('navigator_form') + sa_ssl_desc;\n"
" ret_string += sa_make_checkboxes('enter_secure',\n"
" sa_enter_secure_label,\n"
" sa_warn_enter_secure,\n"
" 'leave_secure',\n"
" sa_leave_secure_label,\n"
" sa_warn_leave_secure,\n"
" 'enter_mixed',\n"
" sa_mixed_secure_label,\n"
" sa_warn_mixed,\n"
" 'send_clear',\n"
" sa_send_clear_label,\n"
" sa_warn_send_clear);\n"
" \n"
" ret_string += '<P>' + sa_ssl_cert_label + \"<BR>\";\n"
" ret_string += sa_make_menu('site_cert', null, sa_selected_ssl_cert,\n"
" sa_ask_sa_every_time_label, sa_select_auto_label,\n"
" sa_your_ssl_certs);\n"
" \n"
" ret_string += \"<P>\";\n"
" ret_string += sa_ssl_config_label;\n"
" ret_string += \"<P>\";\n"
" ret_string += \"<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0>\";\n"
" ret_string += \"<TR><TD ALIGN=LEFT VALIGN=MIDDLE>\";\n"
" ret_string += sa_make_checkboxes('enable_ssl2',\n"
" sa_ssl2_enable_label,\n"
" sa_enable_ssl2);\n"
" ret_string += \"</TD><TD ALIGN=LEFT VALIGN=MIDDLE>\"\n"
" ret_string += sa_make_buttons(sa_ssl2_config_label);\n"
" ret_string += \"</TD></TR><TD ALIGN=LEFT VALIGN=MIDDLE>\"\n"
" ret_string += sa_make_checkboxes('enable_ssl3',\n"
" sa_ssl3_enable_label,\n"
" sa_enable_ssl3);\n"
" ret_string += \"</TD><TD ALIGN=LEFT VALIGN=MIDDLE>\"\n"
" ret_string += sa_make_buttons(sa_ssl3_config_label);\n"
" \n"
" ret_string += \"</TD></TR></TABLE>\"\n"
" ret_string += sa_close_form();\n"
" return(ret_string);\n"
"}\n"
"function sa_make_messenger_page()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_messenger_index_label, null);\n"
" ret_string += sa_open_form('messenger_form');\n"
" ret_string += sa_smime_desc + \"<BR>\";\n"
" ret_string += \"<BR>\" + sa_smime_pref_desc + \"<BR>\";\n"
" ret_string += sa_make_checkboxes('enable_encrypt_always',\n"
" sa_encrypt_always_checkbox_label,\n"
" sa_encrypt_always,\n"
" 'enable_sign_mail_always',\n"
" sa_sign_mail_always_checkbox_label,\n"
" sa_sign_mail_always,\n"
" 'enable_sign_news_always',\n"
" sa_sign_news_always_checkbox_label,\n"
" sa_sign_news_always);\n"
" ret_string += '<P>' + sa_smime_cert_label + \"<BR>\";\n"
" if (sa_your_mail_certs.length == 0)\n"
" {\n"
" ret_string += \"<UL>\" + sa_smime_no_certs_blurb + \"</UL>\";\n"
" ret_string += sa_smime_no_cert_desc_1 + sa_smime_no_cert_desc_2;\n"
" }\n"
" else\n"
" {\n"
" ret_string += sa_make_menu('mail_cert', null,\n"
" sa_selected_mail_cert, sa_your_mail_certs);\n"
" ret_string += sa_smime_cert_desc;\n"
" if (have_ldap) {\n"
" ret_string += sa_smime_send_cert_desc;\n"
" ret_string += \"<P>\" + sa_make_buttons(sa_send_cert_button_label);\n"
" }\n"
" }\n"
" ret_string += \"<P>\";\n"
" ret_string += sa_smime_cipher_heading;\n"
" ret_string += \"<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0><TR>\";\n"
" ret_string += \"<TD WIDTH=35></TD><TD VALIGN=MIDDLE>\";\n"
" ret_string += sa_smime_cipher_desc;\n"
" ret_string += \"</TD><TD VALIGN=MIDDLE>\";\n"
" ret_string += sa_make_buttons(sa_smime_config_label);\n"
" ret_string += \"</TD></TR></TABLE>\";\n"
" ret_string += sa_close_form();\n"
" return(ret_string);\n"
"}\n"
"function sa_make_applets_page()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_applets_index_label, null);\n"
" ret_string += sa_open_form('applets_form') +\n"
" sa_applets_desc_1 + sa_applets_desc_2 +\n"
" \"<P><TABLE><TR><TD WIDTH=10></TD><TD VALIGN=TOP>\" +\n"
" \"<SELECT SIZE=14 NAME=certs>\";\n"
" for ( var i = 0; i < sa_principals.length; i++ ) {\n"
" ret_string += (\"<OPTION>\" + sa_principals[i]);\n"
" }\n"
" ret_string += \"</SELECT></TD><TD VALIGN=TOP>\";\n"
" ret_string += sa_make_buttons(sa_view_cert_button_label,\n"
" sa_remove_button_label,\n"
" sa_edit_privs_button_label);\n"
" ret_string += \"</TD></TR></TABLE>\";\n"
" ret_string += sa_close_form();\n"
" return(ret_string);\n"
"}\n"
"function sa_make_certs_intro_page()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_certs_intro_index_label, null);\n"
" ret_string += sa_open_form('applets_form');\n"
" ret_string += sa_certs_intro_string_1;\n"
" ret_string += sa_certs_intro_string_2;\n"
" ret_string += sa_certs_intro_string_3;\n"
" ret_string += sa_certs_intro_string_4;\n"
" ret_string += sa_certs_intro_string_5;\n"
" ret_string += sa_close_form();\n"
" return(ret_string);\n"
"}\n"
"function sa_make_your_certs_page()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_yours_index_label, null);\n"
" ret_string += sa_open_form('your_certs_form')\n"
" + sa_your_certs_desc_1\n"
" + sa_your_certs_desc_2\n"
" + \"<TABLE><TR><TD WIDTH=10></TD><TD VALIGN=TOP>\"\n"
" + \"<SELECT SIZE=10 NAME=certs>\";\n"
" for ( var i = 0; i < sa_your_certs.length; i++ ) {\n"
" ret_string += (\"<OPTION>\" + sa_your_certs[i]);\n"
" }\n"
" ret_string += \"</SELECT></TD><TD VALIGN=TOP>\";\n"
" ret_string += sa_make_buttons(sa_view_button_label, sa_verify_button_label,\n"
" sa_delete_button_label,\n"
" sa_export_button_label);\n"
" \n"
" ret_string += \"</TD></TR></TABLE>\";\n"
" ret_string += sa_your_certs_desc_tail_1 + sa_your_certs_desc_tail_2 + '<P>';\n"
" ret_string += (' <INPUT TYPE=SUBMIT NAME=button VALUE=\"' +\n"
" sa_get_cert_button_label + '\">');\n"
" ret_string += (' <INPUT TYPE=SUBMIT NAME=button VALUE=\"' +\n"
" sa_import_button_label + '\">');\n"
" ret_string += sa_close_form();\n"
" return(ret_string);\n"
"}\n"
"function sa_make_people_certs_page()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_people_index_label, null);\n"
" ret_string += sa_open_form('people_certs_form');\n"
" ret_string += sa_people_certs_desc_1 + sa_people_certs_desc_2;\n"
" ret_string += \"<TABLE><TR><TD WIDTH=10></TD><TD VALIGN=TOP>\" +\n"
" \"<SELECT SIZE=12 NAME=certs>\";\n"
" for ( var i = 0; i < sa_people_certs.length; i++ ) {\n"
" ret_string += (\"<OPTION>\" + sa_people_certs[i]);\n"
" }\n"
" ret_string += \"</SELECT></TD><TD VALIGN=TOP>\";\n"
" ret_string += sa_make_buttons(sa_view_button_label,\n"
" sa_verify_button_label,\n"
" sa_delete_button_label);\n"
" ret_string += \"</TD></TR></TABLE>\";\n"
" if (have_ldap) {\n"
" ret_string += sa_get_certs_desc;\n"
" ret_string += sa_make_buttons(sa_search_dir_button_label);\n"
" }\n"
" ret_string += sa_close_form();\n"
" return(ret_string);\n"
"}\n"
"function sa_make_site_certs_page()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_sites_index_label, null);\n"
" ret_string += sa_open_form('site_certs_form') + sa_site_certs_desc +\n"
" \"<P><TABLE><TR><TD WIDTH=10></TD><TD VALIGN=TOP>\" +\n"
" \"<SELECT SIZE=14 NAME=certs>\";\n"
" for ( var i = 0; i < sa_site_certs.length; i++ ) {\n"
" ret_string += (\"<OPTION>\" + sa_site_certs[i]);\n"
" }\n"
" ret_string += \"</SELECT></TD><TD VALIGN=TOP>\";\n"
" ret_string += sa_make_buttons(sa_edit_button_label, sa_verify_button_label,\n"
" sa_delete_button_label);\n"
" \n"
" ret_string += \"</TD></TR></TABLE>\";\n"
" ret_string += sa_close_form();\n"
" return(ret_string);\n"
"}\n"
"function sa_make_signers_certs_page()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_signers_index_label, null);\n"
" ret_string += sa_open_form('signers_certs_form') + sa_signers_certs_desc +\n"
" \"<P><TABLE><TR><TD WIDTH=10></TD><TD VALIGN=TOP>\" +\n"
" \"<SELECT SIZE=14 NAME=certs>\";\n"
" for ( var i = 0; i < sa_signers_certs.length; i++ ) {\n"
" ret_string += (\"<OPTION>\" + sa_signers_certs[i]);\n"
" }\n"
" ret_string += \"</SELECT></TD><TD VALIGN=TOP>\";\n"
" ret_string += sa_make_buttons(sa_edit_button_label, sa_verify_button_label,\n"
" sa_delete_button_label);\n"
" \n"
" ret_string += \"</TD></TR></TABLE>\";\n"
" sa_close_form();\n"
" return(ret_string);\n"
"}\n"
"function sa_make_modules_page()\n"
"{\n"
" var ret_string = '';\n"
" ret_string += sa_make_page_intro(sa_modules_index_label, null);\n"
" ret_string += sa_open_form('cr_modules_form');\n"
" ret_string += sa_modules_desc;\n"
" ret_string += \"<P><TABLE><TR><TD WIDTH=10></TD><TD VALIGN=TOP>\" +\n"
" \"<SELECT SIZE=14 NAME=sa_cr_modules>\";\n"
" \n"
" for ( var i = 0; i < sa_cr_modules.length; i++ ) {\n"
" ret_string += (\"<OPTION>\" + sa_cr_modules[i]);\n"
" }\n"
" ret_string += \"</SELECT></TD><TD VALIGN=TOP>\";\n"
" ret_string += sa_make_buttons(sa_view_edit_button_label, sa_add_button_label,\n"
" sa_delete_button_label,\n"
" sa_logout_all_button_label);\n"
" \n"
" ret_string += \"</TD></TR></TABLE>\";\n"
" ret_string += sa_close_form();\n"
" return(ret_string);\n"
"}\n"
"function sa_make_index_page(selected)\n"
"{\n"
" var n_strings = ( sa_make_index_page.arguments.length - 1 ) / 2;\n"
" var table_background;\n"
" var command;\n"
" var indent;\n"
" var label;\n"
" var ret_string = \"\";\n"
" \n"
" ret_string += '<TABLE CELLSPACING=4>';\n"
" for ( var i = 1; i <= n_strings; i++ ) {\n"
" if ( i == selected ) {\n"
" table_background = 'BGCOLOR=#BBCCBB';\n"
" } else {\n"
" table_background = '';\n"
" }\n"
" \n"
" indent = sa_make_index_page.arguments[(i*2) - 1];\n"
" label = sa_make_index_page.arguments[(i*2)];\n"
" if ( indent == 0 ) {\n"
" ret_string += ('<TR><TD COLSPAN=2 ' + table_background + '>');\n"
" } else {\n"
" ret_string += ('<TR><TD>&nbsp;&nbsp;</TD><TD ' + table_background + '>');\n"
" }\n"
" command = \"'parent.sa_switch_pane(parent,\" + selected + \",\" + i + \")'\";\n"
" ret_string += ('<A HREF=\"javascript:void setTimeout(' + command + ',0)\">');\n"
" if ( indent == 0 ) { ret_string += \"<B>\"; }\n"
" ret_string += label;\n"
" if ( indent == 0 ) { ret_string += \"</B>\"; }\n"
" ret_string += '</A></TD></TR>';\n"
" }\n"
" ret_string += '</TABLE>';\n"
" return(ret_string);\n"
"}\n"
"function sa_make_selected_page(selected)\n"
"{\n"
" \n"
" if ( selected == 1 ) { return sa_make_secinfo_page(); }\n"
" else if ( selected == 2 ) { return sa_make_passwords_page(); }\n"
" else if ( selected == 3 ) { return sa_make_navigator_page(); }\n"
" else if ( selected == 4 ) { return sa_make_messenger_page(); }\n"
" else if ( selected == 5 ) { return sa_make_applets_page(); }\n"
" else if ( selected == 6 ) { return sa_make_certs_intro_page(); }\n"
" else if ( selected == 7 ) { return sa_make_your_certs_page(); }\n"
" else if ( selected == 8 ) { return sa_make_people_certs_page(); }\n"
" else if ( selected == 9 ) { return sa_make_site_certs_page(); }\n"
" else if ( selected == 10 ) { return sa_make_signers_certs_page(); }\n"
" else if ( selected == 11 ) { return sa_make_modules_page(); }\n"
" else {\n"
" return sa_open_form('unimplemented_form') +\n"
" '<HTML><BODY><B>Unimplemented: page ' + selected + sa_close_form(); }\n"
"}\n"
"function sa_title_string(selected)\n"
"{\n"
" \n"
" if ( selected == 1 ) { return sa_secinfo_title_label; }\n"
" else if ( selected == 2 ) { return sa_passwords_title_label; }\n"
" else if ( selected == 3 ) { return sa_navigator_title_label; }\n"
" else if ( selected == 4 ) { return sa_messenger_title_label; }\n"
" else if ( selected == 5 ) { return sa_applets_title_label; }\n"
" else if ( selected == 6 ) { return sa_certs_intro_title_label; }\n"
" else if ( selected == 7 ) { return sa_yours_title_label; }\n"
" else if ( selected == 8 ) { return sa_people_title_label; }\n"
" else if ( selected == 9 ) { return sa_sites_title_label; }\n"
" else if ( selected == 10 ) { return sa_signers_title_label; }\n"
" else if ( selected == 11 ) { return sa_modules_title_label; }\n"
" else {\n"
" return 'Page ' + selected;\n"
" }\n"
"}\n"
"var fool0;\n"
"var fool1;\n"
"var fool2;\n"
"var fool3;\n"
"var fool4;\n"
"var help_topics = sa_init_array(\n"
" \"\",\n"
" \"nethelp:netscape/collabra:sec_info_intro\",\n"
" \"nethelp:netscape/collabra:password_introduction\",\n"
" \"nethelp:netscape/collabra:HELP_SEC_PREFS_NAVIGATOR\",\n"
" \"nethelp:netscape/collabra:HELP_SEC_PREFS_MESSENGER\",\n"
" \"nethelp:netscape/collabra:HELP_SEC_PREFS_APPLET\",\n"
" \"nethelp:netscape/collabra:HELP_SEC_CERTS\",\n"
" \"nethelp:netscape/collabra:HELP_SEC_CERTS_YOURS\",\n"
" \"nethelp:netscape/collabra:HELP_SEC_CERTS_PEOPLE\",\n"
" \"nethelp:netscape/collabra:HELP_SEC_CERTS_SITES\",\n"
" \"nethelp:netscape/collabra:HELP_SEC_CERTS_ISSUERS\",\n"
" \"nethelp:netscape/collabra:HELP_SEC_CERTS_CRYPTOMODS\");\n"
"function sa_make_dialog(win, selected)\n"
"{\n"
" var index_string;\n"
" if (Event) {\n"
" captureEvents(Event.MOUSEDOWN);\n"
" }\n"
" \n"
" sa_curpage = selected;\n"
" with (win.frames.buttons) {\n"
" fool4 = sa_make_page_intro(\"\", \"#BBCCBB\") +\n"
" sa_open_form('buttons_form') +\n"
" '<CENTER>' +\n"
" '<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0><TR>' +\n"
" '<TD ALIGN=CENTER VALIGN=MIDDLE>' +\n"
" ' <INPUT TYPE=SUBMIT NAME=button VALUE=\"' + sa_ok_button_label +\n"
" '\" onClick=\"parent.sa_ready_submit(parent, ' + selected + ')\">' +\n"
" '</TD><TD WIDTH=10></TD><TD ALIGN=CENTER VALIGN=MIDDLE>' +\n"
" ' <INPUT TYPE=SUBMIT NAME=button VALUE=\"' + sa_cancel_button_label +\n"
" '\">' +\n"
" '</TD><TD WIDTH=10></TD>';\n"
" \n"
" if (have_help) {\n"
" fool4 += '<TD ALIGN=CENTER VALIGN=MIDDLE>' +\n"
" ' <INPUT TYPE=BUTTON NAME=button VALUE=\"' + sa_help_button_label +\n"
" '\" onClick=\"document.location.replace(\\'' + help_topics[selected] +\n"
" '\\')\"></TD>';\n"
" }\n"
" fool4 += '</TR></TABLE>' +\n"
" '</CENTER>' +\n"
" sa_close_form() +\n"
" '</BODY></HTML>';\n"
" if (dogbert_p) {\n"
" document.write(fool4);\n"
" document.close();\n"
" } else {\n"
" location = 'javascript:parent.fool4';\n"
" }\n"
" }\n"
" with (win.frames.extra) {\n"
" fool3 = sa_make_page_intro(\"\", \"#C0C0C0\") + '</BODY></HTML>';\n"
" if (dogbert_p) {\n"
" document.write(fool3);\n"
" document.close();\n"
" } else {\n"
" location = 'javascript:parent.fool3';\n"
" }\n"
" }\n"
" with (win.frames.title) {\n"
" fool0 = sa_make_page_intro(\"\", \"#BBCCBB\") +\n"
" '<TABLE WIDTH=\"100%\"><TR><TD>' +\n"
" '<B><FONT SIZE=\"+2\">' + sa_title_string(selected) +\n"
" '<B></FONT>' +\n"
" '</TD></TR></TABLE>' +\n"
" '</BODY></HTML>';\n"
" if (dogbert_p) {\n"
" document.write(fool0);\n"
" document.close();\n"
" } else {\n"
" location = 'javascript:parent.fool0';\n"
" }\n"
" }\n"
" with (win.frames.index) {\n"
" index_string = sa_make_index_page(selected,\n"
" 0, sa_secinfo_index_label,\n"
" 0, sa_passwords_index_label,\n"
" 0, sa_navigator_index_label,\n"
" 0, sa_messenger_index_label,\n"
" 0, sa_applets_index_label,\n"
" 0, sa_certs_intro_index_label,\n"
" 1, sa_yours_index_label,\n"
" 1, sa_people_index_label,\n"
" 1, sa_sites_index_label,\n"
" 1, sa_signers_index_label,\n"
" 0, sa_modules_index_label\n"
" );\n"
" fool1 = sa_make_page_intro(sa_secinfo_index_label, \"#FFFFFF\") +\n"
" index_string + '</BODY></HTML>';\n"
" if (dogbert_p) {\n"
" document.write(fool1);\n"
" document.close();\n"
" } else {\n"
" location = 'javascript:parent.fool1';\n"
" }\n"
" }\n"
" with(win.frames.content) {\n"
" fool2 = sa_make_selected_page(selected) + '</BODY></HTML>';\n"
" if (dogbert_p) {\n"
" document.write(fool2);\n"
" document.close();\n"
" } else {\n"
" location = 'javascript:parent.fool2';\n"
" }\n"
" }\n"
" return false;\n"
"}\n"
"function onMouseDown(e)\n"
"{\n"
" if ( e.which == 3 ) {\n"
" return false;\n"
" }\n"
" \n"
" return true;\n"
"}\n"
"</SCRIPT>\n"
"</HEAD>\n"
"<FRAMESET ROWS=\"40,*,60\" BORDER=0>\n"
" <FRAME SRC=\"about:blank\" NAME=\"title\" \n"
" MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO NORESIZE BORDER=NO>\n"
" <FRAMESET COLS=\"20%,69%,1%\" BORDER=0\n"
" ONLOAD=\"sa_make_dialog(window, sa_curpage)\">\n"
" <FRAME SRC=\"about:blank\" NAME=\"index\" \n"
" MARGINWIDTH=0 MARGINHEIGHT=0 NORESIZE BORDER=NO>\n"
" <FRAME SRC=\"about:blank\" NAME=\"content\"\n"
" MARGINWIDTH=15 MARGINHEIGHT=10 NORESIZE BORDER=NO>\n"
" <FRAME SRC=\"about:blank\" NAME=\"extra\"\n"
" MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO NORESIZE BORDER=NO>\n"
" </FRAMESET>\n"
" <FRAME SRC=\"about:blank\" NAME=\"buttons\"\n"
" MARGINWIDTH=0 MARGINHEIGHT=10 SCROLLING=NO NORESIZE BORDER=NO>\n"
" <NOFRAMES>\n"
" <B>Security Advisor:</B> if you can read this, you're too close.\n"
" </NOFRAMES>\n"
"</FRAMESET>\n"
"</HTML>\n";
#endif
