/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class java/lang/Object */

/* SYMBOL: "java/lang/Object/getClass()Ljava/lang/Class;", Java_java_lang_Object_getClass_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Object_getClass_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void* java_lang_Object_getClass(void *);
	_P_[0].p = java_lang_Object_getClass(_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Object/hashCode()I", Java_java_lang_Object_hashCode_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Object_hashCode_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long java_lang_Object_hashCode(void *);
	_P_[0].i = java_lang_Object_hashCode(_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Object/clone()Ljava/lang/Object;", Java_java_lang_Object_clone_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Object_clone_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void* java_lang_Object_clone(void *);
	_P_[0].p = java_lang_Object_clone(_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Object/notify()V", Java_java_lang_Object_notify_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Object_notify_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void java_lang_Object_notify(void *);
	(void) java_lang_Object_notify(_P_[0].p);
	return _P_;
}

/* SYMBOL: "java/lang/Object/notifyAll()V", Java_java_lang_Object_notifyAll_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Object_notifyAll_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void java_lang_Object_notifyAll(void *);
	(void) java_lang_Object_notifyAll(_P_[0].p);
	return _P_;
}

/* SYMBOL: "java/lang/Object/wait(J)V", Java_java_lang_Object_wait_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Object_wait_stub(stack_item* _P_, struct execenv* _EE_) {
	Java8 _t1;
	extern void java_lang_Object_wait(void *, int64_t);
	(void) java_lang_Object_wait(_P_[0].p,GET_INT64(_t1, _P_+1));
	return _P_;
}

