/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class java/lang/Class */

/* SYMBOL: "java/lang/Class/forName(Ljava/lang/String;)Ljava/lang/Class;", Java_java_lang_Class_forName_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Class_forName_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void* java_lang_Class_forName(void *, void *);
	_P_[0].p = java_lang_Class_forName(NULL,((_P_[0].p)));
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Class/newInstance()Ljava/lang/Object;", Java_java_lang_Class_newInstance_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Class_newInstance_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void* java_lang_Class_newInstance(void *);
	_P_[0].p = java_lang_Class_newInstance(_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Class/getName()Ljava/lang/String;", Java_java_lang_Class_getName_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Class_getName_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void* java_lang_Class_getName(void *);
	_P_[0].p = java_lang_Class_getName(_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Class/getSuperclass()Ljava/lang/Class;", Java_java_lang_Class_getSuperclass_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Class_getSuperclass_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void* java_lang_Class_getSuperclass(void *);
	_P_[0].p = java_lang_Class_getSuperclass(_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Class/getInterfaces()[Ljava/lang/Class;", Java_java_lang_Class_getInterfaces_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Class_getInterfaces_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void* java_lang_Class_getInterfaces(void *);
	_P_[0].p = java_lang_Class_getInterfaces(_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Class/getClassLoader()Ljava/lang/ClassLoader;", Java_java_lang_Class_getClassLoader_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Class_getClassLoader_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void* java_lang_Class_getClassLoader(void *);
	_P_[0].p = java_lang_Class_getClassLoader(_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "java/lang/Class/isInterface()Z", Java_java_lang_Class_isInterface_stub */
JRI_PUBLIC_API(stack_item*)
Java_java_lang_Class_isInterface_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long java_lang_Class_isInterface(void *);
	_P_[0].i = (java_lang_Class_isInterface(_P_[0].p) ? 1 : 0);
	return _P_ + 1;
}

