#! gmake
# 
#           CONFIDENTIAL AND PROPRIETARY SOURCE CODE OF
#              NETSCAPE COMMUNICATIONS CORPORATION
# Copyright (C) 1996 Netscape Communications Corporation.  All Rights
# Reserved.  Use of this Source Code is subject to the terms of the
# applicable license agreement from Netscape Communications Corporation.
# The copyright notice(s) in this Source Code does not indicate actual or
# intended publication of this Source Code.
#

include manifest.mn
include $(DEPTH)/config/config.mk

ifeq ($(OS_ARCH),HP-UX)
ASFILES	+= ret_cr16.s
endif

include $(DEPTH)/security/secrules.mk
