/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class netscape_net_URLInputStream */

#ifndef _Included_netscape_net_URLInputStream
#define _Included_netscape_net_URLInputStream
struct Hnetscape_net_URLConnection;

typedef struct Classnetscape_net_URLInputStream {
    struct Hnetscape_net_URLConnection *connection;
} Classnetscape_net_URLInputStream;
HandleTo(netscape_net_URLInputStream);

extern void netscape_net_URLInputStream_open(struct Hnetscape_net_URLInputStream* self);
extern long netscape_net_URLInputStream_read(struct Hnetscape_net_URLInputStream* self,HArrayOfByte *,long,long);
extern long netscape_net_URLInputStream_available(struct Hnetscape_net_URLInputStream* self);
#endif
