/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class netscape_net_URLStreamHandler */

#ifndef _Included_netscape_net_URLStreamHandler
#define _Included_netscape_net_URLStreamHandler

typedef struct Classnetscape_net_URLStreamHandler {
    char PAD;	/* ANSI C requires structures to have a least one member */
} Classnetscape_net_URLStreamHandler;
HandleTo(netscape_net_URLStreamHandler);

#endif
