/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_awt_Frame */

#ifndef _Included_java_awt_Frame
#define _Included_java_awt_Frame
struct Hjava_awt_peer_ComponentPeer;
struct Hjava_awt_Container;
struct Hjava_awt_Color;
struct Hjava_awt_Font;
struct Hjava_awt_Component;
struct Hjava_awt_LayoutManager;
struct Hjava_lang_String;
struct Hjava_awt_Image;
struct Hjava_awt_MenuBar;

typedef struct Classjava_awt_Frame {
    struct Hjava_awt_peer_ComponentPeer *peer;
    struct Hjava_awt_Container *parent;
    long x;
    long y;
    long width;
    long height;
    struct Hjava_awt_Color *foreground;
    struct Hjava_awt_Color *background;
    struct Hjava_awt_Font *font;
    /*boolean*/ long visible;
    /*boolean*/ long enabled;
    /*boolean*/ long valid;
    long ncomponents;
    struct HArrayOfObject *component;
    struct Hjava_awt_LayoutManager *layoutMgr;
    struct Hjava_lang_String *warningString;
#define java_awt_Frame_DEFAULT_CURSOR	0L
#define java_awt_Frame_CROSSHAIR_CURSOR	1L
#define java_awt_Frame_TEXT_CURSOR	2L
#define java_awt_Frame_WAIT_CURSOR	3L
#define java_awt_Frame_SW_RESIZE_CURSOR	4L
#define java_awt_Frame_SE_RESIZE_CURSOR	5L
#define java_awt_Frame_NW_RESIZE_CURSOR	6L
#define java_awt_Frame_NE_RESIZE_CURSOR	7L
#define java_awt_Frame_N_RESIZE_CURSOR	8L
#define java_awt_Frame_S_RESIZE_CURSOR	9L
#define java_awt_Frame_W_RESIZE_CURSOR	10L
#define java_awt_Frame_E_RESIZE_CURSOR	11L
#define java_awt_Frame_HAND_CURSOR	12L
#define java_awt_Frame_MOVE_CURSOR	13L
    struct Hjava_lang_String *title;
    struct Hjava_awt_Image *icon;
    struct Hjava_awt_MenuBar *menuBar;
    /*boolean*/ long resizable;
    struct Hjava_awt_Image *cursorImage;
    long cursorType;
    struct Hjava_awt_Color *cursorFg;
    struct Hjava_awt_Color *cursorBg;
} Classjava_awt_Frame;
HandleTo(java_awt_Frame);

#endif
