/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class java_awt_Component */

#ifndef _Included_java_awt_Component
#define _Included_java_awt_Component
struct Hjava_awt_peer_ComponentPeer;
struct Hjava_awt_Container;
struct Hjava_awt_Color;
struct Hjava_awt_Font;

typedef struct Classjava_awt_Component {
    struct Hjava_awt_peer_ComponentPeer *peer;
    struct Hjava_awt_Container *parent;
    long x;
    long y;
    long width;
    long height;
    struct Hjava_awt_Color *foreground;
    struct Hjava_awt_Color *background;
    struct Hjava_awt_Font *font;
    /*boolean*/ long visible;
    /*boolean*/ long enabled;
    /*boolean*/ long valid;
} Classjava_awt_Component;
HandleTo(java_awt_Component);

#endif
