/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class netscape_applet_MozillaAppletContext */

#ifndef _Included_netscape_applet_MozillaAppletContext
#define _Included_netscape_applet_MozillaAppletContext
struct Hnetscape_applet_Mapping;
struct Hjava_util_Hashtable;
struct Hjava_net_URL;
struct Hjava_lang_Integer;

typedef struct Classnetscape_applet_MozillaAppletContext {
    long frameMWContext;
    struct Hnetscape_applet_Mapping *appletFrames;
    struct Hjava_util_Hashtable *imageCache;
    struct Hjava_util_Hashtable *audioClipCache;
    struct Hjava_net_URL *documentURL;
    struct Hjava_lang_Integer *contextID;
/* Inaccessible static: console */
/* Inaccessible static: totalApplets */
/* Inaccessible static: trimThreshold */
/* Inaccessible static: noisyTrimming */
/* Inaccessible static: appletContexts */
/* Inaccessible static: debug */
} Classnetscape_applet_MozillaAppletContext;
HandleTo(netscape_applet_MozillaAppletContext);

struct Hjava_lang_String;
extern void netscape_applet_MozillaAppletContext_pShowDocument(struct Hnetscape_applet_MozillaAppletContext* self,struct Hjava_lang_String *,struct Hjava_lang_String *,struct Hjava_lang_String *);
extern void netscape_applet_MozillaAppletContext_pShowStatus(struct Hnetscape_applet_MozillaAppletContext* self,struct Hjava_lang_String *);
extern void netscape_applet_MozillaAppletContext_pMochaOnLoad(struct Hnetscape_applet_MozillaAppletContext* self,long);
extern void netscape_applet_MozillaAppletContext_setConsoleState0(struct Hnetscape_applet_MozillaAppletContext* self,long);
#endif
