/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class sun_awt_motif_MTextAreaPeer */

#ifndef _Included_sun_awt_motif_MTextAreaPeer
#define _Included_sun_awt_motif_MTextAreaPeer
struct Hjava_awt_Component;

typedef struct Classsun_awt_motif_MTextAreaPeer {
    struct Hjava_awt_Component *target;
    long pData;
} Classsun_awt_motif_MTextAreaPeer;
HandleTo(sun_awt_motif_MTextAreaPeer);

struct Hsun_awt_motif_MComponentPeer;
extern void sun_awt_motif_MTextAreaPeer_create(struct Hsun_awt_motif_MTextAreaPeer* self,struct Hsun_awt_motif_MComponentPeer *);
struct Hjava_awt_Color;
extern void sun_awt_motif_MTextAreaPeer_setTextBackground(struct Hsun_awt_motif_MTextAreaPeer* self,struct Hjava_awt_Color *);
extern void sun_awt_motif_MTextAreaPeer_pSetEditable(struct Hsun_awt_motif_MTextAreaPeer* self,/*boolean*/ long);
extern void sun_awt_motif_MTextAreaPeer_select(struct Hsun_awt_motif_MTextAreaPeer* self,long,long);
extern long sun_awt_motif_MTextAreaPeer_getSelectionStart(struct Hsun_awt_motif_MTextAreaPeer* self);
extern long sun_awt_motif_MTextAreaPeer_getSelectionEnd(struct Hsun_awt_motif_MTextAreaPeer* self);
struct Hjava_lang_String;
extern void sun_awt_motif_MTextAreaPeer_setText(struct Hsun_awt_motif_MTextAreaPeer* self,struct Hjava_lang_String *);
extern struct Hjava_lang_String *sun_awt_motif_MTextAreaPeer_getText(struct Hsun_awt_motif_MTextAreaPeer* self);
extern void sun_awt_motif_MTextAreaPeer_insertText(struct Hsun_awt_motif_MTextAreaPeer* self,struct Hjava_lang_String *,long);
extern void sun_awt_motif_MTextAreaPeer_replaceText(struct Hsun_awt_motif_MTextAreaPeer* self,struct Hjava_lang_String *,long,long);
#endif
