/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class sun_awt_motif_MWindowPeer */

#ifndef _Included_sun_awt_motif_MWindowPeer
#define _Included_sun_awt_motif_MWindowPeer
struct Hjava_awt_Component;
struct Hjava_awt_Insets;

typedef struct Classsun_awt_motif_MWindowPeer {
    struct Hjava_awt_Component *target;
    long pData;
    struct Hjava_awt_Insets *insets;
/* Inaccessible static: allWindows */
} Classsun_awt_motif_MWindowPeer;
HandleTo(sun_awt_motif_MWindowPeer);

struct Hsun_awt_motif_MComponentPeer;
extern void sun_awt_motif_MWindowPeer_create(struct Hsun_awt_motif_MWindowPeer* self,struct Hsun_awt_motif_MComponentPeer *);
extern void sun_awt_motif_MWindowPeer_pShow(struct Hsun_awt_motif_MWindowPeer* self);
extern void sun_awt_motif_MWindowPeer_pHide(struct Hsun_awt_motif_MWindowPeer* self);
extern void sun_awt_motif_MWindowPeer_pReshape(struct Hsun_awt_motif_MWindowPeer* self,long,long,long,long);
extern void sun_awt_motif_MWindowPeer_pDispose(struct Hsun_awt_motif_MWindowPeer* self);
extern void sun_awt_motif_MWindowPeer_toBack(struct Hsun_awt_motif_MWindowPeer* self);
#endif
