/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class sun_awt_motif_MScrollbarPeer */

#ifndef _Included_sun_awt_motif_MScrollbarPeer
#define _Included_sun_awt_motif_MScrollbarPeer
struct Hjava_awt_Component;

typedef struct Classsun_awt_motif_MScrollbarPeer {
    struct Hjava_awt_Component *target;
    long pData;
} Classsun_awt_motif_MScrollbarPeer;
HandleTo(sun_awt_motif_MScrollbarPeer);

struct Hsun_awt_motif_MComponentPeer;
extern void sun_awt_motif_MScrollbarPeer_create(struct Hsun_awt_motif_MScrollbarPeer* self,struct Hsun_awt_motif_MComponentPeer *);
extern void sun_awt_motif_MScrollbarPeer_setValue(struct Hsun_awt_motif_MScrollbarPeer* self,long);
extern void sun_awt_motif_MScrollbarPeer_setValues(struct Hsun_awt_motif_MScrollbarPeer* self,long,long,long,long);
extern void sun_awt_motif_MScrollbarPeer_setLineIncrement(struct Hsun_awt_motif_MScrollbarPeer* self,long);
extern void sun_awt_motif_MScrollbarPeer_setPageIncrement(struct Hsun_awt_motif_MScrollbarPeer* self,long);
#endif
