/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class sun_awt_motif_MMenuBarPeer */

#ifndef _Included_sun_awt_motif_MMenuBarPeer
#define _Included_sun_awt_motif_MMenuBarPeer
struct Hjava_awt_MenuBar;

typedef struct Classsun_awt_motif_MMenuBarPeer {
    long pData;
    struct Hjava_awt_MenuBar *target;
} Classsun_awt_motif_MMenuBarPeer;
HandleTo(sun_awt_motif_MMenuBarPeer);

struct Hjava_awt_Frame;
extern void sun_awt_motif_MMenuBarPeer_create(struct Hsun_awt_motif_MMenuBarPeer* self,struct Hjava_awt_Frame *);
extern void sun_awt_motif_MMenuBarPeer_dispose(struct Hsun_awt_motif_MMenuBarPeer* self);
#endif
