/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class sun_awt_motif_MFramePeer */

#ifndef _Included_sun_awt_motif_MFramePeer
#define _Included_sun_awt_motif_MFramePeer
struct Hjava_awt_Component;
struct Hjava_awt_Insets;

typedef struct Classsun_awt_motif_MFramePeer {
    struct Hjava_awt_Component *target;
    long pData;
    struct Hjava_awt_Insets *insets;
/* Inaccessible static: allFrames */
} Classsun_awt_motif_MFramePeer;
HandleTo(sun_awt_motif_MFramePeer);

struct Hsun_awt_motif_MComponentPeer;
struct Hjava_lang_Object;
extern void sun_awt_motif_MFramePeer_create(struct Hsun_awt_motif_MFramePeer* self,struct Hsun_awt_motif_MComponentPeer *,struct Hjava_lang_Object *);
struct Hjava_lang_String;
extern void sun_awt_motif_MFramePeer_pSetTitle(struct Hsun_awt_motif_MFramePeer* self,struct Hjava_lang_String *);
extern void sun_awt_motif_MFramePeer_pShow(struct Hsun_awt_motif_MFramePeer* self);
extern void sun_awt_motif_MFramePeer_pHide(struct Hsun_awt_motif_MFramePeer* self);
extern void sun_awt_motif_MFramePeer_pReshape(struct Hsun_awt_motif_MFramePeer* self,long,long,long,long);
extern void sun_awt_motif_MFramePeer_pDispose(struct Hsun_awt_motif_MFramePeer* self);
struct Hsun_awt_image_ImageRepresentation;
extern void sun_awt_motif_MFramePeer_pSetIconImage(struct Hsun_awt_motif_MFramePeer* self,struct Hsun_awt_image_ImageRepresentation *);
extern void sun_awt_motif_MFramePeer_setResizable(struct Hsun_awt_motif_MFramePeer* self,/*boolean*/ long);
struct Hjava_awt_MenuBar;
extern void sun_awt_motif_MFramePeer_pSetMenuBar(struct Hsun_awt_motif_MFramePeer* self,struct Hjava_awt_MenuBar *);
extern void sun_awt_motif_MFramePeer_toBack(struct Hsun_awt_motif_MFramePeer* self);
extern void sun_awt_motif_MFramePeer_setCursor(struct Hsun_awt_motif_MFramePeer* self,long);
#endif
