/* DO NOT EDIT THIS FILE - it is machine generated */
#include "native.h"
/* Header for class sun_awt_motif_MMenuItemPeer */

#ifndef _Included_sun_awt_motif_MMenuItemPeer
#define _Included_sun_awt_motif_MMenuItemPeer
struct Hjava_awt_MenuItem;

typedef struct Classsun_awt_motif_MMenuItemPeer {
    long pData;
    /*boolean*/ long isCheckbox;
    struct Hjava_awt_MenuItem *target;
} Classsun_awt_motif_MMenuItemPeer;
HandleTo(sun_awt_motif_MMenuItemPeer);

struct Hjava_awt_Menu;
extern void sun_awt_motif_MMenuItemPeer_create(struct Hsun_awt_motif_MMenuItemPeer* self,struct Hjava_awt_Menu *);
extern void sun_awt_motif_MMenuItemPeer_enable(struct Hsun_awt_motif_MMenuItemPeer* self);
extern void sun_awt_motif_MMenuItemPeer_disable(struct Hsun_awt_motif_MMenuItemPeer* self);
extern void sun_awt_motif_MMenuItemPeer_dispose(struct Hsun_awt_motif_MMenuItemPeer* self);
struct Hjava_lang_String;
extern void sun_awt_motif_MMenuItemPeer_setLabel(struct Hsun_awt_motif_MMenuItemPeer* self,struct Hjava_lang_String *);
#endif
