IGNORE_MANIFEST=1
#//------------------------------------------------------------------------
#//
#// Makefile to build the cert library
#//
#//------------------------------------------------------------------------


#//------------------------------------------------------------------------
#//
#// Specify the depth of the current directory relative to the
#// root of NS
#//
#//------------------------------------------------------------------------
DEPTH= ..\..\..

!ifndef MAKE_OBJ_TYPE
MAKE_OBJ_TYPE=EXE
!endif

#//------------------------------------------------------------------------
#//
#// Define any Public Make Variables here: (ie. PDFFILE, MAPFILE, ...)
#//
#//------------------------------------------------------------------------
LIBNAME=pkcs12$(MOZ_BITS)
PDBFILE=$(LIBNAME).pdb

LINCS = -I$(PUBLIC)/security \
        -I$(DEPTH)\include

#//------------------------------------------------------------------------
#// 
#// Define the files necessary to build the target (ie. OBJS)
#//
#//------------------------------------------------------------------------
OBJS=                         \
    .\$(OBJDIR)\p12creat.obj  \
    .\$(OBJDIR)\p12dec.obj  \
    .\$(OBJDIR)\p12exp.obj  \
    .\$(OBJDIR)\p12local.obj  \
    .\$(OBJDIR)\p12plcy.obj \
    $(NULL)

#//------------------------------------------------------------------------
#//
#// Define any Public Targets here (ie. PROGRAM, LIBRARY, DLL, ...)
#// (these must be defined before the common makefiles are included)
#//
#//------------------------------------------------------------------------
LIBRARY=.\$(OBJDIR)\$(LIBNAME).lib

#//------------------------------------------------------------------------
#//
#// install headers
#//
#//------------------------------------------------------------------------
INSTALL_DIR=$(PUBLIC)\security
INSTALL_FILE_LIST=pkcs12.h pkcs12t.h p12plcy.h

#//------------------------------------------------------------------------
#//
#// Include the common makefile rules
#//
#//------------------------------------------------------------------------
include <$(DEPTH)/config/rules.mak>

install:: $(LIBRARY)
    $(MAKE_INSTALL) $(LIBRARY) $(DIST)\lib

export:: INSTALL_FILES

