/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/motif/MDialogPeer */

/* SYMBOL: "sun/awt/motif/MDialogPeer/create(Lsun/awt/motif/MComponentPeer;Ljava/lang/Object;)V", Java_sun_awt_motif_MDialogPeer_create_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MDialogPeer_create_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MDialogPeer_create(void *, void *, void *);
	(void) sun_awt_motif_MDialogPeer_create(_P_[0].p,((_P_[1].p)),((_P_[2].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MDialogPeer/pSetTitle(Ljava/lang/String;)V", Java_sun_awt_motif_MDialogPeer_pSetTitle_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MDialogPeer_pSetTitle_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MDialogPeer_pSetTitle(void *, void *);
	(void) sun_awt_motif_MDialogPeer_pSetTitle(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MDialogPeer/pShow()V", Java_sun_awt_motif_MDialogPeer_pShow_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MDialogPeer_pShow_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MDialogPeer_pShow(void *);
	(void) sun_awt_motif_MDialogPeer_pShow(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MDialogPeer/pHide()V", Java_sun_awt_motif_MDialogPeer_pHide_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MDialogPeer_pHide_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MDialogPeer_pHide(void *);
	(void) sun_awt_motif_MDialogPeer_pHide(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MDialogPeer/pReshape(IIII)V", Java_sun_awt_motif_MDialogPeer_pReshape_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MDialogPeer_pReshape_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MDialogPeer_pReshape(void *, long, long, long, long);
	(void) sun_awt_motif_MDialogPeer_pReshape(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MDialogPeer/pDispose()V", Java_sun_awt_motif_MDialogPeer_pDispose_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MDialogPeer_pDispose_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MDialogPeer_pDispose(void *);
	(void) sun_awt_motif_MDialogPeer_pDispose(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MDialogPeer/setResizable(Z)V", Java_sun_awt_motif_MDialogPeer_setResizable_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MDialogPeer_setResizable_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MDialogPeer_setResizable(void *, long);
	(void) sun_awt_motif_MDialogPeer_setResizable(_P_[0].p,((_P_[1].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MDialogPeer/toBack()V", Java_sun_awt_motif_MDialogPeer_toBack_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MDialogPeer_toBack_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MDialogPeer_toBack(void *);
	(void) sun_awt_motif_MDialogPeer_toBack(_P_[0].p);
	return _P_;
}

