/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/motif/X11FontMetrics */

/* SYMBOL: "sun/awt/motif/X11FontMetrics/stringWidth(Ljava/lang/String;)I", Java_sun_awt_motif_X11FontMetrics_stringWidth_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11FontMetrics_stringWidth_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_motif_X11FontMetrics_stringWidth(void *, void *);
	_P_[0].i = sun_awt_motif_X11FontMetrics_stringWidth(_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/motif/X11FontMetrics/stringExtent(Ljava/lang/String;)Ljava/awt/Dimension;", Java_sun_awt_motif_X11FontMetrics_stringExtent_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11FontMetrics_stringExtent_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void* sun_awt_motif_X11FontMetrics_stringExtent(void *, void *);
	_P_[0].p = sun_awt_motif_X11FontMetrics_stringExtent(_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/motif/X11FontMetrics/charsWidth([CII)I", Java_sun_awt_motif_X11FontMetrics_charsWidth_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11FontMetrics_charsWidth_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_motif_X11FontMetrics_charsWidth(void *, void *, long, long);
	_P_[0].i = sun_awt_motif_X11FontMetrics_charsWidth(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)));
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/motif/X11FontMetrics/bytesWidth([BII)I", Java_sun_awt_motif_X11FontMetrics_bytesWidth_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11FontMetrics_bytesWidth_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_motif_X11FontMetrics_bytesWidth(void *, void *, long, long);
	_P_[0].i = sun_awt_motif_X11FontMetrics_bytesWidth(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)));
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/motif/X11FontMetrics/init()V", Java_sun_awt_motif_X11FontMetrics_init_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11FontMetrics_init_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11FontMetrics_init(void *);
	(void) sun_awt_motif_X11FontMetrics_init(_P_[0].p);
	return _P_;
}

