/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/motif/MCheckboxMenuItemPeer */

/* SYMBOL: "sun/awt/motif/MCheckboxMenuItemPeer/setState(Z)V", Java_sun_awt_motif_MCheckboxMenuItemPeer_setState_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MCheckboxMenuItemPeer_setState_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MCheckboxMenuItemPeer_setState(void *, long);
	(void) sun_awt_motif_MCheckboxMenuItemPeer_setState(_P_[0].p,((_P_[1].i)));
	return _P_;
}

