/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/motif/MMenuItemPeer */

/* SYMBOL: "sun/awt/motif/MMenuItemPeer/create(Ljava/awt/Menu;)V", Java_sun_awt_motif_MMenuItemPeer_create_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MMenuItemPeer_create_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MMenuItemPeer_create(void *, void *);
	(void) sun_awt_motif_MMenuItemPeer_create(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MMenuItemPeer/enable()V", Java_sun_awt_motif_MMenuItemPeer_enable_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MMenuItemPeer_enable_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MMenuItemPeer_enable(void *);
	(void) sun_awt_motif_MMenuItemPeer_enable(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MMenuItemPeer/disable()V", Java_sun_awt_motif_MMenuItemPeer_disable_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MMenuItemPeer_disable_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MMenuItemPeer_disable(void *);
	(void) sun_awt_motif_MMenuItemPeer_disable(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MMenuItemPeer/dispose()V", Java_sun_awt_motif_MMenuItemPeer_dispose_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MMenuItemPeer_dispose_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MMenuItemPeer_dispose(void *);
	(void) sun_awt_motif_MMenuItemPeer_dispose(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MMenuItemPeer/setLabel(Ljava/lang/String;)V", Java_sun_awt_motif_MMenuItemPeer_setLabel_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MMenuItemPeer_setLabel_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MMenuItemPeer_setLabel(void *, void *);
	(void) sun_awt_motif_MMenuItemPeer_setLabel(_P_[0].p,((_P_[1].p)));
	return _P_;
}

