/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/motif/MWindowPeer */

/* SYMBOL: "sun/awt/motif/MWindowPeer/create(Lsun/awt/motif/MComponentPeer;)V", Java_sun_awt_motif_MWindowPeer_create_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MWindowPeer_create_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MWindowPeer_create(void *, void *);
	(void) sun_awt_motif_MWindowPeer_create(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MWindowPeer/pShow()V", Java_sun_awt_motif_MWindowPeer_pShow_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MWindowPeer_pShow_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MWindowPeer_pShow(void *);
	(void) sun_awt_motif_MWindowPeer_pShow(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MWindowPeer/pHide()V", Java_sun_awt_motif_MWindowPeer_pHide_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MWindowPeer_pHide_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MWindowPeer_pHide(void *);
	(void) sun_awt_motif_MWindowPeer_pHide(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MWindowPeer/pReshape(IIII)V", Java_sun_awt_motif_MWindowPeer_pReshape_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MWindowPeer_pReshape_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MWindowPeer_pReshape(void *, long, long, long, long);
	(void) sun_awt_motif_MWindowPeer_pReshape(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MWindowPeer/pDispose()V", Java_sun_awt_motif_MWindowPeer_pDispose_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MWindowPeer_pDispose_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MWindowPeer_pDispose(void *);
	(void) sun_awt_motif_MWindowPeer_pDispose(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MWindowPeer/toBack()V", Java_sun_awt_motif_MWindowPeer_toBack_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MWindowPeer_toBack_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MWindowPeer_toBack(void *);
	(void) sun_awt_motif_MWindowPeer_toBack(_P_[0].p);
	return _P_;
}

