/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/motif/InputThread */

/* SYMBOL: "sun/awt/motif/InputThread/run()V", Java_sun_awt_motif_InputThread_run_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_InputThread_run_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_InputThread_run(void *);
	(void) sun_awt_motif_InputThread_run(_P_[0].p);
	return _P_;
}

