/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/motif/X11Graphics */

/* SYMBOL: "sun/awt/motif/X11Graphics/createFromComponent(Lsun/awt/motif/MComponentPeer;)V", Java_sun_awt_motif_X11Graphics_createFromComponent_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_createFromComponent_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_createFromComponent(void *, void *);
	(void) sun_awt_motif_X11Graphics_createFromComponent(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/createFromGraphics(Lsun/awt/motif/X11Graphics;)V", Java_sun_awt_motif_X11Graphics_createFromGraphics_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_createFromGraphics_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_createFromGraphics(void *, void *);
	(void) sun_awt_motif_X11Graphics_createFromGraphics(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/imageCreate(Lsun/awt/image/ImageRepresentation;)V", Java_sun_awt_motif_X11Graphics_imageCreate_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_imageCreate_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_imageCreate(void *, void *);
	(void) sun_awt_motif_X11Graphics_imageCreate(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/pSetFont(Ljava/awt/Font;)V", Java_sun_awt_motif_X11Graphics_pSetFont_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_pSetFont_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_pSetFont(void *, void *);
	(void) sun_awt_motif_X11Graphics_pSetFont(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/pSetForeground(Ljava/awt/Color;)V", Java_sun_awt_motif_X11Graphics_pSetForeground_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_pSetForeground_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_pSetForeground(void *, void *);
	(void) sun_awt_motif_X11Graphics_pSetForeground(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/dispose()V", Java_sun_awt_motif_X11Graphics_dispose_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_dispose_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_dispose(void *);
	(void) sun_awt_motif_X11Graphics_dispose(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/setPaintMode()V", Java_sun_awt_motif_X11Graphics_setPaintMode_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_setPaintMode_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_setPaintMode(void *);
	(void) sun_awt_motif_X11Graphics_setPaintMode(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/setXORMode(Ljava/awt/Color;)V", Java_sun_awt_motif_X11Graphics_setXORMode_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_setXORMode_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_setXORMode(void *, void *);
	(void) sun_awt_motif_X11Graphics_setXORMode(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/getClipRect()Ljava/awt/Rectangle;", Java_sun_awt_motif_X11Graphics_getClipRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_getClipRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void* sun_awt_motif_X11Graphics_getClipRect(void *);
	_P_[0].p = sun_awt_motif_X11Graphics_getClipRect(_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/clipRect(IIII)V", Java_sun_awt_motif_X11Graphics_clipRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_clipRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_clipRect(void *, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_clipRect(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/clearRect(IIII)V", Java_sun_awt_motif_X11Graphics_clearRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_clearRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_clearRect(void *, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_clearRect(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/fillRect(IIII)V", Java_sun_awt_motif_X11Graphics_fillRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_fillRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_fillRect(void *, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_fillRect(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/drawRect(IIII)V", Java_sun_awt_motif_X11Graphics_drawRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_drawRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_drawRect(void *, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_drawRect(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/drawString(Ljava/lang/String;II)V", Java_sun_awt_motif_X11Graphics_drawString_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_drawString_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_drawString(void *, void *, long, long);
	(void) sun_awt_motif_X11Graphics_drawString(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/drawChars([CIIII)V", Java_sun_awt_motif_X11Graphics_drawChars_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_drawChars_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_drawChars(void *, void *, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_drawChars(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/drawBytes([BIIII)V", Java_sun_awt_motif_X11Graphics_drawBytes_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_drawBytes_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_drawBytes(void *, void *, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_drawBytes(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/drawStringWidth(Ljava/lang/String;II)I", Java_sun_awt_motif_X11Graphics_drawStringWidth_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_drawStringWidth_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_motif_X11Graphics_drawStringWidth(void *, void *, long, long);
	_P_[0].i = sun_awt_motif_X11Graphics_drawStringWidth(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)));
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/drawCharsWidth([CIIII)I", Java_sun_awt_motif_X11Graphics_drawCharsWidth_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_drawCharsWidth_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_motif_X11Graphics_drawCharsWidth(void *, void *, long, long, long, long);
	_P_[0].i = sun_awt_motif_X11Graphics_drawCharsWidth(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)));
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/drawBytesWidth([BIIII)I", Java_sun_awt_motif_X11Graphics_drawBytesWidth_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_drawBytesWidth_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_motif_X11Graphics_drawBytesWidth(void *, void *, long, long, long, long);
	_P_[0].i = sun_awt_motif_X11Graphics_drawBytesWidth(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)));
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/drawLine(IIII)V", Java_sun_awt_motif_X11Graphics_drawLine_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_drawLine_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_drawLine(void *, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_drawLine(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/copyArea(IIIIII)V", Java_sun_awt_motif_X11Graphics_copyArea_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_copyArea_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_copyArea(void *, long, long, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_copyArea(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)),((_P_[6].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/drawRoundRect(IIIIII)V", Java_sun_awt_motif_X11Graphics_drawRoundRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_drawRoundRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_drawRoundRect(void *, long, long, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_drawRoundRect(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)),((_P_[6].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/fillRoundRect(IIIIII)V", Java_sun_awt_motif_X11Graphics_fillRoundRect_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_fillRoundRect_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_fillRoundRect(void *, long, long, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_fillRoundRect(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)),((_P_[6].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/drawPolygon([I[II)V", Java_sun_awt_motif_X11Graphics_drawPolygon_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_drawPolygon_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_drawPolygon(void *, void *, void *, long);
	(void) sun_awt_motif_X11Graphics_drawPolygon(_P_[0].p,((_P_[1].p)),((_P_[2].p)),((_P_[3].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/fillPolygon([I[II)V", Java_sun_awt_motif_X11Graphics_fillPolygon_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_fillPolygon_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_fillPolygon(void *, void *, void *, long);
	(void) sun_awt_motif_X11Graphics_fillPolygon(_P_[0].p,((_P_[1].p)),((_P_[2].p)),((_P_[3].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/drawOval(IIII)V", Java_sun_awt_motif_X11Graphics_drawOval_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_drawOval_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_drawOval(void *, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_drawOval(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/fillOval(IIII)V", Java_sun_awt_motif_X11Graphics_fillOval_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_fillOval_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_fillOval(void *, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_fillOval(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/drawArc(IIIIII)V", Java_sun_awt_motif_X11Graphics_drawArc_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_drawArc_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_drawArc(void *, long, long, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_drawArc(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)),((_P_[6].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/X11Graphics/fillArc(IIIIII)V", Java_sun_awt_motif_X11Graphics_fillArc_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_X11Graphics_fillArc_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_X11Graphics_fillArc(void *, long, long, long, long, long, long);
	(void) sun_awt_motif_X11Graphics_fillArc(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].i)),((_P_[6].i)));
	return _P_;
}

