/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/motif/MCheckboxPeer */

/* SYMBOL: "sun/awt/motif/MCheckboxPeer/create(Lsun/awt/motif/MComponentPeer;)V", Java_sun_awt_motif_MCheckboxPeer_create_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MCheckboxPeer_create_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MCheckboxPeer_create(void *, void *);
	(void) sun_awt_motif_MCheckboxPeer_create(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MCheckboxPeer/setLabel(Ljava/lang/String;)V", Java_sun_awt_motif_MCheckboxPeer_setLabel_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MCheckboxPeer_setLabel_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MCheckboxPeer_setLabel(void *, void *);
	(void) sun_awt_motif_MCheckboxPeer_setLabel(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MCheckboxPeer/setState(Z)V", Java_sun_awt_motif_MCheckboxPeer_setState_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MCheckboxPeer_setState_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MCheckboxPeer_setState(void *, long);
	(void) sun_awt_motif_MCheckboxPeer_setState(_P_[0].p,((_P_[1].i)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MCheckboxPeer/setCheckboxGroup(Ljava/awt/CheckboxGroup;)V", Java_sun_awt_motif_MCheckboxPeer_setCheckboxGroup_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MCheckboxPeer_setCheckboxGroup_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MCheckboxPeer_setCheckboxGroup(void *, void *);
	(void) sun_awt_motif_MCheckboxPeer_setCheckboxGroup(_P_[0].p,((_P_[1].p)));
	return _P_;
}

