/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/motif/MLabelPeer */

/* SYMBOL: "sun/awt/motif/MLabelPeer/create(Lsun/awt/motif/MComponentPeer;)V", Java_sun_awt_motif_MLabelPeer_create_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MLabelPeer_create_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MLabelPeer_create(void *, void *);
	(void) sun_awt_motif_MLabelPeer_create(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MLabelPeer/setText(Ljava/lang/String;)V", Java_sun_awt_motif_MLabelPeer_setText_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MLabelPeer_setText_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MLabelPeer_setText(void *, void *);
	(void) sun_awt_motif_MLabelPeer_setText(_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/motif/MLabelPeer/setAlignment(I)V", Java_sun_awt_motif_MLabelPeer_setAlignment_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_motif_MLabelPeer_setAlignment_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_motif_MLabelPeer_setAlignment(void *, long);
	(void) sun_awt_motif_MLabelPeer_setAlignment(_P_[0].p,((_P_[1].i)));
	return _P_;
}

