/* DO NOT EDIT THIS FILE - it is machine generated */
#include "StubPreamble.h"
/* Stubs for class sun/awt/image/ImageRepresentation */

/* SYMBOL: "sun/awt/image/ImageRepresentation/offscreenInit()V", Java_sun_awt_image_ImageRepresentation_offscreenInit_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_image_ImageRepresentation_offscreenInit_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_image_ImageRepresentation_offscreenInit(void *);
	(void) sun_awt_image_ImageRepresentation_offscreenInit(_P_[0].p);
	return _P_;
}

/* SYMBOL: "sun/awt/image/ImageRepresentation/setBytePixels(IIIILjava/awt/image/ColorModel;[BII)Z", Java_sun_awt_image_ImageRepresentation_setBytePixels_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_image_ImageRepresentation_setBytePixels_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_image_ImageRepresentation_setBytePixels(void *, long, long, long, long, void *, void *, long, long);
	_P_[0].i = (sun_awt_image_ImageRepresentation_setBytePixels(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].p)),((_P_[6].p)),((_P_[7].i)),((_P_[8].i))) ? 1 : 0);
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/image/ImageRepresentation/setIntPixels(IIIILjava/awt/image/ColorModel;[III)Z", Java_sun_awt_image_ImageRepresentation_setIntPixels_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_image_ImageRepresentation_setIntPixels_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_image_ImageRepresentation_setIntPixels(void *, long, long, long, long, void *, void *, long, long);
	_P_[0].i = (sun_awt_image_ImageRepresentation_setIntPixels(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].p)),((_P_[6].p)),((_P_[7].i)),((_P_[8].i))) ? 1 : 0);
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/image/ImageRepresentation/finish(Z)Z", Java_sun_awt_image_ImageRepresentation_finish_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_image_ImageRepresentation_finish_stub(stack_item* _P_, struct execenv* _EE_) {
	extern long sun_awt_image_ImageRepresentation_finish(void *, long);
	_P_[0].i = (sun_awt_image_ImageRepresentation_finish(_P_[0].p,((_P_[1].i))) ? 1 : 0);
	return _P_ + 1;
}

/* SYMBOL: "sun/awt/image/ImageRepresentation/imageDraw(Ljava/awt/Graphics;IILjava/awt/Color;)V", Java_sun_awt_image_ImageRepresentation_imageDraw_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_image_ImageRepresentation_imageDraw_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_image_ImageRepresentation_imageDraw(void *, void *, long, long, void *);
	(void) sun_awt_image_ImageRepresentation_imageDraw(_P_[0].p,((_P_[1].p)),((_P_[2].i)),((_P_[3].i)),((_P_[4].p)));
	return _P_;
}

/* SYMBOL: "sun/awt/image/ImageRepresentation/disposeImage()V", Java_sun_awt_image_ImageRepresentation_disposeImage_stub */
JRI_PUBLIC_API(stack_item*)
Java_sun_awt_image_ImageRepresentation_disposeImage_stub(stack_item* _P_, struct execenv* _EE_) {
	extern void sun_awt_image_ImageRepresentation_disposeImage(void *);
	(void) sun_awt_image_ImageRepresentation_disposeImage(_P_[0].p);
	return _P_;
}

